In [1]:
# import all the filenames
from allfunctions import *

In [2]:
%load_ext autoreload
%autoreload 2

3  def GradientBoostingCVModel(filename):

4  def RandomForestCVModel(filename):

In [3]:
def wrapper(functionList = []):
    if __name__ == '__main__':
        global model_selection
        global filenames

        # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
        filenames = ['AB.pickle', 'BC.pickle', 'CD.pickle', 'AC.pickle', 'AD.pickle', 'BD.pickle' ]
        # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
        
        model_selection = {}
        
        for f in functionList:
            print()
            for filename in filenames:
                out = f(filename)
                newScore = out[filename]['train_rmse_cv_picking']

                if filename in model_selection:
                    #compare scores and select more accurate model
                    oldScore = model_selection[filename]['train_rmse_cv_picking']
                    if(newScore < oldScore):
                        print("【【【】】】switching models for %s..." % filename)
                        print("【【【】】】newScore: %f < oldScore: %f" % (newScore, oldScore))
                        print("【【【】】】newModel: %s \n" % f)
                        print(100*'_')
                        model_selection[filename] = out[filename]
                else:
                    #no score to compare
                    print("【【】】adding new model for %s \n" % filename)
                    print(100*'_')
                    model_selection[filename] = out[filename]
    return model_selection

In [4]:
t_gb = wrapper([ GradientBoostingCVModel ])


Dataset size read: train 127 and test 194 

# Tuning hyper-parameters 

Starting grdsurch.fit(X_train, y_train)

Best parameters set found on development set:

{'learning_rate': 0.001, 'loss': 'ls', 'n_estimators': 2000}
GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
             learning_rate=0.001, loss='ls', max_depth=None,
             max_features=None, max_leaf_nodes=None,
             min_impurity_split=1e-07, min_samples_leaf=1,
             min_samples_split=2, min_weight_fraction_leaf=0.0,
             n_estimators=2000, presort='auto', random_state=None,
             subsample=1.0, verbose=0, warm_start=False)

Full Test Set: 194


array([  692.62,  2828.23,  1031.47,  1799.43,  1076.1 ,  1332.56,
        1366.43,  2543.24,   510.55,   503.73,  1623.84,  1082.16,
         198.88,   644.52,   215.55,  1001.19,  2127.71,   197.88,
        2683.3 ,  2087.18,   322.27,   323.21,  2681.79,  1688.66,
        2230.04,   750.28,  3621.04,  1462.69,   801.4 ,  2442.42,
         998.83,  2258.66,  3059.32,  2089.36,  1873.73,  2125.54,
         996.42,  2457.56,  1881.93,   297.21,  3143.72,   643.53,
        1324.9 ,  1862.39,  3200.82,   298.03,  2433.27,  1080.  ,
         462.77,   460.34,   460.82,  2684.27,  1870.14,  1458.18,
        2270.37,  1273.42,  2659.86,   504.92,  2265.29,  2106.02,
         298.64,  2436.08,   747.33,   689.4 ,  2833.87,  1139.61,
        1036.77,  1467.65,   640.49,  1358.2 ,  1476.76,  2470.53,
        1727.59,  2123.49,  1472.6 ,  2129.21,  1467.78,  1357.24,
         216.58,  1627.26,  2836.53,   695.76,   323.32,  2832.66,
        1134.68,   720.7 ,  1801.74,  2119.13,  1466.25,  1637

array([ 1199.30874628,  1276.43011827,  1279.65745325,  1260.09175985,
        1188.60821483,  1084.40403643,  1243.0480731 ,  1238.61551954,
        1245.93661176,  1249.40682594,  1300.84738958,  1036.19587751,
        1027.48229573,  1004.90940829,  1190.9893297 ,  1188.60821483,
        1314.25763918,  1190.9893297 ,  1276.43011827,  1238.61551954,
         977.39203563,  1171.77356686,  1276.43011827,  1049.04048373,
        1340.75050552,  1262.13334816,  1280.5253576 ,  1289.14358562,
        1258.95616   ,  1132.27069857,  1036.19587751,  1295.92711836,
        1276.43011827,  1085.64523722,  1085.64523722,  1274.30064899,
        1227.5624459 ,  1132.27069857,  1276.43011827,   977.39203563,
        1085.64523722,  1158.07556492,  1292.28055452,  1274.30064899,
        1085.64523722,  1168.47963152,  1336.44717815,  1036.19587751,
        1041.46710616,  1245.93661176,  1205.10054351,  1280.5253576 ,
        1276.43011827,  1201.59527509,  1280.5253576 ,  1292.28055452,
      

C: 97


array([  692.62,  2828.23,  1076.1 ,  1366.43,  2543.24,  1082.16,
         644.52,  1001.19,  2683.3 ,  2087.18,   322.27,   323.21,
        2681.79,  1688.66,  3621.04,   998.83,  3059.32,  2089.36,
        1873.73,   996.42,  1881.93,   297.21,  3143.72,   643.53,
        3200.82,   298.03,  1080.  ,  2684.27,  1870.14,  1458.18,
        2270.37,  2659.86,  2265.29,   298.64,   689.4 ,  2833.87,
         640.49,  1358.2 ,  1727.59,  1472.6 ,  1357.24,  2836.53,
         695.76,   323.32,  2832.66,  1466.25,   322.13,  1365.13,
         998.65,  2271.12,  2451.8 ,  1879.75,  1728.17,  2441.62,
        2675.11,  3090.73,   300.32,  1474.68,  1083.5 ,  2844.98,
        2096.62,  2083.07,  2674.81,  1470.8 ,  1724.47,  1000.24,
        1087.87,   976.5 ,  1364.75,   695.31,   297.65,  2771.25,
        3085.44,  1688.15,   643.1 ,   639.5 ,  2392.64,  3326.93,
        2671.47,  2294.56,   321.59,  1857.77,  1722.37,  2084.72,
        1868.49,  2832.93,   299.12,  1359.58,  1869.08,  3055

array([ 1199.30874628,  1276.43011827,  1188.60821483,  1243.0480731 ,
        1238.61551954,  1036.19587751,  1004.90940829,  1188.60821483,
        1276.43011827,  1238.61551954,   977.39203563,  1171.77356686,
        1276.43011827,  1049.04048373,  1280.5253576 ,  1036.19587751,
        1276.43011827,  1085.64523722,  1085.64523722,  1227.5624459 ,
        1276.43011827,   977.39203563,  1085.64523722,  1158.07556492,
        1085.64523722,  1168.47963152,  1036.19587751,  1280.5253576 ,
        1276.43011827,  1201.59527509,  1280.5253576 ,  1238.61551954,
        1238.61551954,  1171.77356686,  1158.07556492,  1238.61551954,
        1199.30874628,  1049.04048373,  1238.61551954,  1239.65323281,
        1239.65323281,  1238.61551954,  1004.90940829,  1168.47963152,
        1238.61551954,  1201.59527509,  1171.77356686,  1243.0480731 ,
        1230.45276145,  1276.43011827,  1276.43011827,  1276.43011827,
        1085.64523722,  1085.64523722,  1276.43011827,  1280.5253576 ,
      

D: 97


array([ 1031.47,  1799.43,  1332.56,   510.55,   503.73,  1623.84,
         198.88,   215.55,  2127.71,   197.88,  2230.04,   750.28,
        1462.69,   801.4 ,  2442.42,  2258.66,  2125.54,  2457.56,
        1324.9 ,  1862.39,  2433.27,   462.77,   460.34,   460.82,
        1273.42,   504.92,  2106.02,  2436.08,   747.33,  1139.61,
        1036.77,  1467.65,  1476.76,  2470.53,  2123.49,  2129.21,
        1467.78,   216.58,  1627.26,  1134.68,   720.7 ,  1801.74,
        2119.13,  1637.05,   218.82,  1628.58,  1333.42,  1459.44,
        1037.79,  1634.05,   746.49,  1808.07,   462.06,  2262.51,
        1037.18,   738.16,   814.27,   198.28,   216.12,   823.05,
        1141.32,   199.09,  2241.22,  1929.21,  2142.12,  1806.17,
         214.64,   504.45,   464.01,  1036.27,  1146.09,  2239.73,
        1333.76,  1792.62,   813.15,   505.67,  2450.37,  1469.66,
        1135.84,   198.71,   216.71,   198.45,  2453.84,  1925.99,
        1802.26,  1944.16,   810.75,  1959.63,  1018.55,   503

array([ 1279.65745325,  1260.09175985,  1084.40403643,  1245.93661176,
        1249.40682594,  1300.84738958,  1027.48229573,  1190.9893297 ,
        1314.25763918,  1190.9893297 ,  1340.75050552,  1262.13334816,
        1289.14358562,  1258.95616   ,  1132.27069857,  1295.92711836,
        1274.30064899,  1132.27069857,  1292.28055452,  1274.30064899,
        1336.44717815,  1041.46710616,  1245.93661176,  1205.10054351,
        1292.28055452,  1249.40682594,  1114.83852321,  1340.75050552,
        1262.13334816,  1276.07232691,  1279.65745325,  1084.40403643,
        1289.14358562,  1336.44717815,  1274.30064899,  1317.31991518,
        1292.28055452,  1235.4794716 ,  1304.47273518,  1279.65745325,
        1258.95616   ,  1260.09175985,  1114.83852321,  1096.83753264,
        1235.4794716 ,  1096.83753264,  1247.52036905,  1289.14358562,
        1071.28106724,  1260.09175985,  1217.96496033,  1096.83753264,
        1205.10054351,  1295.92711836,  1276.07232691,  1258.95616   ,
      

【【】】adding new model for AB.pickle 

____________________________________________________________________________________________________
Dataset size read: train 192 and test 129 

# Tuning hyper-parameters 

Starting grdsurch.fit(X_train, y_train)

Best parameters set found on development set:

{'learning_rate': 0.001, 'loss': 'ls', 'n_estimators': 2000}
GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
             learning_rate=0.001, loss='ls', max_depth=None,
             max_features=None, max_leaf_nodes=None,
             min_impurity_split=1e-07, min_samples_leaf=1,
             min_samples_split=2, min_weight_fraction_leaf=0.0,
             n_estimators=2000, presort='auto', random_state=None,
             subsample=1.0, verbose=0, warm_start=False)

Full Test Set: 129


array([  462.06,    68.75,   142.31,  2436.08,   464.01,   750.28,
        1036.27,   120.44,  2470.53,    45.82,  1135.84,   198.28,
         720.7 ,   198.88,  2262.51,  1324.9 ,    21.6 ,    45.97,
        2142.12,    67.96,  1623.84,    98.42,   204.44,   203.98,
        2230.04,   142.07,  2129.21,   801.4 ,   460.82,  1929.21,
         510.55,  2442.42,   503.73,   198.71,  1792.62,    68.63,
        1469.66,  2457.56,   166.8 ,  2433.27,   504.63,   204.8 ,
         164.88,   504.45,  1799.43,   197.88,   199.09,  1146.09,
        2125.54,  1634.05,  2241.22,  2123.49,    21.63,  1802.26,
         747.33,   216.12,  1801.74,   813.15,  1018.55,    46.36,
        1467.78,  1134.68,   214.64,  1944.16,  1467.65,  2258.66,
        1628.58,  1031.47,  1808.07,    98.47,   120.67,    67.97,
          97.49,   203.5 ,  2450.37,  1036.77,  1925.99,   462.77,
        2127.71,  2478.78,   814.27,   504.92,  1471.89,   801.59,
        1141.32,  1333.42,   505.67,  1333.76,   748.82,   121

array([ 1806.96559082,  2553.18217506,  2336.81083802,  2497.57103312,
        1877.326363  ,  2032.19616455,  2126.1225461 ,  2728.77250373,
        2542.71299866,  2588.07668176,  1882.36745288,  1561.32187638,
        2027.73177684,  1561.32187638,  2435.02371585,  2183.90967943,
        2107.70129876,  2579.82538817,  2352.80641194,  2180.90478115,
        2352.80641194,  2718.59736001,  2772.08086335,  2406.70897517,
        2497.57103312,  2705.06456177,  2343.52678796,  2027.73177684,
        1806.96559082,  2352.80641194,  1871.8404029 ,  2212.87473553,
        1877.326363  ,  1806.96559082,  2352.80641194,  2651.36634888,
        1882.36745288,  2212.87473553,  2705.06456177,  2542.71299866,
        1871.8404029 ,  2872.71654638,  2800.54812276,  1561.32187638,
        2288.99180314,  1806.96559082,  1877.326363  ,  2174.23155253,
        2288.99180314,  2288.99180314,  2435.02371585,  2288.99180314,
        2579.82538817,  2343.52678796,  2032.19616455,  1561.32187638,
      

A: 32


array([  68.75,  142.31,  120.44,   45.82,   21.6 ,   45.97,   67.96,
         98.42,  204.44,  203.98,  142.07,   68.63,  166.8 ,  204.8 ,
        164.88,   21.63,   46.36,   98.47,  120.67,   67.97,   97.49,
        203.5 ,  121.17,   97.83,  141.66,   21.58,  120.19,  164.02,
         45.94,   21.8 ,  141.54,  173.64])

array([ 2553.18217506,  2336.81083802,  2728.77250373,  2588.07668176,
        2107.70129876,  2579.82538817,  2180.90478115,  2718.59736001,
        2772.08086335,  2406.70897517,  2705.06456177,  2651.36634888,
        2705.06456177,  2872.71654638,  2800.54812276,  2579.82538817,
        2483.85528352,  2728.77250373,  2255.03407537,  2659.14882711,
        2630.32134267,  2887.69919029,  2718.59736001,  2255.03407537,
        2802.02326162,  2588.07668176,  2630.32134267,  2802.02326162,
        2107.70129876,  2483.85528352,  2800.54812276,  2336.81083802])

D: 97


array([  462.06,  2436.08,   464.01,   750.28,  1036.27,  2470.53,
        1135.84,   198.28,   720.7 ,   198.88,  2262.51,  1324.9 ,
        2142.12,  1623.84,  2230.04,  2129.21,   801.4 ,   460.82,
        1929.21,   510.55,  2442.42,   503.73,   198.71,  1792.62,
        1469.66,  2457.56,  2433.27,   504.63,   504.45,  1799.43,
         197.88,   199.09,  1146.09,  2125.54,  1634.05,  2241.22,
        2123.49,  1802.26,   747.33,   216.12,  1801.74,   813.15,
        1018.55,  1467.78,  1134.68,   214.64,  1944.16,  1467.65,
        2258.66,  1628.58,  1031.47,  1808.07,  2450.37,  1036.77,
        1925.99,   462.77,  2127.71,  2478.78,   814.27,   504.92,
        1471.89,   801.59,  1141.32,  1333.42,   505.67,  1333.76,
         748.82,  1959.63,   738.16,  1627.26,   215.55,  1139.61,
        1637.05,   460.34,  1037.18,  1135.23,  1332.56,   823.05,
         198.45,   218.82,  1476.76,  2239.73,   216.71,   503.45,
        1862.39,  2106.02,  1273.42,  1037.79,  2119.13,   746

array([ 1806.96559082,  2497.57103312,  1877.326363  ,  2032.19616455,
        2126.1225461 ,  2542.71299866,  1882.36745288,  1561.32187638,
        2027.73177684,  1561.32187638,  2435.02371585,  2183.90967943,
        2352.80641194,  2352.80641194,  2497.57103312,  2343.52678796,
        2027.73177684,  1806.96559082,  2352.80641194,  1871.8404029 ,
        2212.87473553,  1877.326363  ,  1806.96559082,  2352.80641194,
        1882.36745288,  2212.87473553,  2542.71299866,  1871.8404029 ,
        1561.32187638,  2288.99180314,  1806.96559082,  1877.326363  ,
        2174.23155253,  2288.99180314,  2288.99180314,  2435.02371585,
        2288.99180314,  2343.52678796,  2032.19616455,  1561.32187638,
        2288.99180314,  1720.83596921,  1882.36745288,  2183.90967943,
        2183.90967943,  1871.8404029 ,  2343.52678796,  1882.36745288,
        2435.02371585,  2060.56315727,  2183.90967943,  2060.56315727,
        2497.57103312,  2183.90967943,  2343.52678796,  1561.32187638,
      

【【】】adding new model for BC.pickle 

____________________________________________________________________________________________________
Dataset size read: train 194 and test 127 

# Tuning hyper-parameters 

Starting grdsurch.fit(X_train, y_train)

Best parameters set found on development set:

{'learning_rate': 0.001, 'loss': 'ls', 'n_estimators': 2000}
GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
             learning_rate=0.001, loss='ls', max_depth=None,
             max_features=None, max_leaf_nodes=None,
             min_impurity_split=1e-07, min_samples_leaf=1,
             min_samples_split=2, min_weight_fraction_leaf=0.0,
             n_estimators=2000, presort='auto', random_state=None,
             subsample=1.0, verbose=0, warm_start=False)

Full Test Set: 127


array([ 1846.6 ,  1332.03,  3450.94,  2001.65,  1723.63,  1740.7 ,
        3371.75,  3357.03,   164.88,    68.63,  1616.34,  2486.13,
        2024.25,   121.17,  1425.64,  2006.73,  2511.62,  1315.75,
        2587.3 ,   120.67,  3444.3 ,  1861.97,  2544.55,   141.66,
        2877.71,    98.42,  2746.73,   166.8 ,    45.97,  1174.9 ,
        1323.62,    21.63,   164.02,  3348.91,    46.36,  1445.01,
         173.64,  2855.36,    97.49,  2293.62,    68.75,  3192.92,
        2130.06,    98.47,  2179.65,  2940.97,   142.07,  3186.2 ,
        2661.74,    21.6 ,  2110.94,  1632.23,  1621.36,    97.83,
        3152.83,  2657.91,  3167.66,  1932.2 ,  2396.68,  2314.1 ,
        1620.72,  1919.57,  1331.2 ,  2210.97,   141.54,  3353.35,
         203.5 ,    21.8 ,   120.19,  2201.04,  2184.34,  1423.13,
        3055.04,  3028.27,  1578.23,  1393.36,  1447.46,  1721.38,
         204.8 ,  3309.8 ,  2754.95,  2472.15,   120.44,  1338.01,
          45.82,  2308.37,  4234.26,  1329.19,  2762.97,  2376

array([  375.9959005 ,   376.31182035,   376.31182035,   376.31182035,
         382.44301678,   382.44301678,   381.10208653,   381.10208653,
        1982.1047125 ,   848.7266668 ,   381.10208653,   382.44301678,
         382.44301678,  1466.65800357,   381.10208653,   376.31182035,
         381.10208653,   381.10208653,   382.44301678,  1429.46583503,
         382.44301678,   375.9959005 ,   376.31182035,  1691.19112576,
         382.44301678,  1155.37260853,   382.44301678,  1955.41029637,
         623.94780554,   376.31182035,   375.9959005 ,   382.22457841,
        1923.60506297,   376.31182035,   609.76796698,   382.44301678,
        1977.09561884,   382.44301678,  1152.90696272,   382.44301678,
         883.20737343,   381.10208653,   375.9959005 ,  1121.41686453,
         381.10208653,   375.9959005 ,  1699.11256611,   376.31182035,
         375.9959005 ,   377.40101099,   375.9959005 ,   381.10208653,
         376.31182035,  1118.67406167,   382.44301678,   375.9959005 ,
      

A: 32


array([ 164.88,   68.63,  121.17,  120.67,  141.66,   98.42,  166.8 ,
         45.97,   21.63,  164.02,   46.36,  173.64,   97.49,   68.75,
         98.47,  142.07,   21.6 ,   97.83,  141.54,  203.5 ,   21.8 ,
        120.19,  204.8 ,  120.44,   45.82,   45.94,   67.97,   67.96,
        204.44,   21.58,  203.98,  142.31])

array([ 1982.1047125 ,   848.7266668 ,  1466.65800357,  1429.46583503,
        1691.19112576,  1155.37260853,  1955.41029637,   623.94780554,
         382.22457841,  1923.60506297,   609.76796698,  1977.09561884,
        1152.90696272,   883.20737343,  1121.41686453,  1699.11256611,
         377.40101099,  1118.67406167,  1695.73811737,  2257.25178978,
         377.1001466 ,  1391.76055177,  2264.62554901,  1370.72573129,
         623.1233628 ,   623.18966414,   862.25067898,   877.8504409 ,
        2148.72476664,   383.55242475,  2320.61280308,  1655.0952748 ])

B: 95


array([ 1846.6 ,  1332.03,  3450.94,  2001.65,  1723.63,  1740.7 ,
        3371.75,  3357.03,  1616.34,  2486.13,  2024.25,  1425.64,
        2006.73,  2511.62,  1315.75,  2587.3 ,  3444.3 ,  1861.97,
        2544.55,  2877.71,  2746.73,  1174.9 ,  1323.62,  3348.91,
        1445.01,  2855.36,  2293.62,  3192.92,  2130.06,  2179.65,
        2940.97,  3186.2 ,  2661.74,  2110.94,  1632.23,  1621.36,
        3152.83,  2657.91,  3167.66,  1932.2 ,  2396.68,  2314.1 ,
        1620.72,  1919.57,  1331.2 ,  2210.97,  3353.35,  2201.04,
        2184.34,  1423.13,  3055.04,  3028.27,  1578.23,  1393.36,
        1447.46,  1721.38,  3309.8 ,  2754.95,  2472.15,  1338.01,
        2308.37,  4234.26,  1329.19,  2762.97,  2376.19,  1593.28,
        3359.25,  3049.37,  3040.59,  2213.16,  2586.27,  3168.1 ,
        1583.26,  2607.84,  2752.13,  3336.48,  3034.04,  1623.2 ,
        2769.22,  2306.07,  2461.26,  2000.17,  1732.64,  3077.01,
        2397.91,  2474.21,  3153.06,  1914.93,  3186.16,  2896

array([ 375.9959005 ,  376.31182035,  376.31182035,  376.31182035,
        382.44301678,  382.44301678,  381.10208653,  381.10208653,
        381.10208653,  382.44301678,  382.44301678,  381.10208653,
        376.31182035,  381.10208653,  381.10208653,  382.44301678,
        382.44301678,  375.9959005 ,  376.31182035,  382.44301678,
        382.44301678,  376.31182035,  375.9959005 ,  376.31182035,
        382.44301678,  382.44301678,  382.44301678,  381.10208653,
        375.9959005 ,  381.10208653,  375.9959005 ,  376.31182035,
        375.9959005 ,  375.9959005 ,  381.10208653,  376.31182035,
        382.44301678,  375.9959005 ,  375.9959005 ,  381.10208653,
        375.9959005 ,  381.10208653,  376.31182035,  375.9959005 ,
        376.31182035,  381.10208653,  381.10208653,  376.31182035,
        382.44301678,  381.10208653,  375.9959005 ,  375.9959005 ,
        375.9959005 ,  375.9959005 ,  382.44301678,  376.31182035,
        375.9959005 ,  375.9959005 ,  382.44301678,  382.44301

【【】】adding new model for CD.pickle 

____________________________________________________________________________________________________
Dataset size read: train 129 and test 192 

# Tuning hyper-parameters 

Starting grdsurch.fit(X_train, y_train)

Best parameters set found on development set:

{'learning_rate': 0.001, 'loss': 'ls', 'n_estimators': 2000}
GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
             learning_rate=0.001, loss='ls', max_depth=None,
             max_features=None, max_leaf_nodes=None,
             min_impurity_split=1e-07, min_samples_leaf=1,
             min_samples_split=2, min_weight_fraction_leaf=0.0,
             n_estimators=2000, presort='auto', random_state=None,
             subsample=1.0, verbose=0, warm_start=False)

Full Test Set: 192


array([ 1808.07,  3028.27,   504.45,  1632.23,   747.33,  1018.55,
        2587.3 ,  3444.3 ,  2110.94,  2450.37,   504.92,  1459.44,
        2181.44,  1031.47,  1634.05,  2230.04,  1174.9 ,  2855.36,
         198.28,  2657.91,  3153.06,  1929.21,  3357.03,  2123.49,
        1338.01,  1792.62,   801.59,  1139.61,  3040.59,  2308.37,
        3077.01,  2754.95,   216.71,  1801.74,  1393.36,   814.27,
        2457.56,   198.71,   198.45,  3371.75,   214.64,  2746.73,
        3168.1 ,  3055.04,   460.82,   216.12,  1623.2 ,   218.82,
        2474.21,  3186.16,  1469.66,  3309.8 ,  2752.13,  1616.34,
        1806.17,  1037.18,  2000.17,  2877.71,  2896.27,  2397.91,
         748.82,  1862.39,  2762.97,  2661.74,   462.06,  2213.16,
        2396.68,  1134.68,  2201.04,  2544.55,  1959.63,  3450.94,
         503.45,  2436.08,  3353.35,   746.49,  1780.16,  1932.2 ,
        3152.83,  1583.26,  2024.25,  1895.33,  2461.26,  1637.05,
         510.55,  4234.26,  1919.57,   199.09,  2127.71,   503

array([ 766.4918268 ,  191.5770443 ,  304.6303561 ,  191.43002829,
        447.06956839,  596.49661825,  191.38678829,  191.38678829,
        191.5770443 ,  901.56703229,  307.74498766,  596.03049051,
        191.38678829,  588.04304375,  752.49988602,  901.56703229,
        191.40408429,  191.38678829,  292.21795142,  191.5770443 ,
        191.38678829,  765.94647341,  191.43002829,  765.11117475,
        191.38678829,  754.04402783,  447.7280214 ,  584.42892082,
        191.40408429,  191.40408429,  191.43002829,  191.5770443 ,
        295.28606531,  752.49988602,  191.5770443 ,  441.50955665,
        923.85513929,  292.68188102,  295.28606531,  191.43002829,
        295.28606531,  191.38678829,  191.38678829,  191.5770443 ,
        305.20647671,  292.21795142,  191.43002829,  295.38357889,
        191.40408429,  191.5770443 ,  608.14408427,  191.5770443 ,
        191.40408429,  191.43002829,  754.04402783,  584.42892082,
        191.43002829,  191.38678829,  191.43002829,  191.57704

B: 95


array([ 3028.27,  1632.23,  2587.3 ,  3444.3 ,  2110.94,  2181.44,
        1174.9 ,  2855.36,  2657.91,  3153.06,  3357.03,  1338.01,
        3040.59,  2308.37,  3077.01,  2754.95,  1393.36,  3371.75,
        2746.73,  3168.1 ,  3055.04,  1623.2 ,  2474.21,  3186.16,
        3309.8 ,  2752.13,  1616.34,  2000.17,  2877.71,  2896.27,
        2397.91,  2762.97,  2661.74,  2213.16,  2396.68,  2201.04,
        2544.55,  3450.94,  3353.35,  1932.2 ,  3152.83,  1583.26,
        2024.25,  1895.33,  2461.26,  4234.26,  1919.57,  1323.62,
        1621.36,  2314.1 ,  2940.97,  2486.13,  1740.7 ,  2472.15,
        2376.19,  1425.64,  1593.28,  3344.01,  1914.93,  3186.2 ,
        2511.62,  1445.01,  1846.6 ,  1721.38,  3336.48,  1423.13,
        2006.73,  3359.25,  1331.2 ,  1320.38,  1315.75,  2184.34,
        2179.65,  3192.92,  1578.23,  2586.27,  3167.66,  1620.72,
        1332.03,  1723.63,  3034.04,  3348.91,  1861.97,  2306.07,
        2210.97,  1329.19,  2607.84,  2001.65,  1732.64,  2130

array([ 191.5770443 ,  191.43002829,  191.38678829,  191.38678829,
        191.5770443 ,  191.38678829,  191.40408429,  191.38678829,
        191.5770443 ,  191.38678829,  191.43002829,  191.38678829,
        191.40408429,  191.40408429,  191.43002829,  191.5770443 ,
        191.5770443 ,  191.43002829,  191.38678829,  191.38678829,
        191.5770443 ,  191.43002829,  191.40408429,  191.5770443 ,
        191.5770443 ,  191.40408429,  191.43002829,  191.43002829,
        191.38678829,  191.43002829,  191.5770443 ,  191.40408429,
        191.5770443 ,  191.5770443 ,  191.5770443 ,  191.40408429,
        191.40408429,  191.40408429,  191.43002829,  191.43002829,
        191.38678829,  191.5770443 ,  191.38678829,  191.43002829,
        191.40408429,  191.40408429,  191.5770443 ,  191.5770443 ,
        191.40408429,  191.43002829,  191.5770443 ,  191.38678829,
        191.38678829,  191.38678829,  191.5770443 ,  191.43002829,
        191.5770443 ,  191.38678829,  191.38678829,  191.40408

D: 97


array([ 1808.07,   504.45,   747.33,  1018.55,  2450.37,   504.92,
        1459.44,  1031.47,  1634.05,  2230.04,   198.28,  1929.21,
        2123.49,  1792.62,   801.59,  1139.61,   216.71,  1801.74,
         814.27,  2457.56,   198.71,   198.45,   214.64,   460.82,
         216.12,   218.82,  1469.66,  1806.17,  1037.18,   748.82,
        1862.39,   462.06,  1134.68,  1959.63,   503.45,  2436.08,
         746.49,  1780.16,  1637.05,   510.55,   199.09,  2127.71,
         503.73,  1944.16,   462.77,   720.7 ,  1332.56,   823.05,
        1036.77,  1036.27,  1628.58,   504.63,  2241.22,   505.67,
         801.4 ,   198.88,  1141.32,   813.15,  2125.54,  1925.99,
        1471.89,   460.34,  1802.26,  1037.79,  2239.73,   738.16,
        1462.69,  2478.78,  1333.76,  1273.42,  2453.84,  2119.13,
        1799.43,   464.01,  1627.26,   810.75,  1333.42,   215.55,
        2129.21,   750.28,  1135.23,   197.88,  2106.02,  2433.27,
        1324.9 ,  2258.66,  1467.78,  1467.65,  2442.42,  2262

array([ 766.4918268 ,  304.6303561 ,  447.06956839,  596.49661825,
        901.56703229,  307.74498766,  596.03049051,  588.04304375,
        752.49988602,  901.56703229,  292.21795142,  765.94647341,
        765.11117475,  754.04402783,  447.7280214 ,  584.42892082,
        295.28606531,  752.49988602,  441.50955665,  923.85513929,
        292.68188102,  295.28606531,  295.28606531,  305.20647671,
        292.21795142,  295.38357889,  608.14408427,  754.04402783,
        584.42892082,  447.7280214 ,  765.11117475,  305.20647671,
        588.04304375,  782.46884564,  305.20647671,  901.56703229,
        441.50955665,  742.0217052 ,  766.4918268 ,  307.69846999,
        295.38357889,  765.94647341,  307.74498766,  753.42439084,
        304.6303561 ,  448.12765136,  608.14408427,  441.50955665,
        588.04304375,  595.12386968,  766.4918268 ,  307.69846999,
        905.02884654,  304.6303561 ,  448.12765136,  292.21795142,
        595.12386968,  447.7280214 ,  765.11117475,  753.42439

【【】】adding new model for AC.pickle 

____________________________________________________________________________________________________
Dataset size read: train 129 and test 192 

# Tuning hyper-parameters 

Starting grdsurch.fit(X_train, y_train)

Best parameters set found on development set:

{'learning_rate': 0.001, 'loss': 'ls', 'n_estimators': 2000}
GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
             learning_rate=0.001, loss='ls', max_depth=None,
             max_features=None, max_leaf_nodes=None,
             min_impurity_split=1e-07, min_samples_leaf=1,
             min_samples_split=2, min_weight_fraction_leaf=0.0,
             n_estimators=2000, presort='auto', random_state=None,
             subsample=1.0, verbose=0, warm_start=False)

Full Test Set: 192


array([ 2181.44,   689.4 ,  2896.76,  2213.16,   695.31,  1445.01,
         695.76,  1366.43,  3344.01,  3444.3 ,  2184.34,  1732.64,
        2451.8 ,  2681.79,  1329.19,  1881.93,   297.21,  1869.08,
        2828.23,  2087.18,  1076.1 ,  2006.73,  2511.62,  2486.13,
         298.03,  2832.93,   998.83,  2096.62,  3621.04,  2308.37,
        3167.66,  3049.37,  3152.83,   643.1 ,   643.53,  2271.12,
        1620.72,  2376.19,  2024.25,  3192.92,  2587.3 ,  2001.65,
        1472.6 ,  1593.28,  2877.71,  2472.15,  1578.23,  2314.1 ,
        2089.36,  2607.84,  1000.24,  1080.  ,   322.27,  2293.62,
         321.59,  1174.9 ,  1895.33,  1082.16,  1466.25,  2474.21,
        2671.47,  3055.04,  1688.15,  1870.14,  3348.91,  1621.36,
        3055.04,  1323.62,  3371.75,   322.13,  2110.94,  2762.97,
        3200.82,  1861.97,  1365.13,  2543.24,  1722.37,  2000.17,
        1688.66,  1616.34,  2396.68,  1919.57,   692.62,  2294.56,
        1740.7 ,  2450.48,  3186.2 ,  2674.81,  3359.25,  1425

array([  243.97965219,   511.87945913,   243.24062036,   240.45088445,
         493.71809175,   243.97965219,   508.57535845,   957.09510395,
         243.97965219,   243.97965219,   243.97965219,   243.97965219,
        1266.85024542,  1266.85024542,   240.55915439,  1266.85024542,
         232.3082841 ,  1301.535049  ,  1266.85024542,  1211.38105032,
         791.03577365,   240.55915439,   243.24062036,   243.97965219,
         234.74259101,  1211.38105032,   810.41288775,  1301.535049  ,
        1272.4185234 ,   240.55915439,   240.45088445,   243.24062036,
         243.97965219,   511.87945913,   511.87945913,  1266.85024542,
         240.55915439,   240.45088445,   243.97965219,   243.24062036,
         243.97965219,   240.55915439,   958.94235109,   240.45088445,
         243.97965219,   243.97965219,   240.45088445,   243.24062036,
        1301.535049  ,   243.24062036,   780.445856  ,   810.41288775,
         232.3082841 ,   243.97965219,   234.74259101,   240.55915439,
      

B: 95


array([ 2181.44,  2896.76,  2213.16,  1445.01,  3344.01,  3444.3 ,
        2184.34,  1732.64,  1329.19,  2006.73,  2511.62,  2486.13,
        2308.37,  3167.66,  3049.37,  3152.83,  1620.72,  2376.19,
        2024.25,  3192.92,  2587.3 ,  2001.65,  1593.28,  2877.71,
        2472.15,  1578.23,  2314.1 ,  2607.84,  2293.62,  1174.9 ,
        1895.33,  2474.21,  3348.91,  1621.36,  3055.04,  1323.62,
        3371.75,  2110.94,  2762.97,  1861.97,  2000.17,  1616.34,
        2396.68,  1919.57,  1740.7 ,  3186.2 ,  3359.25,  1425.64,
        4234.26,  1623.2 ,  2746.73,  1320.38,  3309.8 ,  3357.03,
        3186.16,  3034.04,  2752.13,  2397.91,  1721.38,  3450.94,
        3040.59,  1331.2 ,  1723.63,  2586.27,  2201.04,  2896.27,
        1632.23,  1846.6 ,  3077.01,  2306.07,  1914.93,  2210.97,
        2179.65,  1423.13,  1393.36,  3336.48,  3153.06,  2657.91,
        2940.97,  1338.01,  3168.1 ,  2769.22,  1447.46,  2544.55,
        2661.74,  2855.36,  1583.26,  1932.2 ,  2130.06,  3353

array([ 243.97965219,  243.24062036,  240.45088445,  243.97965219,
        243.97965219,  243.97965219,  243.97965219,  243.97965219,
        240.55915439,  240.55915439,  243.24062036,  243.97965219,
        240.55915439,  240.45088445,  243.24062036,  243.97965219,
        240.55915439,  240.45088445,  243.97965219,  243.24062036,
        243.97965219,  240.55915439,  240.45088445,  243.97965219,
        243.97965219,  240.45088445,  243.24062036,  243.24062036,
        243.97965219,  240.55915439,  243.24062036,  240.55915439,
        240.55915439,  240.55915439,  240.45088445,  240.45088445,
        243.24062036,  240.45088445,  240.55915439,  240.45088445,
        243.24062036,  243.24062036,  240.45088445,  240.45088445,
        243.97965219,  240.55915439,  243.24062036,  243.24062036,
        240.55915439,  243.24062036,  243.97965219,  240.45088445,
        240.45088445,  243.24062036,  240.45088445,  240.55915439,
        240.55915439,  240.45088445,  240.55915439,  240.55915

C: 97


array([  689.4 ,   695.31,   695.76,  1366.43,  2451.8 ,  2681.79,
        1881.93,   297.21,  1869.08,  2828.23,  2087.18,  1076.1 ,
         298.03,  2832.93,   998.83,  2096.62,  3621.04,   643.1 ,
         643.53,  2271.12,  1472.6 ,  2089.36,  1000.24,  1080.  ,
         322.27,   321.59,  1082.16,  1466.25,  2671.47,  3055.04,
        1688.15,  1870.14,   322.13,  3200.82,  1365.13,  2543.24,
        1722.37,  1688.66,   692.62,  2294.56,  2450.48,  2674.81,
        3326.93,  2270.37,  1724.47,  2844.98,   298.64,  1474.68,
        1358.2 ,  1087.87,  1357.24,  3143.72,  2833.87,  1458.18,
        2392.64,   691.73,  1879.75,  2675.11,  1728.17,  2265.29,
        3059.32,   300.32,   299.12,  2836.53,   644.52,  2084.72,
        1073.56,  1470.8 ,  1727.59,   323.21,   640.49,   323.32,
        3090.73,  1001.19,  1868.49,  1857.77,   693.29,   976.5 ,
        2771.25,  1873.73,   996.42,  2684.27,  2659.86,   320.75,
        2683.3 ,   998.65,  1083.5 ,   697.69,  1364.75,  2083

array([  511.87945913,   493.71809175,   508.57535845,   957.09510395,
        1266.85024542,  1266.85024542,  1266.85024542,   232.3082841 ,
        1301.535049  ,  1266.85024542,  1211.38105032,   791.03577365,
         234.74259101,  1211.38105032,   810.41288775,  1301.535049  ,
        1272.4185234 ,   511.87945913,   511.87945913,  1266.85024542,
         958.94235109,  1301.535049  ,   780.445856  ,   810.41288775,
         232.3082841 ,   234.74259101,   810.41288775,   961.01311095,
        1301.535049  ,  1266.85024542,  1272.4185234 ,  1266.85024542,
         235.40881396,  1301.535049  ,   957.09510395,  1211.38105032,
        1272.4185234 ,   937.43899543,   500.48821319,  1301.535049  ,
        1272.4185234 ,  1301.535049  ,  1301.535049  ,  1272.4185234 ,
        1211.38105032,  1272.4185234 ,   235.40881396,   958.94235109,
         937.43899543,   780.445856  ,   958.94235109,  1301.535049  ,
        1211.38105032,   961.01311095,  1211.38105032,   508.57535845,
      

【【】】adding new model for AD.pickle 

____________________________________________________________________________________________________
Dataset size read: train 192 and test 129 

# Tuning hyper-parameters 

Starting grdsurch.fit(X_train, y_train)

Best parameters set found on development set:

{'learning_rate': 0.001, 'loss': 'ls', 'n_estimators': 2000}
GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
             learning_rate=0.001, loss='ls', max_depth=None,
             max_features=None, max_leaf_nodes=None,
             min_impurity_split=1e-07, min_samples_leaf=1,
             min_samples_split=2, min_weight_fraction_leaf=0.0,
             n_estimators=2000, presort='auto', random_state=None,
             subsample=1.0, verbose=0, warm_start=False)

Full Test Set: 129


array([ 2671.47,   120.44,   643.53,    21.63,  2451.8 ,  2681.79,
        2675.11,  2683.3 ,   998.83,    68.63,   643.1 ,  1868.49,
        1472.6 ,    68.75,   297.21,  1458.18,   142.31,   976.5 ,
         639.5 ,  1470.8 ,   323.32,   691.73,  1076.1 ,  1857.77,
        2441.62,  2271.12,    21.8 ,    98.42,   141.54,   996.42,
        3085.44,  1364.75,    67.97,   693.29,  2087.18,    21.58,
         298.64,   120.19,  1870.14,  2836.53,   173.64,  1087.87,
         644.52,  2832.93,  2392.64,  2265.29,  1366.43,    97.49,
        1881.93,   164.88,   322.13,   697.69,  1359.58,  1688.15,
        2833.87,  1466.25,  1357.24,  1869.08,  2828.23,    67.96,
        1080.  ,   640.49,  2844.98,  3326.93,  2543.24,    21.6 ,
        1365.13,  2270.37,   204.8 ,  1474.68,  1083.5 ,  1722.37,
        2083.07,  2832.66,  3200.82,   203.5 ,  2684.27,   695.76,
          45.94,  1688.66,  1727.59,  2674.81,  2096.62,   164.02,
        1001.19,   320.75,  2089.36,    46.36,   321.59,   322

array([ 2436.63903159,  2003.23541328,  1713.04595986,  1341.1313488 ,
        2620.51272393,  2620.51272393,  2620.51272393,  2620.51272393,
        1873.6198726 ,  1653.60207256,  1713.04595986,  2630.64896143,
        2272.63824059,  1636.27300923,  1211.41238807,  2229.43555877,
        1988.59877064,  2123.45914386,  1736.15381495,  2274.23245628,
        1440.877939  ,  1528.38763441,  2030.92308289,  2506.00564296,
        2436.63903159,  2620.51272393,  1296.73998961,  1857.24867566,
        2221.32768248,  2123.45914386,  2630.64896143,  2229.43555877,
        1666.37201891,  1748.80416954,  2506.00564296,  1345.58195329,
        1445.66675404,  1972.66112215,  2620.51272393,  2506.00564296,
        2201.53252661,  2067.13041991,  1528.38763441,  2506.00564296,
        2506.00564296,  2506.00564296,  2274.23245628,  1814.31382415,
        2620.51272393,  2408.45250578,  1445.66675404,  1736.15381495,
        2019.19327358,  2630.64896143,  2506.00564296,  2229.43555877,
      

A: 32


array([ 120.44,   21.63,   68.63,   68.75,  142.31,   21.8 ,   98.42,
        141.54,   67.97,   21.58,  120.19,  173.64,   97.49,  164.88,
         67.96,   21.6 ,  204.8 ,  203.5 ,   45.94,  164.02,   46.36,
        121.17,  120.67,  204.44,  142.07,  141.66,   45.82,   45.97,
         97.83,  203.98,  166.8 ,   98.47])

array([ 2003.23541328,  1341.1313488 ,  1653.60207256,  1636.27300923,
        1988.59877064,  1296.73998961,  1857.24867566,  2221.32768248,
        1666.37201891,  1345.58195329,  1972.66112215,  2201.53252661,
        1814.31382415,  2408.45250578,  1469.21196735,  1133.77825025,
        2599.56942112,  2589.45999685,  1298.51885036,  2373.73646907,
        1452.77603992,  2063.4614153 ,  1834.54817027,  2475.40924174,
        2182.73360713,  2222.39765601,  1506.21366859,  1503.20998949,
        1628.01346578,  2430.35371496,  2350.65361017,  1837.81063785])

C: 97


array([ 2671.47,   643.53,  2451.8 ,  2681.79,  2675.11,  2683.3 ,
         998.83,   643.1 ,  1868.49,  1472.6 ,   297.21,  1458.18,
         976.5 ,   639.5 ,  1470.8 ,   323.32,   691.73,  1076.1 ,
        1857.77,  2441.62,  2271.12,   996.42,  3085.44,  1364.75,
         693.29,  2087.18,   298.64,  1870.14,  2836.53,  1087.87,
         644.52,  2832.93,  2392.64,  2265.29,  1366.43,  1881.93,
         322.13,   697.69,  1359.58,  1688.15,  2833.87,  1466.25,
        1357.24,  1869.08,  2828.23,  1080.  ,   640.49,  2844.98,
        3326.93,  2543.24,  1365.13,  2270.37,  1474.68,  1083.5 ,
        1722.37,  2083.07,  2832.66,  3200.82,  2684.27,   695.76,
        1688.66,  1727.59,  2674.81,  2096.62,  1001.19,   320.75,
        2089.36,   321.59,   322.27,  2659.86,   298.03,   689.4 ,
         998.65,   299.12,  2274.86,  1073.56,  3055.04,   695.31,
        3090.73,  1873.73,   300.32,   323.21,  2771.25,   297.65,
        1358.2 ,  1724.47,  3059.32,  2450.48,  1728.17,  1000

array([ 2436.63903159,  1713.04595986,  2620.51272393,  2620.51272393,
        2620.51272393,  2620.51272393,  1873.6198726 ,  1713.04595986,
        2630.64896143,  2272.63824059,  1211.41238807,  2229.43555877,
        2123.45914386,  1736.15381495,  2274.23245628,  1440.877939  ,
        1528.38763441,  2030.92308289,  2506.00564296,  2436.63903159,
        2620.51272393,  2123.45914386,  2630.64896143,  2229.43555877,
        1748.80416954,  2506.00564296,  1445.66675404,  2620.51272393,
        2506.00564296,  2067.13041991,  1528.38763441,  2506.00564296,
        2506.00564296,  2506.00564296,  2274.23245628,  2620.51272393,
        1445.66675404,  1736.15381495,  2019.19327358,  2630.64896143,
        2506.00564296,  2229.43555877,  2272.63824059,  2436.63903159,
        2620.51272393,  1873.6198726 ,  1748.80416954,  2630.64896143,
        2436.63903159,  2506.00564296,  2274.23245628,  2630.64896143,
        2272.63824059,  2123.45914386,  2630.64896143,  2630.64896143,
      

【【】】adding new model for BD.pickle 

____________________________________________________________________________________________________


In [5]:
t_print = t_gb

for key in t_print.keys():
    print(80*'_')
    print(key)    

    print('Model: %s' % (str(t_print[key]['model'])[:20]))
    print('Train RMSE: %f \n' % (t_print[key]['train_rmse_cv_picking']))

    #print('Test RMSE   : %f' % (t_print[key]['test_rmse_reporting']))
    #print('Overall Mean: %f \n' % (t_print[key]['test_mean_y_comparing']))

    if(not t_print[key]['test_rmse_reportingA']==None):
        print('A...TestA RMSE   : %f' % float(t_print[key]['test_rmse_reportingA'] or -1))
        print('A...<<y_test_A Mean>>: %f \n' % float(t_print[key]['test_mean_y_comparingA'] or -1))

    if(not t_print[key]['test_rmse_reportingB']==None):
        print('B...TestB RMSE   : %f' % float(t_print[key]['test_rmse_reportingB'] or -1))
        print('B...<<y_test_B Mean>>: %f \n' % float(t_print[key]['test_mean_y_comparingB'] or -1))

    if(not t_print[key]['test_rmse_reportingC']==None):
        print('C...TestC RMSE   : %f' % float(t_print[key]['test_rmse_reportingC'] or -1))
        print('C...<<y_test_C Mean>>: %f \n' % float(t_print[key]['test_mean_y_comparingC'] or -1))

    if(not t_print[key]['test_rmse_reportingD']==None):
        print('D...TestD RMSE   : %f' % float(t_print[key]['test_rmse_reportingD'] or -1))
        print('D...<<y_test_D Mean>>: %f' % float(t_print[key]['test_mean_y_comparingD'] or -1))

    print(80*'_')

________________________________________________________________________________
AB.pickle
Model: GradientBoostingRegr
Train RMSE: 360.512614 

C...TestC RMSE   : 1002.662870
C...<<y_test_C Mean>>: 1663.210000 

D...TestD RMSE   : 694.000824
D...<<y_test_D Mean>>: 1274.728557
________________________________________________________________________________
________________________________________________________________________________
BC.pickle
Model: GradientBoostingRegr
Train RMSE: 315.472625 

A...TestA RMSE   : 2476.319894
A...<<y_test_A Mean>>: 108.510312 

D...TestD RMSE   : 961.293829
D...<<y_test_D Mean>>: 1274.728557
________________________________________________________________________________
________________________________________________________________________________
CD.pickle
Model: GradientBoostingRegr
Train RMSE: 172.924403 

A...TestA RMSE   : 1305.208441
A...<<y_test_A Mean>>: 108.510312 

B...TestB RMSE   : 2108.671965
B...<<y_test_B Mean>>: 2371.578632 

______

In [ ]:
# write the model
import pickle

#||||||||||||||||||| 
t_ = t_gb
prefix = '4C2_' + 'gb'
#||||||||||||||||||| 

for k in t_.keys():
    mo   = t_[k]['model']
    fname = prefix + '_tuned_' + str(k[:2]) + '.pickle'
    
    print()
    print(k, str(mo)[:30])
    
    print(fname)
    # write the model to a file
    with open(fname, 'wb') as handle:
        pickle.dump(mo, handle)


AB.pickle GradientBoostingRegressor(alph
4C2_gb_tuned_AB.pickle

BC.pickle GradientBoostingRegressor(alph
4C2_gb_tuned_BC.pickle

CD.pickle GradientBoostingRegressor(alph
4C2_gb_tuned_CD.pickle

AC.pickle GradientBoostingRegressor(alph
4C2_gb_tuned_AC.pickle

AD.pickle GradientBoostingRegressor(alph
4C2_gb_tuned_AD.pickle

BD.pickle GradientBoostingRegressor(alph
4C2_gb_tuned_BD.pickle


# Random Forest

In [ ]:
t_rf = wrapper([ RandomForestCVModel ])


Dataset size read: train 127 and test 194 

# Tuning hyper-parameters 

Starting grdsurch.fit(X_train, y_train)


In [ ]:
t_print = t_rf

for key in t_print.keys():
    print(80*'_')
    print(key)    

    print('Model: %s' % (str(t_print[key]['model'])[:20]))
    print('Train RMSE: %f \n' % (t_print[key]['train_rmse_cv_picking']))

    #print('Test RMSE   : %f' % (t_print[key]['test_rmse_reporting']))
    #print('Overall Mean: %f \n' % (t_print[key]['test_mean_y_comparing']))

    if(not t_print[key]['test_rmse_reportingA']==None):
        print('A...TestA RMSE   : %f' % float(t_print[key]['test_rmse_reportingA'] or -1))
        print('A...<<y_test_A Mean>>: %f \n' % float(t_print[key]['test_mean_y_comparingA'] or -1))

    if(not t_print[key]['test_rmse_reportingB']==None):
        print('B...TestB RMSE   : %f' % float(t_print[key]['test_rmse_reportingB'] or -1))
        print('B...<<y_test_B Mean>>: %f \n' % float(t_print[key]['test_mean_y_comparingB'] or -1))

    if(not t_print[key]['test_rmse_reportingC']==None):
        print('C...TestC RMSE   : %f' % float(t_print[key]['test_rmse_reportingC'] or -1))
        print('C...<<y_test_C Mean>>: %f \n' % float(t_print[key]['test_mean_y_comparingC'] or -1))

    if(not t_print[key]['test_rmse_reportingD']==None):
        print('D...TestD RMSE   : %f' % float(t_print[key]['test_rmse_reportingD'] or -1))
        print('D...<<y_test_D Mean>>: %f' % float(t_print[key]['test_mean_y_comparingD'] or -1))

    print(80*'_')

In [ ]:
# write the model
import pickle

#||||||||||||||||||| 
t_ = t_rf
prefix = '4C2_' + 'rforest'
#||||||||||||||||||| 

for k in t_.keys():
    mo   = t_[k]['model']
    fname = prefix + '_tuned_' + str(k[:2]) + '.pickle'
    
    print()
    print(k, str(mo)[:30])
    
    print(fname)
    # write the model to a file
    with open(fname, 'wb') as handle:
        pickle.dump(mo, handle)

# Which features were given most weights by each model ?

In [ ]:
names = ['ppn', 'sizeGB', 'ft1', 'ft2', 'ft3', 'ft4', 'ft5', 'ft6', 'ft7', 'ft8',
        'ft9', 'ft10', 'ft11', 'ft12', 'ft13', 'ft14', 'ft15', 'ft16', 'ft17',
        'ft18', 'ft24', 'ft25', 'ft19', 'ft39', 'ft20', 'ft33', 'ft21', 'ft35',
        'ft22', 'ft23', 'ft34', 'ft36', 'ft37', 'ft38', 'ft40', 'ft41', 'ft42',
        'ft43', 'ft44', 'ft45', 'ft46', 'ft48', 'ft47', 'ft49', 'ft51', 'ft50',
        'ft52', 'ft53', 'ft54', 'ft55', 'ft26', 'ft27', 'ft28', 'ft29', 'ft30',
        'ft31', 'ft32']

In [ ]:
%matplotlib inline

In [ ]:
t_ = t_gb

for k in t_.keys():
    mo   = t_[k]['model']
    feature_importance = mo.feature_importances_
    feature_names = names 
    
    # make importances relative to max importance
    feature_importance = 100.0 * (feature_importance / feature_importance.max())
    sorted_idx = np.argsort(feature_importance)
    pos = np.arange(sorted_idx.shape[0]) + .5
    plt.subplot(1, 2, 2)
    plt.barh(pos, feature_importance[sorted_idx], align='center')
    plt.yticks(pos, feature_names[sorted_idx])
    plt.xlabel('Relative Importance')
    plt.title('Variable Importance')
    plt.show()