In [ ]:
# import all the filenames
from allfunctions import *

In [ ]:
%load_ext autoreload
%autoreload 2

1  def LassoCVModel(filename):

3  def RidgeCVModel(filename):

4  def ElasticNetCVModel(filename):

In [ ]:
def wrapper(functionList):
    if __name__ == '__main__':
        global model_selection
        global filenames
        
        filenames = ['AB.pickle', 'BC.pickle', 'CD.pickle', 'AC.pickle', 'AD.pickle', 'BD.pickle' ]
        
        model_selection = {}
        
        for f in functionList:
            print()
            for filename in filenames:
                out = f(filename)
                newScore = out[filename]['train_rmse_cv_picking']

                if filename in model_selection:
                    #compare scores and select more accurate model
                    oldScore = model_selection[filename]['train_rmse_cv_picking']
                    if(newScore < oldScore):
                        print("【【【】】】switching models for %s..." % filename)
                        print("【【【】】】newScore: %f < oldScore: %f" % (newScore, oldScore))
                        print("【【【】】】newModel: %s \n" % f)
                        print(100*'_')
                        model_selection[filename] = out[filename]
                else:
                    #no score to compare
                    print("【【】】adding new model for %s \n" % filename)
                    print(100*'_')
                    model_selection[filename] = out[filename]
    return model_selection

<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:><:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>
<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:><:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>
<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:><:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>
<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:><:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:


In [ ]:
t_lasso = wrapper([LassoCVModel])

In [ ]:
t_print = t_lasso

for key in t_print.keys():
    print(80*'_')
    print(key)
    
    print('Model: %s' % (str(t_print[key]['model'])[:20]))
    print('Train RMSE: %f \n' % (t_print[key]['train_rmse_cv_picking']))

    #print('Test RMSE   : %f' % (t_print[key]['test_rmse_reporting']))
    #print('Overall Mean: %f \n' % (t_print[key]['test_mean_y_comparing']))

    if(not t_print[key]['test_rmse_reportingA']==None):
        print('A...TestA RMSE   : %f' % float(t_print[key]['test_rmse_reportingA'] or -1))
        print('A...<<y_test_A Mean>>: %f \n' % float(t_print[key]['test_mean_y_comparingA'] or -1))

    if(not t_print[key]['test_rmse_reportingB']==None):
        print('B...TestB RMSE   : %f' % float(t_print[key]['test_rmse_reportingB'] or -1))
        print('B...<<y_test_B Mean>>: %f \n' % float(t_print[key]['test_mean_y_comparingB'] or -1))

    if(not t_print[key]['test_rmse_reportingC']==None):
        print('C...TestC RMSE   : %f' % float(t_print[key]['test_rmse_reportingC'] or -1))
        print('C...<<y_test_C Mean>>: %f \n' % float(t_print[key]['test_mean_y_comparingC'] or -1))

    if(not t_print[key]['test_rmse_reportingD']==None):
        print('D...TestD RMSE   : %f' % float(t_print[key]['test_rmse_reportingD'] or -1))
        print('D...<<y_test_D Mean>>: %f' % float(t_print[key]['test_mean_y_comparingD'] or -1))

    print(80*'_')

<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:><:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>
<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:><:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>
<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:><:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>
<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:><:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:


In [ ]:
t_ridge = wrapper([RidgeCVModel])

In [ ]:
t_print = t_ridge


for key in t_print.keys():
    print(80*'_')
    print(key)
    
    print('Model: %s' % (str(t_print[key]['model'])[:20]))
    print('Train RMSE: %f \n' % (t_print[key]['train_rmse_cv_picking']))

    #print('Test RMSE   : %f' % (t_print[key]['test_rmse_reporting']))
    #print('Overall Mean: %f \n' % (t_print[key]['test_mean_y_comparing']))

    if(not t_print[key]['test_rmse_reportingA']==None):
        print('A...TestA RMSE   : %f' % float(t_print[key]['test_rmse_reportingA'] or -1))
        print('A...<<y_test_A Mean>>: %f \n' % float(t_print[key]['test_mean_y_comparingA'] or -1))

    if(not t_print[key]['test_rmse_reportingB']==None):
        print('B...TestB RMSE   : %f' % float(t_print[key]['test_rmse_reportingB'] or -1))
        print('B...<<y_test_B Mean>>: %f \n' % float(t_print[key]['test_mean_y_comparingB'] or -1))

    if(not t_print[key]['test_rmse_reportingC']==None):
        print('C...TestC RMSE   : %f' % float(t_print[key]['test_rmse_reportingC'] or -1))
        print('C...<<y_test_C Mean>>: %f \n' % float(t_print[key]['test_mean_y_comparingC'] or -1))

    if(not t_print[key]['test_rmse_reportingD']==None):
        print('D...TestD RMSE   : %f' % float(t_print[key]['test_rmse_reportingD'] or -1))
        print('D...<<y_test_D Mean>>: %f' % float(t_print[key]['test_mean_y_comparingD'] or -1))

    print(80*'_')

<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:><:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>
<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:><:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>
<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:><:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>
<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:><:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:


In [ ]:
t_elasticNet = wrapper([ElasticNetCVModel])



{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}

Dataset size read: train 127 and test 194 

# Tuning hyper-parameters 
[{'alpha': array([  1.00000000e-25,   1.91448198e-24,   3.66524124e-23,
         7.01703829e-22,   1.34339933e-20,   2.57191381e-19,
         4.92388263e-18,   9.42668455e-17,   1.80472177e-15,
         3.45510729e-14,   6.61474064e-13,   1.26638017e-11,
         2.42446202e-10,   4.64158883e-09,   8.88623816e-08,
         1.70125428e-06,   3.25702066e-05,   6.23550734e-04,
         1.19377664e-02,   2.28546386e-01,   4.37547938e+00,
         8.37677640e+01,   1.60371874e+03,   3.07029063e+04,
         5.87801607e+05,   1.12533558e+07,   2.15443469e+08,
         4.12462638e+09,   7.89652287e+10,   1.51177507e+12,
         2.89426612e+13,   5.54102033e+14,   1.06081836e+16,
         2.03091762e+17,   3.88815518e+18,   7.44380301e+19,
         1.42510267e+21,   2.72833338e+22,   5.22334507e+23,
         1.00000000e+25]), 'l1_r

/data/home/a1singh/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:484: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
/data/home/a1singh/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:484: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
/data/home/a1singh/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:484: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
/data/home/a1singh/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:484: ConvergenceWarni


Best parameters set found on development set:

{'alpha': 1603.7187437513408, 'l1_ratio': 0.9}
ElasticNet(alpha=1603.7187437513408, copy_X=True, fit_intercept=True,
      l1_ratio=0.9, max_iter=10000000.0, normalize=False, positive=False,
      precompute=False, random_state=None, selection='cyclic', tol=1e-20,
      warm_start=False)

Full Test Set: 194


array([ 2230.04,  1862.39,  3085.44,   218.82,   299.12,   643.1 ,
         322.13,   691.73,  1076.1 ,  2087.18,  1036.27,  1870.14,
        2392.64,   692.62,  1332.56,   297.65,  1470.8 ,  2119.13,
         695.76,   460.34,  2241.22,   510.55,  1135.23,   640.49,
        2543.24,  2127.71,   216.12,   322.27,  1134.68,   504.45,
         720.7 ,  1727.59,  1792.62,  1944.16,  1881.93,  1083.5 ,
         976.5 ,  1333.42,   199.09,   810.75,  1637.05,   503.45,
        1273.42,  1471.89,  1333.76,  2274.86,  3621.04,   801.59,
         801.4 ,   998.65,  1357.24,  1366.43,  1031.47,   746.49,
        2659.86,  2125.54,  1724.47,  2450.48,  1359.58,  1929.21,
        3059.32,  1869.08,   639.5 ,  2451.8 ,  1802.26,  2442.42,
        2833.87,  1873.73,  2270.37,  2675.11,   503.73,  1018.55,
        1135.84,  2271.12,  1467.78,   462.06,   216.58,   321.59,
         738.16,  2470.53,  2106.02,  2265.29,  1466.25,   823.05,
        1728.17,  1001.19,  2096.62,  2828.23,   300.32,   813

array([ 1801.35669291,  1801.35669291,  1801.35669291,  1801.35669291,
        1801.35669291,  1801.35669291,  1801.35669291,  1801.35669291,
        1801.35669291,  1801.35669291,  1801.35669291,  1801.35669291,
        1801.35669291,  1801.35669291,  1801.35669291,  1801.35669291,
        1801.35669291,  1801.35669291,  1801.35669291,  1801.35669291,
        1801.35669291,  1801.35669291,  1801.35669291,  1801.35669291,
        1801.35669291,  1801.35669291,  1801.35669291,  1801.35669291,
        1801.35669291,  1801.35669291,  1801.35669291,  1801.35669291,
        1801.35669291,  1801.35669291,  1801.35669291,  1801.35669291,
        1801.35669291,  1801.35669291,  1801.35669291,  1801.35669291,
        1801.35669291,  1801.35669291,  1801.35669291,  1801.35669291,
        1801.35669291,  1801.35669291,  1801.35669291,  1801.35669291,
        1801.35669291,  1801.35669291,  1801.35669291,  1801.35669291,
        1801.35669291,  1801.35669291,  1801.35669291,  1801.35669291,
      

C: 97

{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}



array([ 3085.44,   299.12,   643.1 ,   322.13,   691.73,  1076.1 ,
        2087.18,  1870.14,  2392.64,   692.62,   297.65,  1470.8 ,
         695.76,   640.49,  2543.24,   322.27,  1727.59,  1881.93,
        1083.5 ,   976.5 ,  2274.86,  3621.04,   998.65,  1357.24,
        1366.43,  2659.86,  1724.47,  2450.48,  1359.58,  3059.32,
        1869.08,   639.5 ,  2451.8 ,  2833.87,  1873.73,  2270.37,
        2675.11,  2271.12,   321.59,  2265.29,  1466.25,  1728.17,
        1001.19,  2096.62,  2828.23,   300.32,   297.21,   643.53,
        2684.27,  2836.53,  1472.6 ,  1688.15,  1458.18,  2089.36,
        3200.82,  2683.3 ,  3055.04,  2844.98,  1688.66,  1358.2 ,
        1868.49,   996.42,   323.32,  3326.93,  2441.62,  1082.16,
        3143.72,   323.21,  1364.75,  2294.56,  1073.56,  2084.72,
         689.4 ,  1087.87,  1879.75,   695.31,  2671.47,  2832.93,
         644.52,  2083.07,   998.83,  1722.37,   697.69,   298.64,
        2674.81,  3090.73,   298.03,  1000.24,  1474.68,   693

array([ 1801.35669291,  1801.35669291,  1801.35669291,  1801.35669291,
        1801.35669291,  1801.35669291,  1801.35669291,  1801.35669291,
        1801.35669291,  1801.35669291,  1801.35669291,  1801.35669291,
        1801.35669291,  1801.35669291,  1801.35669291,  1801.35669291,
        1801.35669291,  1801.35669291,  1801.35669291,  1801.35669291,
        1801.35669291,  1801.35669291,  1801.35669291,  1801.35669291,
        1801.35669291,  1801.35669291,  1801.35669291,  1801.35669291,
        1801.35669291,  1801.35669291,  1801.35669291,  1801.35669291,
        1801.35669291,  1801.35669291,  1801.35669291,  1801.35669291,
        1801.35669291,  1801.35669291,  1801.35669291,  1801.35669291,
        1801.35669291,  1801.35669291,  1801.35669291,  1801.35669291,
        1801.35669291,  1801.35669291,  1801.35669291,  1801.35669291,
        1801.35669291,  1801.35669291,  1801.35669291,  1801.35669291,
        1801.35669291,  1801.35669291,  1801.35669291,  1801.35669291,
      

D: 97

{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}



array([ 2230.04,  1862.39,   218.82,  1036.27,  1332.56,  2119.13,
         460.34,  2241.22,   510.55,  1135.23,  2127.71,   216.12,
        1134.68,   504.45,   720.7 ,  1792.62,  1944.16,  1333.42,
         199.09,   810.75,  1637.05,   503.45,  1273.42,  1471.89,
        1333.76,   801.59,   801.4 ,  1031.47,   746.49,  2125.54,
        1929.21,  1802.26,  2442.42,   503.73,  1018.55,  1135.84,
        1467.78,   462.06,   216.58,   738.16,  2470.53,  2106.02,
         823.05,   813.15,   464.01,   814.27,   460.82,  2433.27,
        1139.61,   750.28,  2129.21,   198.28,  1808.07,   214.64,
         198.71,  2436.08,  1467.65,  2457.56,  1462.69,   198.88,
         505.67,   198.45,  1037.79,  1628.58,  2258.66,   197.88,
         747.33,  1324.9 ,  2453.84,  1801.74,   748.82,   504.63,
        1806.17,  2262.51,  1141.32,  2123.49,  1146.09,  1036.77,
        1623.84,  2142.12,  1925.99,  1469.66,  1037.18,   462.77,
        2478.78,  2239.73,  1780.16,  1959.63,  1459.44,   215

array([ 1801.35669291,  1801.35669291,  1801.35669291,  1801.35669291,
        1801.35669291,  1801.35669291,  1801.35669291,  1801.35669291,
        1801.35669291,  1801.35669291,  1801.35669291,  1801.35669291,
        1801.35669291,  1801.35669291,  1801.35669291,  1801.35669291,
        1801.35669291,  1801.35669291,  1801.35669291,  1801.35669291,
        1801.35669291,  1801.35669291,  1801.35669291,  1801.35669291,
        1801.35669291,  1801.35669291,  1801.35669291,  1801.35669291,
        1801.35669291,  1801.35669291,  1801.35669291,  1801.35669291,
        1801.35669291,  1801.35669291,  1801.35669291,  1801.35669291,
        1801.35669291,  1801.35669291,  1801.35669291,  1801.35669291,
        1801.35669291,  1801.35669291,  1801.35669291,  1801.35669291,
        1801.35669291,  1801.35669291,  1801.35669291,  1801.35669291,
        1801.35669291,  1801.35669291,  1801.35669291,  1801.35669291,
        1801.35669291,  1801.35669291,  1801.35669291,  1801.35669291,
      

【【】】adding new model for AB.pickle 

____________________________________________________________________________________________________

{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}

Dataset size read: train 192 and test 129 

# Tuning hyper-parameters 
[{'alpha': array([  1.00000000e-25,   1.91448198e-24,   3.66524124e-23,
         7.01703829e-22,   1.34339933e-20,   2.57191381e-19,
         4.92388263e-18,   9.42668455e-17,   1.80472177e-15,
         3.45510729e-14,   6.61474064e-13,   1.26638017e-11,
         2.42446202e-10,   4.64158883e-09,   8.88623816e-08,
         1.70125428e-06,   3.25702066e-05,   6.23550734e-04,
         1.19377664e-02,   2.28546386e-01,   4.37547938e+00,
         8.37677640e+01,   1.60371874e+03,   3.07029063e+04,
         5.87801607e+05,   1.12533558e+07,   2.15443469e+08,
         4.12462638e+09,   7.89652287e+10,   1.51177507e+12,
         2.89426612e+13,   5.54102033e+14,   1.06081836e+16,
         2.030917

/data/home/a1singh/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:484: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
/data/home/a1singh/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:484: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
/data/home/a1singh/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:484: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
/data/home/a1singh/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:484: ConvergenceWarni


Best parameters set found on development set:

{'alpha': 1603.7187437513408, 'l1_ratio': 0.9}
ElasticNet(alpha=1603.7187437513408, copy_X=True, fit_intercept=True,
      l1_ratio=0.9, max_iter=10000000.0, normalize=False, positive=False,
      precompute=False, random_state=None, selection='cyclic', tol=1e-20,
      warm_start=False)

Full Test Set: 129


array([  204.8 ,  1476.76,   464.01,  1146.09,  1036.77,  1634.05,
        1637.05,  1469.66,    97.49,  1467.65,   810.75,   746.49,
          21.6 ,    21.63,  2106.02,    98.42,   462.77,   198.28,
        2125.54,    67.96,   504.45,   214.64,  1333.76,   218.82,
         504.63,  1628.58,  1959.63,   460.82,  2457.56,  2478.78,
         814.27,   204.44,  1332.56,   748.82,  1037.18,   505.67,
        1925.99,  1459.44,   823.05,  2142.12,  2442.42,   462.06,
         197.88,    45.94,   738.16,  1471.89,    46.36,  2258.66,
         801.59,   750.28,   460.34,    45.82,  1780.16,    45.97,
        1333.42,    21.8 ,  1929.21,  1139.61,  2129.21,  2230.04,
        1031.47,  1627.26,  1792.62,   503.45,   141.66,  2470.53,
        2123.49,  1018.55,  2127.71,   216.58,   747.33,   121.17,
         164.88,  1135.84,   504.92,    68.75,   120.67,   203.98,
        1324.9 ,   164.02,   216.71,  1799.43,  1802.26,   199.09,
        1037.79,   215.55,  1467.78,  1036.27,    68.63,  1862

array([ 2013.70489583,  2013.70489583,  2013.70489583,  2013.70489583,
        2013.70489583,  2013.70489583,  2013.70489583,  2013.70489583,
        2013.70489583,  2013.70489583,  2013.70489583,  2013.70489583,
        2013.70489583,  2013.70489583,  2013.70489583,  2013.70489583,
        2013.70489583,  2013.70489583,  2013.70489583,  2013.70489583,
        2013.70489583,  2013.70489583,  2013.70489583,  2013.70489583,
        2013.70489583,  2013.70489583,  2013.70489583,  2013.70489583,
        2013.70489583,  2013.70489583,  2013.70489583,  2013.70489583,
        2013.70489583,  2013.70489583,  2013.70489583,  2013.70489583,
        2013.70489583,  2013.70489583,  2013.70489583,  2013.70489583,
        2013.70489583,  2013.70489583,  2013.70489583,  2013.70489583,
        2013.70489583,  2013.70489583,  2013.70489583,  2013.70489583,
        2013.70489583,  2013.70489583,  2013.70489583,  2013.70489583,
        2013.70489583,  2013.70489583,  2013.70489583,  2013.70489583,
      

A: 32

{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}



array([ 204.8 ,   97.49,   21.6 ,   21.63,   98.42,   67.96,  204.44,
         45.94,   46.36,   45.82,   45.97,   21.8 ,  141.66,  121.17,
        164.88,   68.75,  120.67,  203.98,  164.02,   68.63,  166.8 ,
        203.5 ,  173.64,  120.19,  120.44,  142.31,   67.97,   98.47,
         97.83,   21.58,  141.54,  142.07])

array([ 2013.70489583,  2013.70489583,  2013.70489583,  2013.70489583,
        2013.70489583,  2013.70489583,  2013.70489583,  2013.70489583,
        2013.70489583,  2013.70489583,  2013.70489583,  2013.70489583,
        2013.70489583,  2013.70489583,  2013.70489583,  2013.70489583,
        2013.70489583,  2013.70489583,  2013.70489583,  2013.70489583,
        2013.70489583,  2013.70489583,  2013.70489583,  2013.70489583,
        2013.70489583,  2013.70489583,  2013.70489583,  2013.70489583,
        2013.70489583,  2013.70489583,  2013.70489583,  2013.70489583])

D: 97

{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}



array([ 1476.76,   464.01,  1146.09,  1036.77,  1634.05,  1637.05,
        1469.66,  1467.65,   810.75,   746.49,  2106.02,   462.77,
         198.28,  2125.54,   504.45,   214.64,  1333.76,   218.82,
         504.63,  1628.58,  1959.63,   460.82,  2457.56,  2478.78,
         814.27,  1332.56,   748.82,  1037.18,   505.67,  1925.99,
        1459.44,   823.05,  2142.12,  2442.42,   462.06,   197.88,
         738.16,  1471.89,  2258.66,   801.59,   750.28,   460.34,
        1780.16,  1333.42,  1929.21,  1139.61,  2129.21,  2230.04,
        1031.47,  1627.26,  1792.62,   503.45,  2470.53,  2123.49,
        1018.55,  2127.71,   216.58,   747.33,  1135.84,   504.92,
        1324.9 ,   216.71,  1799.43,  1802.26,   199.09,  1037.79,
         215.55,  1467.78,  1036.27,  1862.39,   720.7 ,  2436.08,
        1806.17,  1135.23,  2239.73,   216.12,   813.15,  1141.32,
        1801.74,  1944.16,   198.71,   510.55,  1134.68,  2119.13,
        2241.22,  2450.37,   503.73,  2433.27,   198.88,  2453

array([ 2013.70489583,  2013.70489583,  2013.70489583,  2013.70489583,
        2013.70489583,  2013.70489583,  2013.70489583,  2013.70489583,
        2013.70489583,  2013.70489583,  2013.70489583,  2013.70489583,
        2013.70489583,  2013.70489583,  2013.70489583,  2013.70489583,
        2013.70489583,  2013.70489583,  2013.70489583,  2013.70489583,
        2013.70489583,  2013.70489583,  2013.70489583,  2013.70489583,
        2013.70489583,  2013.70489583,  2013.70489583,  2013.70489583,
        2013.70489583,  2013.70489583,  2013.70489583,  2013.70489583,
        2013.70489583,  2013.70489583,  2013.70489583,  2013.70489583,
        2013.70489583,  2013.70489583,  2013.70489583,  2013.70489583,
        2013.70489583,  2013.70489583,  2013.70489583,  2013.70489583,
        2013.70489583,  2013.70489583,  2013.70489583,  2013.70489583,
        2013.70489583,  2013.70489583,  2013.70489583,  2013.70489583,
        2013.70489583,  2013.70489583,  2013.70489583,  2013.70489583,
      

【【】】adding new model for BC.pickle 

____________________________________________________________________________________________________

{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}

Dataset size read: train 194 and test 127 

# Tuning hyper-parameters 
[{'alpha': array([  1.00000000e-25,   1.91448198e-24,   3.66524124e-23,
         7.01703829e-22,   1.34339933e-20,   2.57191381e-19,
         4.92388263e-18,   9.42668455e-17,   1.80472177e-15,
         3.45510729e-14,   6.61474064e-13,   1.26638017e-11,
         2.42446202e-10,   4.64158883e-09,   8.88623816e-08,
         1.70125428e-06,   3.25702066e-05,   6.23550734e-04,
         1.19377664e-02,   2.28546386e-01,   4.37547938e+00,
         8.37677640e+01,   1.60371874e+03,   3.07029063e+04,
         5.87801607e+05,   1.12533558e+07,   2.15443469e+08,
         4.12462638e+09,   7.89652287e+10,   1.51177507e+12,
         2.89426612e+13,   5.54102033e+14,   1.06081836e+16,
         2.030917

/data/home/a1singh/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:484: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
/data/home/a1singh/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:484: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
/data/home/a1singh/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:484: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
/data/home/a1singh/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:484: ConvergenceWarni


Best parameters set found on development set:

{'alpha': 1603.7187437513408, 'l1_ratio': 0.9}
ElasticNet(alpha=1603.7187437513408, copy_X=True, fit_intercept=True,
      l1_ratio=0.9, max_iter=10000000.0, normalize=False, positive=False,
      precompute=False, random_state=None, selection='cyclic', tol=1e-20,
      warm_start=False)

Full Test Set: 127


array([   98.42,  2486.13,   203.5 ,   121.17,  3348.91,  2661.74,
        1732.64,    68.75,  1332.03,  2000.17,  1445.01,  2472.15,
        2746.73,  1621.36,    21.6 ,    98.47,  1740.7 ,   141.66,
         120.19,  1423.13,   164.02,  3309.8 ,   120.67,   203.98,
        1447.46,  1593.28,  3353.35,  1315.75,  2762.97,  2754.95,
        2769.22,    68.63,  3186.16,  2940.97,  1721.38,  1861.97,
        1578.23,  3450.94,   204.44,  3359.25,  2001.65,  3444.3 ,
        1623.2 ,  3152.83,    97.49,  1425.64,  2896.27,  1616.34,
        3034.04,  3357.03,   164.88,  2006.73,  1174.9 ,  1331.2 ,
          45.94,    67.96,  3371.75,  2474.21,  1393.36,    45.82,
        2586.27,  1632.23,  2877.71,  1323.62,  1338.01,  1919.57,
         166.8 ,    21.63,  2308.37,  2544.55,  1932.2 ,  4234.26,
         142.07,  1895.33,  2397.91,  1620.72,  3192.92,    97.83,
        1846.6 ,  1320.38,    45.97,    46.36,  1329.19,  2213.16,
          21.58,  2376.19,  2201.04,  2179.65,  2184.34,  3153

array([ 1468.96927835,  1468.96927835,  1468.96927835,  1468.96927835,
        1468.96927835,  1468.96927835,  1468.96927835,  1468.96927835,
        1468.96927835,  1468.96927835,  1468.96927835,  1468.96927835,
        1468.96927835,  1468.96927835,  1468.96927835,  1468.96927835,
        1468.96927835,  1468.96927835,  1468.96927835,  1468.96927835,
        1468.96927835,  1468.96927835,  1468.96927835,  1468.96927835,
        1468.96927835,  1468.96927835,  1468.96927835,  1468.96927835,
        1468.96927835,  1468.96927835,  1468.96927835,  1468.96927835,
        1468.96927835,  1468.96927835,  1468.96927835,  1468.96927835,
        1468.96927835,  1468.96927835,  1468.96927835,  1468.96927835,
        1468.96927835,  1468.96927835,  1468.96927835,  1468.96927835,
        1468.96927835,  1468.96927835,  1468.96927835,  1468.96927835,
        1468.96927835,  1468.96927835,  1468.96927835,  1468.96927835,
        1468.96927835,  1468.96927835,  1468.96927835,  1468.96927835,
      

A: 32

{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}



array([  98.42,  203.5 ,  121.17,   68.75,   21.6 ,   98.47,  141.66,
        120.19,  164.02,  120.67,  203.98,   68.63,  204.44,   97.49,
        164.88,   45.94,   67.96,   45.82,  166.8 ,   21.63,  142.07,
         97.83,   45.97,   46.36,   21.58,  142.31,  173.64,  141.54,
         21.8 ,  204.8 ,  120.44,   67.97])

array([ 1468.96927835,  1468.96927835,  1468.96927835,  1468.96927835,
        1468.96927835,  1468.96927835,  1468.96927835,  1468.96927835,
        1468.96927835,  1468.96927835,  1468.96927835,  1468.96927835,
        1468.96927835,  1468.96927835,  1468.96927835,  1468.96927835,
        1468.96927835,  1468.96927835,  1468.96927835,  1468.96927835,
        1468.96927835,  1468.96927835,  1468.96927835,  1468.96927835,
        1468.96927835,  1468.96927835,  1468.96927835,  1468.96927835,
        1468.96927835,  1468.96927835,  1468.96927835,  1468.96927835])

B: 95

{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}



array([ 2486.13,  3348.91,  2661.74,  1732.64,  1332.03,  2000.17,
        1445.01,  2472.15,  2746.73,  1621.36,  1740.7 ,  1423.13,
        3309.8 ,  1447.46,  1593.28,  3353.35,  1315.75,  2762.97,
        2754.95,  2769.22,  3186.16,  2940.97,  1721.38,  1861.97,
        1578.23,  3450.94,  3359.25,  2001.65,  3444.3 ,  1623.2 ,
        3152.83,  1425.64,  2896.27,  1616.34,  3034.04,  3357.03,
        2006.73,  1174.9 ,  1331.2 ,  3371.75,  2474.21,  1393.36,
        2586.27,  1632.23,  2877.71,  1323.62,  1338.01,  1919.57,
        2308.37,  2544.55,  1932.2 ,  4234.26,  1895.33,  2397.91,
        1620.72,  3192.92,  1846.6 ,  1320.38,  1329.19,  2213.16,
        2376.19,  2201.04,  2179.65,  2184.34,  3153.06,  1914.93,
        3077.01,  2896.76,  1583.26,  2130.06,  3055.04,  2396.68,
        2461.26,  2210.97,  3336.48,  2024.25,  2587.3 ,  3040.59,
        2306.07,  1723.63,  3049.37,  2110.94,  2752.13,  2855.36,
        2293.62,  2314.1 ,  3167.66,  3186.2 ,  2181.44,  3028

array([ 1468.96927835,  1468.96927835,  1468.96927835,  1468.96927835,
        1468.96927835,  1468.96927835,  1468.96927835,  1468.96927835,
        1468.96927835,  1468.96927835,  1468.96927835,  1468.96927835,
        1468.96927835,  1468.96927835,  1468.96927835,  1468.96927835,
        1468.96927835,  1468.96927835,  1468.96927835,  1468.96927835,
        1468.96927835,  1468.96927835,  1468.96927835,  1468.96927835,
        1468.96927835,  1468.96927835,  1468.96927835,  1468.96927835,
        1468.96927835,  1468.96927835,  1468.96927835,  1468.96927835,
        1468.96927835,  1468.96927835,  1468.96927835,  1468.96927835,
        1468.96927835,  1468.96927835,  1468.96927835,  1468.96927835,
        1468.96927835,  1468.96927835,  1468.96927835,  1468.96927835,
        1468.96927835,  1468.96927835,  1468.96927835,  1468.96927835,
        1468.96927835,  1468.96927835,  1468.96927835,  1468.96927835,
        1468.96927835,  1468.96927835,  1468.96927835,  1468.96927835,
      

【【】】adding new model for CD.pickle 

____________________________________________________________________________________________________

{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}

Dataset size read: train 129 and test 192 

# Tuning hyper-parameters 
[{'alpha': array([  1.00000000e-25,   1.91448198e-24,   3.66524124e-23,
         7.01703829e-22,   1.34339933e-20,   2.57191381e-19,
         4.92388263e-18,   9.42668455e-17,   1.80472177e-15,
         3.45510729e-14,   6.61474064e-13,   1.26638017e-11,
         2.42446202e-10,   4.64158883e-09,   8.88623816e-08,
         1.70125428e-06,   3.25702066e-05,   6.23550734e-04,
         1.19377664e-02,   2.28546386e-01,   4.37547938e+00,
         8.37677640e+01,   1.60371874e+03,   3.07029063e+04,
         5.87801607e+05,   1.12533558e+07,   2.15443469e+08,
         4.12462638e+09,   7.89652287e+10,   1.51177507e+12,
         2.89426612e+13,   5.54102033e+14,   1.06081836e+16,
         2.030917

/data/home/a1singh/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:484: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
/data/home/a1singh/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:484: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
/data/home/a1singh/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:484: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
/data/home/a1singh/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:484: ConvergenceWarni


Best parameters set found on development set:

{'alpha': 1603.7187437513408, 'l1_ratio': 0.9}
ElasticNet(alpha=1603.7187437513408, copy_X=True, fit_intercept=True,
      l1_ratio=0.9, max_iter=10000000.0, normalize=False, positive=False,
      precompute=False, random_state=None, selection='cyclic', tol=1e-20,
      warm_start=False)

Full Test Set: 192


array([ 2239.73,   505.67,   810.75,   504.92,  2478.78,  1959.63,
        1425.64,  1801.74,  2450.37,  2754.95,  1634.05,  4234.26,
        1329.19,  1583.26,   214.64,  1141.32,  1628.58,  1932.2 ,
        2230.04,  2258.66,  3186.16,  1808.07,  2940.97,  1018.55,
         814.27,   823.05,  3371.75,  1740.7 ,  1037.79,  1423.13,
        2457.56,   199.09,   460.34,  3168.1 ,   801.59,  2470.53,
        2210.97,  1146.09,  1469.66,  1919.57,  1895.33,   216.58,
        2587.3 ,  1447.46,  1393.36,  2472.15,  2024.25,  2752.13,
        3353.35,  3444.3 ,  1861.97,  2201.04,  3192.92,  1929.21,
        1723.63,   198.88,  1338.01,   748.82,  2123.49,   216.12,
        3040.59,  2106.02,  1620.72,  2127.71,  2308.37,  2461.26,
        1332.56,  2486.13,  2433.27,  2607.84,  2511.62,   504.63,
        1925.99,  3153.06,  3049.37,  3077.01,  2181.44,  1445.01,
        3344.01,  2314.1 ,  1806.17,  2442.42,  2436.08,  2006.73,
        3336.48,  1462.69,   738.16,  2376.19,  1862.39,  1134

array([ 1277.54806202,  1277.54806202,  1277.54806202,  1277.54806202,
        1277.54806202,  1277.54806202,  1277.54806202,  1277.54806202,
        1277.54806202,  1277.54806202,  1277.54806202,  1277.54806202,
        1277.54806202,  1277.54806202,  1277.54806202,  1277.54806202,
        1277.54806202,  1277.54806202,  1277.54806202,  1277.54806202,
        1277.54806202,  1277.54806202,  1277.54806202,  1277.54806202,
        1277.54806202,  1277.54806202,  1277.54806202,  1277.54806202,
        1277.54806202,  1277.54806202,  1277.54806202,  1277.54806202,
        1277.54806202,  1277.54806202,  1277.54806202,  1277.54806202,
        1277.54806202,  1277.54806202,  1277.54806202,  1277.54806202,
        1277.54806202,  1277.54806202,  1277.54806202,  1277.54806202,
        1277.54806202,  1277.54806202,  1277.54806202,  1277.54806202,
        1277.54806202,  1277.54806202,  1277.54806202,  1277.54806202,
        1277.54806202,  1277.54806202,  1277.54806202,  1277.54806202,
      

B: 95

{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}



array([ 1425.64,  2754.95,  4234.26,  1329.19,  1583.26,  1932.2 ,
        3186.16,  2940.97,  3371.75,  1740.7 ,  1423.13,  3168.1 ,
        2210.97,  1919.57,  1895.33,  2587.3 ,  1447.46,  1393.36,
        2472.15,  2024.25,  2752.13,  3353.35,  3444.3 ,  1861.97,
        2201.04,  3192.92,  1723.63,  1338.01,  3040.59,  1620.72,
        2308.37,  2461.26,  2486.13,  2607.84,  2511.62,  3153.06,
        3049.37,  3077.01,  2181.44,  1445.01,  3344.01,  2314.1 ,
        2006.73,  3336.48,  2376.19,  2397.91,  2746.73,  3359.25,
        3348.91,  1332.03,  3028.27,  2306.07,  2877.71,  2001.65,
        3034.04,  1174.9 ,  1593.28,  1721.38,  1315.75,  3152.83,
        2293.62,  2586.27,  3450.94,  2110.94,  2896.27,  2657.91,
        1621.36,  1632.23,  3357.03,  1616.34,  2661.74,  3186.2 ,
        3055.04,  2544.55,  1323.62,  2396.68,  2474.21,  1623.2 ,
        1320.38,  2896.76,  1846.6 ,  2184.34,  2179.65,  1732.64,
        2000.17,  2762.97,  2213.16,  3309.8 ,  1331.2 ,  1578

array([ 1277.54806202,  1277.54806202,  1277.54806202,  1277.54806202,
        1277.54806202,  1277.54806202,  1277.54806202,  1277.54806202,
        1277.54806202,  1277.54806202,  1277.54806202,  1277.54806202,
        1277.54806202,  1277.54806202,  1277.54806202,  1277.54806202,
        1277.54806202,  1277.54806202,  1277.54806202,  1277.54806202,
        1277.54806202,  1277.54806202,  1277.54806202,  1277.54806202,
        1277.54806202,  1277.54806202,  1277.54806202,  1277.54806202,
        1277.54806202,  1277.54806202,  1277.54806202,  1277.54806202,
        1277.54806202,  1277.54806202,  1277.54806202,  1277.54806202,
        1277.54806202,  1277.54806202,  1277.54806202,  1277.54806202,
        1277.54806202,  1277.54806202,  1277.54806202,  1277.54806202,
        1277.54806202,  1277.54806202,  1277.54806202,  1277.54806202,
        1277.54806202,  1277.54806202,  1277.54806202,  1277.54806202,
        1277.54806202,  1277.54806202,  1277.54806202,  1277.54806202,
      

D: 97

{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}



array([ 2239.73,   505.67,   810.75,   504.92,  2478.78,  1959.63,
        1801.74,  2450.37,  1634.05,   214.64,  1141.32,  1628.58,
        2230.04,  2258.66,  1808.07,  1018.55,   814.27,   823.05,
        1037.79,  2457.56,   199.09,   460.34,   801.59,  2470.53,
        1146.09,  1469.66,   216.58,  1929.21,   198.88,   748.82,
        2123.49,   216.12,  2106.02,  2127.71,  1332.56,  2433.27,
         504.63,  1925.99,  1806.17,  2442.42,  2436.08,  1462.69,
         738.16,  1862.39,  1134.68,  1792.62,  1135.84,   504.45,
         746.49,   813.15,   218.82,  2142.12,  1627.26,  1036.27,
        1135.23,   198.28,   460.82,   510.55,   464.01,  1637.05,
        1944.16,   216.71,   462.06,  1324.9 ,  1273.42,  2129.21,
        1623.84,   750.28,  1799.43,  1139.61,  1467.78,   801.4 ,
        1802.26,  1459.44,   747.33,  2453.84,  1471.89,   503.45,
        1467.65,  2262.51,  1036.77,   503.73,   198.71,  2119.13,
         462.77,   197.88,   215.55,  1037.18,   720.7 ,  1476

array([ 1277.54806202,  1277.54806202,  1277.54806202,  1277.54806202,
        1277.54806202,  1277.54806202,  1277.54806202,  1277.54806202,
        1277.54806202,  1277.54806202,  1277.54806202,  1277.54806202,
        1277.54806202,  1277.54806202,  1277.54806202,  1277.54806202,
        1277.54806202,  1277.54806202,  1277.54806202,  1277.54806202,
        1277.54806202,  1277.54806202,  1277.54806202,  1277.54806202,
        1277.54806202,  1277.54806202,  1277.54806202,  1277.54806202,
        1277.54806202,  1277.54806202,  1277.54806202,  1277.54806202,
        1277.54806202,  1277.54806202,  1277.54806202,  1277.54806202,
        1277.54806202,  1277.54806202,  1277.54806202,  1277.54806202,
        1277.54806202,  1277.54806202,  1277.54806202,  1277.54806202,
        1277.54806202,  1277.54806202,  1277.54806202,  1277.54806202,
        1277.54806202,  1277.54806202,  1277.54806202,  1277.54806202,
        1277.54806202,  1277.54806202,  1277.54806202,  1277.54806202,
      

【【】】adding new model for AC.pickle 

____________________________________________________________________________________________________

{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}

Dataset size read: train 129 and test 192 

# Tuning hyper-parameters 
[{'alpha': array([  1.00000000e-25,   1.91448198e-24,   3.66524124e-23,
         7.01703829e-22,   1.34339933e-20,   2.57191381e-19,
         4.92388263e-18,   9.42668455e-17,   1.80472177e-15,
         3.45510729e-14,   6.61474064e-13,   1.26638017e-11,
         2.42446202e-10,   4.64158883e-09,   8.88623816e-08,
         1.70125428e-06,   3.25702066e-05,   6.23550734e-04,
         1.19377664e-02,   2.28546386e-01,   4.37547938e+00,
         8.37677640e+01,   1.60371874e+03,   3.07029063e+04,
         5.87801607e+05,   1.12533558e+07,   2.15443469e+08,
         4.12462638e+09,   7.89652287e+10,   1.51177507e+12,
         2.89426612e+13,   5.54102033e+14,   1.06081836e+16,
         2.030917

/data/home/a1singh/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:484: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
/data/home/a1singh/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:484: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
/data/home/a1singh/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:484: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
/data/home/a1singh/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:484: ConvergenceWarni

In [ ]:
t_print = t_elasticNet

for key in t_print.keys():
    print(80*'_')
    print(key)    

    print('Model: %s' % (str(t_print[key]['model'])[:20]))
    print('Train RMSE: %f \n' % (t_print[key]['train_rmse_cv_picking']))

    #print('Test RMSE   : %f' % (t_print[key]['test_rmse_reporting']))
    #print('Overall Mean: %f \n' % (t_print[key]['test_mean_y_comparing']))

    if(not t_print[key]['test_rmse_reportingA']==None):
        print('A...TestA RMSE   : %f' % float(t_print[key]['test_rmse_reportingA'] or -1))
        print('A...<<y_test_A Mean>>: %f \n' % float(t_print[key]['test_mean_y_comparingA'] or -1))

    if(not t_print[key]['test_rmse_reportingB']==None):
        print('B...TestB RMSE   : %f' % float(t_print[key]['test_rmse_reportingB'] or -1))
        print('B...<<y_test_B Mean>>: %f \n' % float(t_print[key]['test_mean_y_comparingB'] or -1))

    if(not t_print[key]['test_rmse_reportingC']==None):
        print('C...TestC RMSE   : %f' % float(t_print[key]['test_rmse_reportingC'] or -1))
        print('C...<<y_test_C Mean>>: %f \n' % float(t_print[key]['test_mean_y_comparingC'] or -1))

    if(not t_print[key]['test_rmse_reportingD']==None):
        print('D...TestD RMSE   : %f' % float(t_print[key]['test_rmse_reportingD'] or -1))
        print('D...<<y_test_D Mean>>: %f' % float(t_print[key]['test_mean_y_comparingD'] or -1))

    print(80*'_')