In [2]:
# import all the filenames
from allfunctions import *

In [3]:
%load_ext autoreload
%autoreload 2

7  def SVRSigmoidCVModel(filename):
 
8 def SVRRbfCVModel(filename):

In [4]:
def wrapper(functionList = []):
    if __name__ == '__main__':
        global model_selection
        global filenames
        
        filenames = ['ABC.pickle', 'BCD.pickle', 'CDA.pickle', 'DAB.pickle' ]
        
        model_selection = {}
        
        for f in functionList:
            print()
            for filename in filenames:
                print('function = %s, filename = %s' % (f,filename))
                out = f(filename)
                newScore = out[filename]['train_rmse_cv_picking']

                if filename in model_selection:
                    #compare scores and select more accurate model
                    oldScore = model_selection[filename]['train_rmse_cv_picking']
                    if(newScore < oldScore):
                        print("【【【】】】switching models for %s..." % filename)
                        print("【【【】】】newScore: %f < oldScore: %f" % (newScore, oldScore))
                        print("【【【】】】newModel: %s \n" % f)
                        print(100*'_')
                        model_selection[filename] = out[filename]
                else:
                    #no score to compare
                    print("【【】】adding new model for %s \n" % filename)
                    print(100*'_')
                    model_selection[filename] = out[filename]
    return model_selection

# Linear Kernel

In [6]:
t_SVRLinearCVModel = wrapper([ SVRLinearCVModel ])


function = <function SVRLinearCVModel at 0x7f8e8e4c86a8>, filename = ABC.pickle
Dataset size read: train 224 and test 97 

# Tuning hyper-parameters 

Starting grdsurch.fit(X_train, y_train)

 Best parameters set found on development set:

{'C': 3.1622776601683792e-08}
SVR(C=3.1622776601683792e-08, cache_size=20480, coef0=0.0, degree=3,
  epsilon=0.1, gamma='auto', kernel='linear', max_iter=-1, shrinking=False,
  tol=1e-07, verbose=False)

Full Test Set: 97


array([  746.49,  1959.63,   216.12,  1031.47,   462.77,  2239.73,
         198.71,   801.4 ,  2470.53,   199.09,  2230.04,  1018.55,
         218.82,  1806.17,  1634.05,   810.75,   464.01,   460.34,
         198.88,  2436.08,  1467.65,  1037.18,  1944.16,   750.28,
         748.82,   504.45,  2478.78,  2241.22,  1792.62,  1141.32,
         505.67,   510.55,   823.05,  2258.66,   738.16,   503.73,
        2125.54,  1273.42,  2142.12,  1799.43,   747.33,  1801.74,
        1802.26,  2119.13,  1332.56,  2106.02,   214.64,  1459.44,
        1627.26,  1139.61,  1623.84,  1036.77,  2442.42,   216.71,
        2450.37,   462.06,  2433.27,  1476.76,   813.15,   504.63,
        1037.79,  1134.68,   460.82,  1808.07,  1467.78,  1135.84,
         504.92,   215.55,  1471.89,   801.59,  1135.23,  1324.9 ,
        1637.05,  1462.69,   814.27,  1628.58,  2262.51,  2123.49,
        1929.21,  2453.84,  1862.39,   216.58,   198.28,  1333.76,
         720.7 ,  1469.66,   197.88,  1925.99,  2129.21,   503

array([ 1941.76475111,  1941.76476344,  1941.76474537,  1941.76475461,
        1941.76474833,  1941.76476628,  1941.76474504,  1941.76475128,
        1941.76476628,  1941.76474554,  1941.76476661,  1941.76475444,
        1941.76474554,  1941.76476028,  1941.76476011,  1941.76475161,
        1941.76474849,  1941.76474816,  1941.76474537,  1941.76476661,
        1941.76475744,  1941.76475428,  1941.76476361,  1941.76475161,
        1941.76475144,  1941.76474833,  1941.76476644,  1941.76476611,
        1941.76476028,  1941.76475411,  1941.76474833,  1941.76474816,
        1941.76475111,  1941.76476611,  1941.76475128,  1941.76474849,
        1941.76476311,  1941.76475761,  1941.76476328,  1941.76476011,
        1941.76475161,  1941.76476011,  1941.76476061,  1941.76476344,
        1941.76475744,  1941.76476344,  1941.76474521,  1941.76475728,
        1941.76476061,  1941.76475428,  1941.76476028,  1941.76475461,
        1941.76476644,  1941.76474521,  1941.76476661,  1941.76474799,
      

D: 97


array([  746.49,  1959.63,   216.12,  1031.47,   462.77,  2239.73,
         198.71,   801.4 ,  2470.53,   199.09,  2230.04,  1018.55,
         218.82,  1806.17,  1634.05,   810.75,   464.01,   460.34,
         198.88,  2436.08,  1467.65,  1037.18,  1944.16,   750.28,
         748.82,   504.45,  2478.78,  2241.22,  1792.62,  1141.32,
         505.67,   510.55,   823.05,  2258.66,   738.16,   503.73,
        2125.54,  1273.42,  2142.12,  1799.43,   747.33,  1801.74,
        1802.26,  2119.13,  1332.56,  2106.02,   214.64,  1459.44,
        1627.26,  1139.61,  1623.84,  1036.77,  2442.42,   216.71,
        2450.37,   462.06,  2433.27,  1476.76,   813.15,   504.63,
        1037.79,  1134.68,   460.82,  1808.07,  1467.78,  1135.84,
         504.92,   215.55,  1471.89,   801.59,  1135.23,  1324.9 ,
        1637.05,  1462.69,   814.27,  1628.58,  2262.51,  2123.49,
        1929.21,  2453.84,  1862.39,   216.58,   198.28,  1333.76,
         720.7 ,  1469.66,   197.88,  1925.99,  2129.21,   503

array([ 1941.76475111,  1941.76476344,  1941.76474537,  1941.76475461,
        1941.76474833,  1941.76476628,  1941.76474504,  1941.76475128,
        1941.76476628,  1941.76474554,  1941.76476661,  1941.76475444,
        1941.76474554,  1941.76476028,  1941.76476011,  1941.76475161,
        1941.76474849,  1941.76474816,  1941.76474537,  1941.76476661,
        1941.76475744,  1941.76475428,  1941.76476361,  1941.76475161,
        1941.76475144,  1941.76474833,  1941.76476644,  1941.76476611,
        1941.76476028,  1941.76475411,  1941.76474833,  1941.76474816,
        1941.76475111,  1941.76476611,  1941.76475128,  1941.76474849,
        1941.76476311,  1941.76475761,  1941.76476328,  1941.76476011,
        1941.76475161,  1941.76476011,  1941.76476061,  1941.76476344,
        1941.76475744,  1941.76476344,  1941.76474521,  1941.76475728,
        1941.76476061,  1941.76475428,  1941.76476028,  1941.76475461,
        1941.76476644,  1941.76474521,  1941.76476661,  1941.76474799,
      

【【】】adding new model for ABC.pickle 

____________________________________________________________________________________________________
function = <function SVRLinearCVModel at 0x7f8e8e4c86a8>, filename = BCD.pickle
Dataset size read: train 289 and test 32 

# Tuning hyper-parameters 

Starting grdsurch.fit(X_train, y_train)

 Best parameters set found on development set:

{'C': 1.0000000000000001e-15}
SVR(C=1.0000000000000001e-15, cache_size=20480, coef0=0.0, degree=3,
  epsilon=0.1, gamma='auto', kernel='linear', max_iter=-1, shrinking=False,
  tol=1e-07, verbose=False)

Full Test Set: 32


array([ 203.5 ,  142.31,  121.17,   97.83,   21.58,  164.02,  164.88,
         67.96,   98.42,  120.19,  141.66,   98.47,   67.97,  204.44,
         45.97,   45.94,  173.64,  120.44,  203.98,  142.07,  141.54,
         21.8 ,   46.36,   68.75,   97.49,  120.67,  166.8 ,   45.82,
         21.63,   68.63,   21.6 ,  204.8 ])

array([ 1792.61999857,  1792.61999857,  1792.61999857,  1792.61999857,
        1792.61999857,  1792.61999857,  1792.61999857,  1792.61999857,
        1792.61999857,  1792.61999857,  1792.61999857,  1792.61999857,
        1792.61999857,  1792.61999857,  1792.61999857,  1792.61999857,
        1792.61999857,  1792.61999857,  1792.61999857,  1792.61999857,
        1792.61999857,  1792.61999857,  1792.61999857,  1792.61999857,
        1792.61999857,  1792.61999857,  1792.61999857,  1792.61999857,
        1792.61999857,  1792.61999857,  1792.61999857,  1792.61999857])

A: 32


array([ 203.5 ,  142.31,  121.17,   97.83,   21.58,  164.02,  164.88,
         67.96,   98.42,  120.19,  141.66,   98.47,   67.97,  204.44,
         45.97,   45.94,  173.64,  120.44,  203.98,  142.07,  141.54,
         21.8 ,   46.36,   68.75,   97.49,  120.67,  166.8 ,   45.82,
         21.63,   68.63,   21.6 ,  204.8 ])

array([ 1792.61999857,  1792.61999857,  1792.61999857,  1792.61999857,
        1792.61999857,  1792.61999857,  1792.61999857,  1792.61999857,
        1792.61999857,  1792.61999857,  1792.61999857,  1792.61999857,
        1792.61999857,  1792.61999857,  1792.61999857,  1792.61999857,
        1792.61999857,  1792.61999857,  1792.61999857,  1792.61999857,
        1792.61999857,  1792.61999857,  1792.61999857,  1792.61999857,
        1792.61999857,  1792.61999857,  1792.61999857,  1792.61999857,
        1792.61999857,  1792.61999857,  1792.61999857,  1792.61999857])

【【】】adding new model for BCD.pickle 

____________________________________________________________________________________________________
function = <function SVRLinearCVModel at 0x7f8e8e4c86a8>, filename = CDA.pickle
Dataset size read: train 226 and test 95 

# Tuning hyper-parameters 

Starting grdsurch.fit(X_train, y_train)

 Best parameters set found on development set:

{'C': 1.0000000000000001e-15}
SVR(C=1.0000000000000001e-15, cache_size=20480, coef0=0.0, degree=3,
  epsilon=0.1, gamma='auto', kernel='linear', max_iter=-1, shrinking=False,
  tol=1e-07, verbose=False)

Full Test Set: 95


array([ 2213.16,  2607.84,  3167.66,  3153.06,  2746.73,  2201.04,
        1329.19,  1338.01,  1723.63,  2314.1 ,  1332.03,  2006.73,
        1425.64,  3353.35,  2293.62,  1914.93,  4234.26,  3309.8 ,
        1846.6 ,  1323.62,  2110.94,  3034.04,  1445.01,  2657.91,
        3336.48,  3444.3 ,  2472.15,  1616.34,  1740.7 ,  2000.17,
        2181.44,  3040.59,  2396.68,  2754.95,  2877.71,  3450.94,
        3357.03,  1732.64,  3168.1 ,  1932.2 ,  1423.13,  2587.3 ,
        2896.76,  3344.01,  1174.9 ,  2855.36,  2752.13,  2024.25,
        2661.74,  2130.06,  1861.97,  1578.23,  3152.83,  2544.55,
        2474.21,  1621.36,  1620.72,  2210.97,  2376.19,  2308.37,
        3028.27,  2001.65,  2896.27,  3055.04,  1447.46,  1583.26,
        3348.91,  2586.27,  1331.2 ,  1393.36,  3186.2 ,  3359.25,
        3371.75,  3192.92,  1895.33,  1632.23,  2461.26,  2940.97,
        1320.38,  3077.01,  1315.75,  2769.22,  1721.38,  2486.13,
        1919.57,  3186.16,  2306.07,  2179.65,  2511.62,  3049

array([ 1137.72501172,  1137.72501172,  1137.72501172,  1137.72501172,
        1137.72501172,  1137.72501172,  1137.72501172,  1137.72501172,
        1137.72501172,  1137.72501172,  1137.72501172,  1137.72501172,
        1137.72501172,  1137.72501172,  1137.72501172,  1137.72501172,
        1137.72501172,  1137.72501172,  1137.72501172,  1137.72501172,
        1137.72501172,  1137.72501172,  1137.72501172,  1137.72501172,
        1137.72501172,  1137.72501172,  1137.72501172,  1137.72501172,
        1137.72501172,  1137.72501172,  1137.72501172,  1137.72501172,
        1137.72501172,  1137.72501172,  1137.72501172,  1137.72501172,
        1137.72501172,  1137.72501172,  1137.72501172,  1137.72501172,
        1137.72501172,  1137.72501172,  1137.72501172,  1137.72501172,
        1137.72501172,  1137.72501172,  1137.72501172,  1137.72501172,
        1137.72501172,  1137.72501172,  1137.72501172,  1137.72501172,
        1137.72501172,  1137.72501172,  1137.72501172,  1137.72501172,
      

B: 95


array([ 2213.16,  2607.84,  3167.66,  3153.06,  2746.73,  2201.04,
        1329.19,  1338.01,  1723.63,  2314.1 ,  1332.03,  2006.73,
        1425.64,  3353.35,  2293.62,  1914.93,  4234.26,  3309.8 ,
        1846.6 ,  1323.62,  2110.94,  3034.04,  1445.01,  2657.91,
        3336.48,  3444.3 ,  2472.15,  1616.34,  1740.7 ,  2000.17,
        2181.44,  3040.59,  2396.68,  2754.95,  2877.71,  3450.94,
        3357.03,  1732.64,  3168.1 ,  1932.2 ,  1423.13,  2587.3 ,
        2896.76,  3344.01,  1174.9 ,  2855.36,  2752.13,  2024.25,
        2661.74,  2130.06,  1861.97,  1578.23,  3152.83,  2544.55,
        2474.21,  1621.36,  1620.72,  2210.97,  2376.19,  2308.37,
        3028.27,  2001.65,  2896.27,  3055.04,  1447.46,  1583.26,
        3348.91,  2586.27,  1331.2 ,  1393.36,  3186.2 ,  3359.25,
        3371.75,  3192.92,  1895.33,  1632.23,  2461.26,  2940.97,
        1320.38,  3077.01,  1315.75,  2769.22,  1721.38,  2486.13,
        1919.57,  3186.16,  2306.07,  2179.65,  2511.62,  3049

array([ 1137.72501172,  1137.72501172,  1137.72501172,  1137.72501172,
        1137.72501172,  1137.72501172,  1137.72501172,  1137.72501172,
        1137.72501172,  1137.72501172,  1137.72501172,  1137.72501172,
        1137.72501172,  1137.72501172,  1137.72501172,  1137.72501172,
        1137.72501172,  1137.72501172,  1137.72501172,  1137.72501172,
        1137.72501172,  1137.72501172,  1137.72501172,  1137.72501172,
        1137.72501172,  1137.72501172,  1137.72501172,  1137.72501172,
        1137.72501172,  1137.72501172,  1137.72501172,  1137.72501172,
        1137.72501172,  1137.72501172,  1137.72501172,  1137.72501172,
        1137.72501172,  1137.72501172,  1137.72501172,  1137.72501172,
        1137.72501172,  1137.72501172,  1137.72501172,  1137.72501172,
        1137.72501172,  1137.72501172,  1137.72501172,  1137.72501172,
        1137.72501172,  1137.72501172,  1137.72501172,  1137.72501172,
        1137.72501172,  1137.72501172,  1137.72501172,  1137.72501172,
      

【【】】adding new model for CDA.pickle 

____________________________________________________________________________________________________
function = <function SVRLinearCVModel at 0x7f8e8e4c86a8>, filename = DAB.pickle
Dataset size read: train 224 and test 97 

# Tuning hyper-parameters 

Starting grdsurch.fit(X_train, y_train)

 Best parameters set found on development set:

{'C': 1.0000000000000001e-15}
SVR(C=1.0000000000000001e-15, cache_size=20480, coef0=0.0, degree=3,
  epsilon=0.1, gamma='auto', kernel='linear', max_iter=-1, shrinking=False,
  tol=1e-07, verbose=False)

Full Test Set: 97


array([  299.12,   297.65,  2271.12,  1870.14,   976.5 ,  1357.24,
         320.75,  3085.44,  1073.56,  1688.66,  1366.43,  1728.17,
        1365.13,  2674.81,  2294.56,   639.5 ,  2684.27,  2671.47,
        2087.18,   297.21,  1869.08,  1364.75,  2089.36,  1881.93,
        3621.04,   998.65,  1083.5 ,  3055.04,  2828.23,  2265.29,
        1470.8 ,   322.13,   695.76,   643.53,  3326.93,   322.27,
         323.32,   298.64,  2844.98,   640.49,  1724.47,  2675.11,
        3090.73,   692.62,  1076.1 ,   298.03,  1082.16,  2270.37,
        2659.86,   691.73,  2083.07,  2832.66,  2096.62,  2771.25,
         643.1 ,  1873.73,  1458.18,  2084.72,  2392.64,  2543.24,
         996.42,  1474.68,   998.83,   300.32,  3143.72,  1087.87,
        3200.82,  1359.58,  2683.3 ,  2274.86,  3059.32,   323.21,
        1688.15,  2451.8 ,  1001.19,  2450.48,  1727.59,  1868.49,
        2832.93,   693.29,   695.31,  1000.24,  1080.  ,  1722.37,
        1472.6 ,  2441.62,  1857.77,  1879.75,  1466.25,  2833

array([ 1623.52001721,  1623.52001721,  1623.52001721,  1623.52001721,
        1623.52001721,  1623.52001721,  1623.52001721,  1623.52001721,
        1623.52001721,  1623.52001721,  1623.52001721,  1623.52001721,
        1623.52001721,  1623.52001721,  1623.52001721,  1623.52001721,
        1623.52001721,  1623.52001721,  1623.52001721,  1623.52001721,
        1623.52001721,  1623.52001721,  1623.52001721,  1623.52001721,
        1623.52001721,  1623.52001721,  1623.52001721,  1623.52001721,
        1623.52001721,  1623.52001721,  1623.52001721,  1623.52001721,
        1623.52001721,  1623.52001721,  1623.52001721,  1623.52001721,
        1623.52001721,  1623.52001721,  1623.52001721,  1623.52001721,
        1623.52001721,  1623.52001721,  1623.52001721,  1623.52001721,
        1623.52001721,  1623.52001721,  1623.52001721,  1623.52001721,
        1623.52001721,  1623.52001721,  1623.52001721,  1623.52001721,
        1623.52001721,  1623.52001721,  1623.52001721,  1623.52001721,
      

C: 97


array([  299.12,   297.65,  2271.12,  1870.14,   976.5 ,  1357.24,
         320.75,  3085.44,  1073.56,  1688.66,  1366.43,  1728.17,
        1365.13,  2674.81,  2294.56,   639.5 ,  2684.27,  2671.47,
        2087.18,   297.21,  1869.08,  1364.75,  2089.36,  1881.93,
        3621.04,   998.65,  1083.5 ,  3055.04,  2828.23,  2265.29,
        1470.8 ,   322.13,   695.76,   643.53,  3326.93,   322.27,
         323.32,   298.64,  2844.98,   640.49,  1724.47,  2675.11,
        3090.73,   692.62,  1076.1 ,   298.03,  1082.16,  2270.37,
        2659.86,   691.73,  2083.07,  2832.66,  2096.62,  2771.25,
         643.1 ,  1873.73,  1458.18,  2084.72,  2392.64,  2543.24,
         996.42,  1474.68,   998.83,   300.32,  3143.72,  1087.87,
        3200.82,  1359.58,  2683.3 ,  2274.86,  3059.32,   323.21,
        1688.15,  2451.8 ,  1001.19,  2450.48,  1727.59,  1868.49,
        2832.93,   693.29,   695.31,  1000.24,  1080.  ,  1722.37,
        1472.6 ,  2441.62,  1857.77,  1879.75,  1466.25,  2833

array([ 1623.52001721,  1623.52001721,  1623.52001721,  1623.52001721,
        1623.52001721,  1623.52001721,  1623.52001721,  1623.52001721,
        1623.52001721,  1623.52001721,  1623.52001721,  1623.52001721,
        1623.52001721,  1623.52001721,  1623.52001721,  1623.52001721,
        1623.52001721,  1623.52001721,  1623.52001721,  1623.52001721,
        1623.52001721,  1623.52001721,  1623.52001721,  1623.52001721,
        1623.52001721,  1623.52001721,  1623.52001721,  1623.52001721,
        1623.52001721,  1623.52001721,  1623.52001721,  1623.52001721,
        1623.52001721,  1623.52001721,  1623.52001721,  1623.52001721,
        1623.52001721,  1623.52001721,  1623.52001721,  1623.52001721,
        1623.52001721,  1623.52001721,  1623.52001721,  1623.52001721,
        1623.52001721,  1623.52001721,  1623.52001721,  1623.52001721,
        1623.52001721,  1623.52001721,  1623.52001721,  1623.52001721,
        1623.52001721,  1623.52001721,  1623.52001721,  1623.52001721,
      

【【】】adding new model for DAB.pickle 

____________________________________________________________________________________________________


In [7]:
t_print = t_SVRLinearCVModel

for key in t_print.keys():
    print(80*'_')
    print(key)    

    print('Model: %s' % (str(t_print[key]['model'])[:20]))
    print('Train RMSE: %f \n' % (t_print[key]['train_rmse_cv_picking']))

    #print('Test RMSE   : %f' % (t_print[key]['test_rmse_reporting']))
    #print('Overall Mean: %f \n' % (t_print[key]['test_mean_y_comparing']))

    if(not t_print[key]['test_rmse_reportingA']==None):
        print('A...TestA RMSE   : %f' % float(t_print[key]['test_rmse_reportingA'] or -1))
        print('A...<<y_test_A Mean>>: %f \n' % float(t_print[key]['test_mean_y_comparingA'] or -1))

    if(not t_print[key]['test_rmse_reportingB']==None):
        print('B...TestB RMSE   : %f' % float(t_print[key]['test_rmse_reportingB'] or -1))
        print('B...<<y_test_B Mean>>: %f \n' % float(t_print[key]['test_mean_y_comparingB'] or -1))

    if(not t_print[key]['test_rmse_reportingC']==None):
        print('C...TestC RMSE   : %f' % float(t_print[key]['test_rmse_reportingC'] or -1))
        print('C...<<y_test_C Mean>>: %f \n' % float(t_print[key]['test_mean_y_comparingC'] or -1))

    if(not t_print[key]['test_rmse_reportingD']==None):
        print('D...TestD RMSE   : %f' % float(t_print[key]['test_rmse_reportingD'] or -1))
        print('D...<<y_test_D Mean>>: %f' % float(t_print[key]['test_mean_y_comparingD'] or -1))

    print(80*'_')

________________________________________________________________________________
BCD.pickle
Model: SVR(C=1.000000000000
Train RMSE: 909.816664 

A...TestA RMSE   : 1685.113711
A...<<y_test_A Mean>>: 108.510312 

________________________________________________________________________________
________________________________________________________________________________
ABC.pickle
Model: SVR(C=3.162277660168
Train RMSE: 1067.628837 

D...TestD RMSE   : 982.115048
D...<<y_test_D Mean>>: 1274.728557
________________________________________________________________________________
________________________________________________________________________________
DAB.pickle
Model: SVR(C=1.000000000000
Train RMSE: 1030.233724 

C...TestC RMSE   : 915.818628
C...<<y_test_C Mean>>: 1663.210000 

________________________________________________________________________________
________________________________________________________________________________
CDA.pickle
Model: SVR(C=1.000000000000
T

In [8]:
# write the model
import pickle

#||||||||||||||||||| 
t_ = t_SVRLinearCVModel
prefix = '4C3_' + 'SVRLinearCVModel'
#||||||||||||||||||| 

for k in t_.keys():
    mo   = t_[k]['model']
    fname = prefix + '_tuned_' + str(k[:3]) + '.pickle'
    
    print()
    print(k, str(mo)[:30])
    
    print(fname)
    # write the model to a file
    with open(fname, 'wb') as handle:
        pickle.dump(mo, handle)


BCD.pickle SVR(C=1.0000000000000001e-15, 
4C3_SVRLinearCVModel_tuned_BCD.pickle

ABC.pickle SVR(C=3.1622776601683792e-08, 
4C3_SVRLinearCVModel_tuned_ABC.pickle

DAB.pickle SVR(C=1.0000000000000001e-15, 
4C3_SVRLinearCVModel_tuned_DAB.pickle

CDA.pickle SVR(C=1.0000000000000001e-15, 
4C3_SVRLinearCVModel_tuned_CDA.pickle


# Poly Kernel

In [5]:
t_SSVRPolyCVModel = wrapper([ SVRPolyCVModel ])


function = <function SVRPolyCVModel at 0x7f8e8e4c8598>, filename = ABC.pickle
Dataset size read: train 224 and test 97 

# Tuning hyper-parameters... 

Starting grdsurch.fit(X_train, y_train)


JoblibValueError: JoblibValueError
___________________________________________________________________________
Multiprocessing exception:
...........................................................................
/usr/lib/python3.4/runpy.py in _run_module_as_main(mod_name='ipykernel.__main__', alter_argv=1)
    165         sys.exit(msg)
    166     main_globals = sys.modules["__main__"].__dict__
    167     if alter_argv:
    168         sys.argv[0] = mod_spec.origin
    169     return _run_code(code, main_globals, None,
--> 170                      "__main__", mod_spec)
        mod_spec = ModuleSpec(name='ipykernel.__main__', loader=<_f...b/python3.4/dist-packages/ipykernel/__main__.py')
    171 
    172 def run_module(mod_name, init_globals=None,
    173                run_name=None, alter_sys=False):
    174     """Execute a module's code without importing it

...........................................................................
/usr/lib/python3.4/runpy.py in _run_code(code=<code object <module> at 0x7f8ebb70b4b0, file "/...3.4/dist-packages/ipykernel/__main__.py", line 1>, run_globals={'__builtins__': <module 'builtins' (built-in)>, '__cached__': '/usr/local/lib/python3.4/dist-packages/ipykernel/__pycache__/__main__.cpython-34.pyc', '__doc__': None, '__file__': '/usr/local/lib/python3.4/dist-packages/ipykernel/__main__.py', '__loader__': <_frozen_importlib.SourceFileLoader object>, '__name__': '__main__', '__package__': 'ipykernel', '__spec__': ModuleSpec(name='ipykernel.__main__', loader=<_f...b/python3.4/dist-packages/ipykernel/__main__.py'), 'app': <module 'ipykernel.kernelapp' from '/usr/local/lib/python3.4/dist-packages/ipykernel/kernelapp.py'>}, init_globals=None, mod_name='__main__', mod_spec=ModuleSpec(name='ipykernel.__main__', loader=<_f...b/python3.4/dist-packages/ipykernel/__main__.py'), pkg_name='ipykernel', script_name=None)
     80                        __cached__ = cached,
     81                        __doc__ = None,
     82                        __loader__ = loader,
     83                        __package__ = pkg_name,
     84                        __spec__ = mod_spec)
---> 85     exec(code, run_globals)
        code = <code object <module> at 0x7f8ebb70b4b0, file "/...3.4/dist-packages/ipykernel/__main__.py", line 1>
        run_globals = {'__builtins__': <module 'builtins' (built-in)>, '__cached__': '/usr/local/lib/python3.4/dist-packages/ipykernel/__pycache__/__main__.cpython-34.pyc', '__doc__': None, '__file__': '/usr/local/lib/python3.4/dist-packages/ipykernel/__main__.py', '__loader__': <_frozen_importlib.SourceFileLoader object>, '__name__': '__main__', '__package__': 'ipykernel', '__spec__': ModuleSpec(name='ipykernel.__main__', loader=<_f...b/python3.4/dist-packages/ipykernel/__main__.py'), 'app': <module 'ipykernel.kernelapp' from '/usr/local/lib/python3.4/dist-packages/ipykernel/kernelapp.py'>}
     86     return run_globals
     87 
     88 def _run_module_code(code, init_globals=None,
     89                     mod_name=None, mod_spec=None,

...........................................................................
/usr/local/lib/python3.4/dist-packages/ipykernel/__main__.py in <module>()
      1 
      2 
----> 3 
      4 if __name__ == '__main__':
      5     from ipykernel import kernelapp as app
      6     app.launch_new_instance()
      7 
      8 
      9 
     10 

...........................................................................
/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py in launch_instance(cls=<class 'ipykernel.kernelapp.IPKernelApp'>, argv=None, **kwargs={})
    653 
    654         If a global instance already exists, this reinitializes and starts it
    655         """
    656         app = cls.instance(**kwargs)
    657         app.initialize(argv)
--> 658         app.start()
        app.start = <bound method IPKernelApp.start of <ipykernel.kernelapp.IPKernelApp object>>
    659 
    660 #-----------------------------------------------------------------------------
    661 # utility functions, for convenience
    662 #-----------------------------------------------------------------------------

...........................................................................
/usr/local/lib/python3.4/dist-packages/ipykernel/kernelapp.py in start(self=<ipykernel.kernelapp.IPKernelApp object>)
    469             return self.subapp.start()
    470         if self.poller is not None:
    471             self.poller.start()
    472         self.kernel.start()
    473         try:
--> 474             ioloop.IOLoop.instance().start()
    475         except KeyboardInterrupt:
    476             pass
    477 
    478 launch_new_instance = IPKernelApp.launch_instance

...........................................................................
/usr/local/lib/python3.4/dist-packages/zmq/eventloop/ioloop.py in start(self=<zmq.eventloop.ioloop.ZMQIOLoop object>)
    172             )
    173         return loop
    174     
    175     def start(self):
    176         try:
--> 177             super(ZMQIOLoop, self).start()
        self.start = <bound method ZMQIOLoop.start of <zmq.eventloop.ioloop.ZMQIOLoop object>>
    178         except ZMQError as e:
    179             if e.errno == ETERM:
    180                 # quietly return on ETERM
    181                 pass

...........................................................................
/usr/local/lib/python3.4/dist-packages/tornado/ioloop.py in start(self=<zmq.eventloop.ioloop.ZMQIOLoop object>)
    882                 self._events.update(event_pairs)
    883                 while self._events:
    884                     fd, events = self._events.popitem()
    885                     try:
    886                         fd_obj, handler_func = self._handlers[fd]
--> 887                         handler_func(fd_obj, events)
        handler_func = <function wrap.<locals>.null_wrapper>
        fd_obj = <zmq.sugar.socket.Socket object>
        events = 1
    888                     except (OSError, IOError) as e:
    889                         if errno_from_exception(e) == errno.EPIPE:
    890                             # Happens when the client closes the connection
    891                             pass

...........................................................................
/usr/local/lib/python3.4/dist-packages/tornado/stack_context.py in null_wrapper(*args=(<zmq.sugar.socket.Socket object>, 1), **kwargs={})
    270         # Fast path when there are no active contexts.
    271         def null_wrapper(*args, **kwargs):
    272             try:
    273                 current_state = _state.contexts
    274                 _state.contexts = cap_contexts[0]
--> 275                 return fn(*args, **kwargs)
        args = (<zmq.sugar.socket.Socket object>, 1)
        kwargs = {}
    276             finally:
    277                 _state.contexts = current_state
    278         null_wrapper._wrapped = True
    279         return null_wrapper

...........................................................................
/usr/local/lib/python3.4/dist-packages/zmq/eventloop/zmqstream.py in _handle_events(self=<zmq.eventloop.zmqstream.ZMQStream object>, fd=<zmq.sugar.socket.Socket object>, events=1)
    435             # dispatch events:
    436             if events & IOLoop.ERROR:
    437                 gen_log.error("got POLLERR event on ZMQStream, which doesn't make sense")
    438                 return
    439             if events & IOLoop.READ:
--> 440                 self._handle_recv()
        self._handle_recv = <bound method ZMQStream._handle_recv of <zmq.eventloop.zmqstream.ZMQStream object>>
    441                 if not self.socket:
    442                     return
    443             if events & IOLoop.WRITE:
    444                 self._handle_send()

...........................................................................
/usr/local/lib/python3.4/dist-packages/zmq/eventloop/zmqstream.py in _handle_recv(self=<zmq.eventloop.zmqstream.ZMQStream object>)
    467                 gen_log.error("RECV Error: %s"%zmq.strerror(e.errno))
    468         else:
    469             if self._recv_callback:
    470                 callback = self._recv_callback
    471                 # self._recv_callback = None
--> 472                 self._run_callback(callback, msg)
        self._run_callback = <bound method ZMQStream._run_callback of <zmq.eventloop.zmqstream.ZMQStream object>>
        callback = <function wrap.<locals>.null_wrapper>
        msg = [<zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>]
    473                 
    474         # self.update_state()
    475         
    476 

...........................................................................
/usr/local/lib/python3.4/dist-packages/zmq/eventloop/zmqstream.py in _run_callback(self=<zmq.eventloop.zmqstream.ZMQStream object>, callback=<function wrap.<locals>.null_wrapper>, *args=([<zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>],), **kwargs={})
    409         close our socket."""
    410         try:
    411             # Use a NullContext to ensure that all StackContexts are run
    412             # inside our blanket exception handler rather than outside.
    413             with stack_context.NullContext():
--> 414                 callback(*args, **kwargs)
        callback = <function wrap.<locals>.null_wrapper>
        args = ([<zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>],)
        kwargs = {}
    415         except:
    416             gen_log.error("Uncaught exception, closing connection.",
    417                           exc_info=True)
    418             # Close the socket on an uncaught exception from a user callback

...........................................................................
/usr/local/lib/python3.4/dist-packages/tornado/stack_context.py in null_wrapper(*args=([<zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>],), **kwargs={})
    270         # Fast path when there are no active contexts.
    271         def null_wrapper(*args, **kwargs):
    272             try:
    273                 current_state = _state.contexts
    274                 _state.contexts = cap_contexts[0]
--> 275                 return fn(*args, **kwargs)
        args = ([<zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>],)
        kwargs = {}
    276             finally:
    277                 _state.contexts = current_state
    278         null_wrapper._wrapped = True
    279         return null_wrapper

...........................................................................
/usr/local/lib/python3.4/dist-packages/ipykernel/kernelbase.py in dispatcher(msg=[<zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>])
    271         if self.control_stream:
    272             self.control_stream.on_recv(self.dispatch_control, copy=False)
    273 
    274         def make_dispatcher(stream):
    275             def dispatcher(msg):
--> 276                 return self.dispatch_shell(stream, msg)
        msg = [<zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>, <zmq.sugar.frame.Frame object>]
    277             return dispatcher
    278 
    279         for s in self.shell_streams:
    280             s.on_recv(make_dispatcher(s), copy=False)

...........................................................................
/usr/local/lib/python3.4/dist-packages/ipykernel/kernelbase.py in dispatch_shell(self=<ipykernel.ipkernel.IPythonKernel object>, stream=<zmq.eventloop.zmqstream.ZMQStream object>, msg={'buffers': [], 'content': {'allow_stdin': True, 'code': 't_SSVRPolyCVModel = wrapper([ SVRPolyCVModel ])', 'silent': False, 'stop_on_error': True, 'store_history': True, 'user_expressions': {}}, 'header': {'date': '2017-04-13T13:07:12.575824', 'msg_id': '8069DC0C7415464699170FA3611AA748', 'msg_type': 'execute_request', 'session': '3F36D409A13B4E748DCD90ED0D6CD4FE', 'username': 'username', 'version': '5.0'}, 'metadata': {}, 'msg_id': '8069DC0C7415464699170FA3611AA748', 'msg_type': 'execute_request', 'parent_header': {}})
    223             self.log.error("UNKNOWN MESSAGE TYPE: %r", msg_type)
    224         else:
    225             self.log.debug("%s: %s", msg_type, msg)
    226             self.pre_handler_hook()
    227             try:
--> 228                 handler(stream, idents, msg)
        handler = <bound method IPythonKernel.execute_request of <ipykernel.ipkernel.IPythonKernel object>>
        stream = <zmq.eventloop.zmqstream.ZMQStream object>
        idents = [b'3F36D409A13B4E748DCD90ED0D6CD4FE']
        msg = {'buffers': [], 'content': {'allow_stdin': True, 'code': 't_SSVRPolyCVModel = wrapper([ SVRPolyCVModel ])', 'silent': False, 'stop_on_error': True, 'store_history': True, 'user_expressions': {}}, 'header': {'date': '2017-04-13T13:07:12.575824', 'msg_id': '8069DC0C7415464699170FA3611AA748', 'msg_type': 'execute_request', 'session': '3F36D409A13B4E748DCD90ED0D6CD4FE', 'username': 'username', 'version': '5.0'}, 'metadata': {}, 'msg_id': '8069DC0C7415464699170FA3611AA748', 'msg_type': 'execute_request', 'parent_header': {}}
    229             except Exception:
    230                 self.log.error("Exception in message handler:", exc_info=True)
    231             finally:
    232                 self.post_handler_hook()

...........................................................................
/usr/local/lib/python3.4/dist-packages/ipykernel/kernelbase.py in execute_request(self=<ipykernel.ipkernel.IPythonKernel object>, stream=<zmq.eventloop.zmqstream.ZMQStream object>, ident=[b'3F36D409A13B4E748DCD90ED0D6CD4FE'], parent={'buffers': [], 'content': {'allow_stdin': True, 'code': 't_SSVRPolyCVModel = wrapper([ SVRPolyCVModel ])', 'silent': False, 'stop_on_error': True, 'store_history': True, 'user_expressions': {}}, 'header': {'date': '2017-04-13T13:07:12.575824', 'msg_id': '8069DC0C7415464699170FA3611AA748', 'msg_type': 'execute_request', 'session': '3F36D409A13B4E748DCD90ED0D6CD4FE', 'username': 'username', 'version': '5.0'}, 'metadata': {}, 'msg_id': '8069DC0C7415464699170FA3611AA748', 'msg_type': 'execute_request', 'parent_header': {}})
    385         if not silent:
    386             self.execution_count += 1
    387             self._publish_execute_input(code, parent, self.execution_count)
    388 
    389         reply_content = self.do_execute(code, silent, store_history,
--> 390                                         user_expressions, allow_stdin)
        user_expressions = {}
        allow_stdin = True
    391 
    392         # Flush output before sending the reply.
    393         sys.stdout.flush()
    394         sys.stderr.flush()

...........................................................................
/usr/local/lib/python3.4/dist-packages/ipykernel/ipkernel.py in do_execute(self=<ipykernel.ipkernel.IPythonKernel object>, code='t_SSVRPolyCVModel = wrapper([ SVRPolyCVModel ])', silent=False, store_history=True, user_expressions={}, allow_stdin=True)
    191 
    192         self._forward_input(allow_stdin)
    193 
    194         reply_content = {}
    195         try:
--> 196             res = shell.run_cell(code, store_history=store_history, silent=silent)
        res = undefined
        shell.run_cell = <bound method ZMQInteractiveShell.run_cell of <ipykernel.zmqshell.ZMQInteractiveShell object>>
        code = 't_SSVRPolyCVModel = wrapper([ SVRPolyCVModel ])'
        store_history = True
        silent = False
    197         finally:
    198             self._restore_input()
    199 
    200         if res.error_before_exec is not None:

...........................................................................
/usr/local/lib/python3.4/dist-packages/ipykernel/zmqshell.py in run_cell(self=<ipykernel.zmqshell.ZMQInteractiveShell object>, *args=('t_SSVRPolyCVModel = wrapper([ SVRPolyCVModel ])',), **kwargs={'silent': False, 'store_history': True})
    496             )
    497         self.payload_manager.write_payload(payload)
    498 
    499     def run_cell(self, *args, **kwargs):
    500         self._last_traceback = None
--> 501         return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
        self.run_cell = <bound method ZMQInteractiveShell.run_cell of <ipykernel.zmqshell.ZMQInteractiveShell object>>
        args = ('t_SSVRPolyCVModel = wrapper([ SVRPolyCVModel ])',)
        kwargs = {'silent': False, 'store_history': True}
    502 
    503     def _showtraceback(self, etype, evalue, stb):
    504         # try to preserve ordering of tracebacks and print statements
    505         sys.stdout.flush()

...........................................................................
/usr/local/lib/python3.4/dist-packages/IPython/core/interactiveshell.py in run_cell(self=<ipykernel.zmqshell.ZMQInteractiveShell object>, raw_cell='t_SSVRPolyCVModel = wrapper([ SVRPolyCVModel ])', store_history=True, silent=False, shell_futures=True)
   2712                 self.displayhook.exec_result = result
   2713 
   2714                 # Execute the user code
   2715                 interactivity = "none" if silent else self.ast_node_interactivity
   2716                 has_raised = self.run_ast_nodes(code_ast.body, cell_name,
-> 2717                    interactivity=interactivity, compiler=compiler, result=result)
        interactivity = 'last_expr'
        compiler = <IPython.core.compilerop.CachingCompiler object>
   2718                 
   2719                 self.last_execution_succeeded = not has_raised
   2720 
   2721                 # Reset this so later displayed values do not modify the

...........................................................................
/usr/local/lib/python3.4/dist-packages/IPython/core/interactiveshell.py in run_ast_nodes(self=<ipykernel.zmqshell.ZMQInteractiveShell object>, nodelist=[<_ast.Assign object>], cell_name='<ipython-input-5-4ea39000c626>', interactivity='none', compiler=<IPython.core.compilerop.CachingCompiler object>, result=<ExecutionResult object at 7f8eb056a780, executi..._before_exec=None error_in_exec=None result=None>)
   2816 
   2817         try:
   2818             for i, node in enumerate(to_run_exec):
   2819                 mod = ast.Module([node])
   2820                 code = compiler(mod, cell_name, "exec")
-> 2821                 if self.run_code(code, result):
        self.run_code = <bound method ZMQInteractiveShell.run_code of <ipykernel.zmqshell.ZMQInteractiveShell object>>
        code = <code object <module> at 0x7f8eb4a81c00, file "<ipython-input-5-4ea39000c626>", line 1>
        result = <ExecutionResult object at 7f8eb056a780, executi..._before_exec=None error_in_exec=None result=None>
   2822                     return True
   2823 
   2824             for i, node in enumerate(to_run_interactive):
   2825                 mod = ast.Interactive([node])

...........................................................................
/usr/local/lib/python3.4/dist-packages/IPython/core/interactiveshell.py in run_code(self=<ipykernel.zmqshell.ZMQInteractiveShell object>, code_obj=<code object <module> at 0x7f8eb4a81c00, file "<ipython-input-5-4ea39000c626>", line 1>, result=<ExecutionResult object at 7f8eb056a780, executi..._before_exec=None error_in_exec=None result=None>)
   2876         outflag = 1  # happens in more places, so it's easier as default
   2877         try:
   2878             try:
   2879                 self.hooks.pre_run_code_hook()
   2880                 #rprint('Running code', repr(code_obj)) # dbg
-> 2881                 exec(code_obj, self.user_global_ns, self.user_ns)
        code_obj = <code object <module> at 0x7f8eb4a81c00, file "<ipython-input-5-4ea39000c626>", line 1>
        self.user_global_ns = {'ElasticNetCVModel': <function ElasticNetCVModel>, 'GradientBoostingCVModel': <function GradientBoostingCVModel>, 'In': ['', 't_SSVRPolyCVModel = wrapper([ SVRPolyCVModel ])', '# import all the filenames\nfrom allfunctions import *', "get_ipython().magic('load_ext autoreload')\nget_ipython().magic('autoreload 2')", 'def wrapper(functionList = []):\n    if __name__ ...ename] = out[filename]\n    return model_selection', 't_SSVRPolyCVModel = wrapper([ SVRPolyCVModel ])'], 'LassoCVModel': <function LassoCVModel>, 'OMPCVModel': <function OMPCVModel>, 'Out': {}, 'RandomForestCVModel': <function RandomForestCVModel>, 'RidgeCVModel': <function RidgeCVModel>, 'SVRLinearCVModel': <function SVRLinearCVModel>, 'SVRPolyCVModel': <function SVRPolyCVModel>, ...}
        self.user_ns = {'ElasticNetCVModel': <function ElasticNetCVModel>, 'GradientBoostingCVModel': <function GradientBoostingCVModel>, 'In': ['', 't_SSVRPolyCVModel = wrapper([ SVRPolyCVModel ])', '# import all the filenames\nfrom allfunctions import *', "get_ipython().magic('load_ext autoreload')\nget_ipython().magic('autoreload 2')", 'def wrapper(functionList = []):\n    if __name__ ...ename] = out[filename]\n    return model_selection', 't_SSVRPolyCVModel = wrapper([ SVRPolyCVModel ])'], 'LassoCVModel': <function LassoCVModel>, 'OMPCVModel': <function OMPCVModel>, 'Out': {}, 'RandomForestCVModel': <function RandomForestCVModel>, 'RidgeCVModel': <function RidgeCVModel>, 'SVRLinearCVModel': <function SVRLinearCVModel>, 'SVRPolyCVModel': <function SVRPolyCVModel>, ...}
   2882             finally:
   2883                 # Reset our crash handler in place
   2884                 sys.excepthook = old_excepthook
   2885         except SystemExit as e:

...........................................................................
/data/home/a1singh/IPPD/IPPD/workbench/<ipython-input-5-4ea39000c626> in <module>()
----> 1 
      2 
      3 
      4 
      5 
      6 t_SSVRPolyCVModel = wrapper([ SVRPolyCVModel ])
      7 
      8 
      9 
     10 

...........................................................................
/data/home/a1singh/IPPD/IPPD/workbench/<ipython-input-4-d05adcac5aa0> in wrapper(functionList=[<function SVRPolyCVModel>])
      9         
     10         for f in functionList:
     11             print()
     12             for filename in filenames:
     13                 print('function = %s, filename = %s' % (f,filename))
---> 14                 out = f(filename)
     15                 newScore = out[filename]['train_rmse_cv_picking']
     16 
     17                 if filename in model_selection:
     18                     #compare scores and select more accurate model

...........................................................................
/data/home/a1singh/IPPD/IPPD/workbench/allfunctions.py in SVRPolyCVModel(filename='ABC.pickle', scale=False)
    660                        cv=3, 
    661                        n_jobs=-1, 
    662                        scoring=rmse_scorer)
    663     print('Starting grdsurch.fit(X_train, y_train)')
    664     
--> 665     grdsurch.fit(X_train, y_train)
        grdsurch.fit = <bound method GridSearchCV.fit of GridSearchCV(c...ction rmse_scorer at 0x7f8eb5614a60>, verbose=0)>
        X_train =       ppn     sizeGB     ft1     ft2     ft3   f...  1445.0   0.0   681.0  

[224 rows x 57 columns]
        y_train = array([   98.42,  2294.56,  2087.18,  3357.03,  ...,   322.27,  3085.44,
        2543.24,  2746.73])
    666 
    667     print("\nBest parameters set found on development set:")
    668     print()
    669     print(grdsurch.best_params_)

...........................................................................
/usr/local/lib/python3.4/dist-packages/sklearn/model_selection/_search.py in fit(self=GridSearchCV(cv=3, error_score='raise',
       e...nction rmse_scorer at 0x7f8eb5614a60>, verbose=0), X=      ppn     sizeGB     ft1     ft2     ft3   f...  1445.0   0.0   681.0  

[224 rows x 57 columns], y=array([   98.42,  2294.56,  2087.18,  3357.03,  ...,   322.27,  3085.44,
        2543.24,  2746.73]), groups=None)
    940 
    941         groups : array-like, with shape (n_samples,), optional
    942             Group labels for the samples used while splitting the dataset into
    943             train/test set.
    944         """
--> 945         return self._fit(X, y, groups, ParameterGrid(self.param_grid))
        self._fit = <bound method GridSearchCV._fit of GridSearchCV(...ction rmse_scorer at 0x7f8eb5614a60>, verbose=0)>
        X =       ppn     sizeGB     ft1     ft2     ft3   f...  1445.0   0.0   681.0  

[224 rows x 57 columns]
        y = array([   98.42,  2294.56,  2087.18,  3357.03,  ...,   322.27,  3085.44,
        2543.24,  2746.73])
        groups = None
        self.param_grid = [{'C': array([  1.00000000e-05,   1.00000000e+15]), 'degree': [6], 'gamma': array([  1.00000000e-15,   1.00000000e+03])}]
    946 
    947 
    948 class RandomizedSearchCV(BaseSearchCV):
    949     """Randomized search on hyper parameters.

...........................................................................
/usr/local/lib/python3.4/dist-packages/sklearn/model_selection/_search.py in _fit(self=GridSearchCV(cv=3, error_score='raise',
       e...nction rmse_scorer at 0x7f8eb5614a60>, verbose=0), X=      ppn     sizeGB     ft1     ft2     ft3   f...  1445.0   0.0   681.0  

[224 rows x 57 columns], y=array([   98.42,  2294.56,  2087.18,  3357.03,  ...,   322.27,  3085.44,
        2543.24,  2746.73]), groups=None, parameter_iterable=<sklearn.model_selection._search.ParameterGrid object>)
    559                                   fit_params=self.fit_params,
    560                                   return_train_score=self.return_train_score,
    561                                   return_n_test_samples=True,
    562                                   return_times=True, return_parameters=True,
    563                                   error_score=self.error_score)
--> 564           for parameters in parameter_iterable
        parameters = undefined
        parameter_iterable = <sklearn.model_selection._search.ParameterGrid object>
    565           for train, test in cv_iter)
    566 
    567         # if one choose to see train score, "out" will contain train score info
    568         if self.return_train_score:

...........................................................................
/usr/local/lib/python3.4/dist-packages/sklearn/externals/joblib/parallel.py in __call__(self=Parallel(n_jobs=-1), iterable=<generator object <genexpr>>)
    763             if pre_dispatch == "all" or n_jobs == 1:
    764                 # The iterable was consumed all at once by the above for loop.
    765                 # No need to wait for async callbacks to trigger to
    766                 # consumption.
    767                 self._iterating = False
--> 768             self.retrieve()
        self.retrieve = <bound method Parallel.retrieve of Parallel(n_jobs=-1)>
    769             # Make sure that we get a last message telling us we are done
    770             elapsed_time = time.time() - self._start_time
    771             self._print('Done %3i out of %3i | elapsed: %s finished',
    772                         (len(self._output), len(self._output),

---------------------------------------------------------------------------
Sub-process traceback:
---------------------------------------------------------------------------
ValueError                                         Thu Apr 13 13:07:13 2017
PID: 13489                                   Python 3.4.3: /usr/bin/python3
...........................................................................
/usr/local/lib/python3.4/dist-packages/sklearn/externals/joblib/parallel.py in __call__(self=<sklearn.externals.joblib.parallel.BatchedCalls object>)
    126     def __init__(self, iterator_slice):
    127         self.items = list(iterator_slice)
    128         self._size = len(self.items)
    129 
    130     def __call__(self):
--> 131         return [func(*args, **kwargs) for func, args, kwargs in self.items]
        self.items = [(<function _fit_and_score>, (SVR(C=1.0000000000000001e-05, cache_size=20480, ...00.0,
  shrinking=False, tol=0.01, verbose=False),       ppn     sizeGB     ft1     ft2     ft3   f...  1445.0   0.0   681.0  

[224 rows x 57 columns], array([   98.42,  2294.56,  2087.18,  3357.03,  ...,   322.27,  3085.44,
        2543.24,  2746.73]), <function rmse_scorer>, array([ 75,  76,  77,  78,  79,  80,  81,  82,  ..., 216, 217,
       218, 219, 220, 221, 222, 223]), array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 1..., 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74]), 0, {'C': 1.0000000000000001e-05, 'degree': 6, 'gamma': 1000.0}), {'error_score': 'raise', 'fit_params': {}, 'return_n_test_samples': True, 'return_parameters': True, 'return_times': True, 'return_train_score': True})]
    132 
    133     def __len__(self):
    134         return self._size
    135 

...........................................................................
/usr/local/lib/python3.4/dist-packages/sklearn/externals/joblib/parallel.py in <listcomp>(.0=<list_iterator object>)
    126     def __init__(self, iterator_slice):
    127         self.items = list(iterator_slice)
    128         self._size = len(self.items)
    129 
    130     def __call__(self):
--> 131         return [func(*args, **kwargs) for func, args, kwargs in self.items]
        func = <function _fit_and_score>
        args = (SVR(C=1.0000000000000001e-05, cache_size=20480, ...00.0,
  shrinking=False, tol=0.01, verbose=False),       ppn     sizeGB     ft1     ft2     ft3   f...  1445.0   0.0   681.0  

[224 rows x 57 columns], array([   98.42,  2294.56,  2087.18,  3357.03,  ...,   322.27,  3085.44,
        2543.24,  2746.73]), <function rmse_scorer>, array([ 75,  76,  77,  78,  79,  80,  81,  82,  ..., 216, 217,
       218, 219, 220, 221, 222, 223]), array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 1..., 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74]), 0, {'C': 1.0000000000000001e-05, 'degree': 6, 'gamma': 1000.0})
        kwargs = {'error_score': 'raise', 'fit_params': {}, 'return_n_test_samples': True, 'return_parameters': True, 'return_times': True, 'return_train_score': True}
    132 
    133     def __len__(self):
    134         return self._size
    135 

...........................................................................
/usr/local/lib/python3.4/dist-packages/sklearn/model_selection/_validation.py in _fit_and_score(estimator=SVR(C=1.0000000000000001e-05, cache_size=20480, ...00.0,
  shrinking=False, tol=0.01, verbose=False), X=      ppn     sizeGB     ft1     ft2     ft3   f...  1445.0   0.0   681.0  

[224 rows x 57 columns], y=array([   98.42,  2294.56,  2087.18,  3357.03,  ...,   322.27,  3085.44,
        2543.24,  2746.73]), scorer=<function rmse_scorer>, train=array([ 75,  76,  77,  78,  79,  80,  81,  82,  ..., 216, 217,
       218, 219, 220, 221, 222, 223]), test=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 1..., 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74]), verbose=0, parameters={'C': 1.0000000000000001e-05, 'degree': 6, 'gamma': 1000.0}, fit_params={}, return_train_score=True, return_parameters=True, return_n_test_samples=True, return_times=True, error_score='raise')
    255                              " numeric value. (Hint: if using 'raise', please"
    256                              " make sure that it has been spelled correctly.)")
    257 
    258     else:
    259         fit_time = time.time() - start_time
--> 260         test_score = _score(estimator, X_test, y_test, scorer)
        test_score = undefined
        estimator = SVR(C=1.0000000000000001e-05, cache_size=20480, ...00.0,
  shrinking=False, tol=0.01, verbose=False)
        X_test =       ppn     sizeGB     ft1     ft2     ft3   f...3  6132.0  67.0  2616.0  

[75 rows x 57 columns]
        y_test = array([   98.42,  2294.56,  2087.18,  3357.03,  ...,  1620.72,
         697.69,  2607.84,  1466.25])
        scorer = <function rmse_scorer>
    261         score_time = time.time() - start_time - fit_time
    262         if return_train_score:
    263             train_score = _score(estimator, X_train, y_train, scorer)
    264 

...........................................................................
/usr/local/lib/python3.4/dist-packages/sklearn/model_selection/_validation.py in _score(estimator=SVR(C=1.0000000000000001e-05, cache_size=20480, ...00.0,
  shrinking=False, tol=0.01, verbose=False), X_test=      ppn     sizeGB     ft1     ft2     ft3   f...3  6132.0  67.0  2616.0  

[75 rows x 57 columns], y_test=array([   98.42,  2294.56,  2087.18,  3357.03,  ...,  1620.72,
         697.69,  2607.84,  1466.25]), scorer=<function rmse_scorer>)
    283 def _score(estimator, X_test, y_test, scorer):
    284     """Compute the score of an estimator on a given test set."""
    285     if y_test is None:
    286         score = scorer(estimator, X_test)
    287     else:
--> 288         score = scorer(estimator, X_test, y_test)
        score = undefined
        scorer = <function rmse_scorer>
        estimator = SVR(C=1.0000000000000001e-05, cache_size=20480, ...00.0,
  shrinking=False, tol=0.01, verbose=False)
        X_test =       ppn     sizeGB     ft1     ft2     ft3   f...3  6132.0  67.0  2616.0  

[75 rows x 57 columns]
        y_test = array([   98.42,  2294.56,  2087.18,  3357.03,  ...,  1620.72,
         697.69,  2607.84,  1466.25])
    289     if hasattr(score, 'item'):
    290         try:
    291             # e.g. unwrap memmapped scalars
    292             score = score.item()

...........................................................................
/data/home/a1singh/IPPD/IPPD/workbench/allfunctions.py in rmse_scorer(model=SVR(C=1.0000000000000001e-05, cache_size=20480, ...00.0,
  shrinking=False, tol=0.01, verbose=False), X=      ppn     sizeGB     ft1     ft2     ft3   f...3  6132.0  67.0  2616.0  

[75 rows x 57 columns], y=array([   98.42,  2294.56,  2087.18,  3357.03,  ...,  1620.72,
         697.69,  2607.84,  1466.25]))
     24 c = 0
     25 
     26 def rmse_scorer(model, X, y):
     27     global c
     28     y_predict = model.predict(X)
---> 29     k = np.sqrt(mean_squared_error(y, y_predict))
        k = undefined
        y = array([   98.42,  2294.56,  2087.18,  3357.03,  ...,  1620.72,
         697.69,  2607.84,  1466.25])
        y_predict = array([ nan,  nan,  nan,  nan,  nan,  nan,  nan,...  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan])
     30     c = c+1
     31     return k
     32 
     33 

...........................................................................
/usr/local/lib/python3.4/dist-packages/sklearn/metrics/regression.py in mean_squared_error(y_true=array([   98.42,  2294.56,  2087.18,  3357.03,  ...,  1620.72,
         697.69,  2607.84,  1466.25]), y_pred=array([ nan,  nan,  nan,  nan,  nan,  nan,  nan,...  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan]), sample_weight=None, multioutput='uniform_average')
    226     ... # doctest: +ELLIPSIS
    227     0.824...
    228 
    229     """
    230     y_type, y_true, y_pred, multioutput = _check_reg_targets(
--> 231         y_true, y_pred, multioutput)
        y_true = array([   98.42,  2294.56,  2087.18,  3357.03,  ...,  1620.72,
         697.69,  2607.84,  1466.25])
        y_pred = array([ nan,  nan,  nan,  nan,  nan,  nan,  nan,...  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan])
        multioutput = 'uniform_average'
    232     output_errors = np.average((y_true - y_pred) ** 2, axis=0,
    233                                weights=sample_weight)
    234     if isinstance(multioutput, string_types):
    235         if multioutput == 'raw_values':

...........................................................................
/usr/local/lib/python3.4/dist-packages/sklearn/metrics/regression.py in _check_reg_targets(y_true=array([   98.42,  2294.56,  2087.18,  3357.03,  ...,  1620.72,
         697.69,  2607.84,  1466.25]), y_pred=array([ nan,  nan,  nan,  nan,  nan,  nan,  nan,...  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan]), multioutput='uniform_average')
     71         correct keyword.
     72 
     73     """
     74     check_consistent_length(y_true, y_pred)
     75     y_true = check_array(y_true, ensure_2d=False)
---> 76     y_pred = check_array(y_pred, ensure_2d=False)
        y_pred = array([ nan,  nan,  nan,  nan,  nan,  nan,  nan,...  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan])
     77 
     78     if y_true.ndim == 1:
     79         y_true = y_true.reshape((-1, 1))
     80 

...........................................................................
/usr/local/lib/python3.4/dist-packages/sklearn/utils/validation.py in check_array(array=array([ nan,  nan,  nan,  nan,  nan,  nan,  nan,...  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan]), accept_sparse=None, dtype=None, order=None, copy=False, force_all_finite=True, ensure_2d=False, allow_nd=False, ensure_min_samples=1, ensure_min_features=1, warn_on_dtype=False, estimator=None)
    402             array = array.astype(np.float64)
    403         if not allow_nd and array.ndim >= 3:
    404             raise ValueError("Found array with dim %d. %s expected <= 2."
    405                              % (array.ndim, estimator_name))
    406         if force_all_finite:
--> 407             _assert_all_finite(array)
        array = array([ nan,  nan,  nan,  nan,  nan,  nan,  nan,...  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan])
    408 
    409     shape_repr = _shape_repr(array.shape)
    410     if ensure_min_samples > 0:
    411         n_samples = _num_samples(array)

...........................................................................
/usr/local/lib/python3.4/dist-packages/sklearn/utils/validation.py in _assert_all_finite(X=array([ nan,  nan,  nan,  nan,  nan,  nan,  nan,...  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan]))
     53     # everything is finite; fall back to O(n) space np.isfinite to prevent
     54     # false positives from overflow in sum method.
     55     if (X.dtype.char in np.typecodes['AllFloat'] and not np.isfinite(X.sum())
     56             and not np.isfinite(X).all()):
     57         raise ValueError("Input contains NaN, infinity"
---> 58                          " or a value too large for %r." % X.dtype)
        X.dtype = dtype('float64')
     59 
     60 
     61 def assert_all_finite(X):
     62     """Throw a ValueError if X contains NaN or infinity.

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
___________________________________________________________________________

# Sigmoid Kernel

In [ ]:
t_SVRSigmoidCVModel = wrapper([ SVRSigmoidCVModel ])

In [ ]:
t_print = t_SVRSigmoidCVModel

for key in t_print.keys():
    print(80*'_')
    print(key)    

    print('Model: %s' % (str(t_print[key]['model'])[:20]))
    print('Train RMSE: %f \n' % (t_print[key]['train_rmse_cv_picking']))

    #print('Test RMSE   : %f' % (t_print[key]['test_rmse_reporting']))
    #print('Overall Mean: %f \n' % (t_print[key]['test_mean_y_comparing']))

    if(not t_print[key]['test_rmse_reportingA']==None):
        print('A...TestA RMSE   : %f' % float(t_print[key]['test_rmse_reportingA'] or -1))
        print('A...<<y_test_A Mean>>: %f \n' % float(t_print[key]['test_mean_y_comparingA'] or -1))

    if(not t_print[key]['test_rmse_reportingB']==None):
        print('B...TestB RMSE   : %f' % float(t_print[key]['test_rmse_reportingB'] or -1))
        print('B...<<y_test_B Mean>>: %f \n' % float(t_print[key]['test_mean_y_comparingB'] or -1))

    if(not t_print[key]['test_rmse_reportingC']==None):
        print('C...TestC RMSE   : %f' % float(t_print[key]['test_rmse_reportingC'] or -1))
        print('C...<<y_test_C Mean>>: %f \n' % float(t_print[key]['test_mean_y_comparingC'] or -1))

    if(not t_print[key]['test_rmse_reportingD']==None):
        print('D...TestD RMSE   : %f' % float(t_print[key]['test_rmse_reportingD'] or -1))
        print('D...<<y_test_D Mean>>: %f' % float(t_print[key]['test_mean_y_comparingD'] or -1))

    print(80*'_')

In [ ]:
# write the model
import pickle

#||||||||||||||||||| 
t_ = t_SVRSigmoidCVModel
prefix = '4C3_' + 'SVRSigmoidCVModel'
#||||||||||||||||||| 

for k in t_.keys():
    mo   = t_[k]['model']
    fname = prefix + '_tuned_' + str(k[:3]) + '.pickle'
    
    print()
    print(k, str(mo)[:30])
    
    print(fname)
    # write the model to a file
    with open(fname, 'wb') as handle:
        pickle.dump(mo, handle)

# Which features were given most weights by each model ?