In [1]:
# import all the filenames
from allfunctions import *

In [2]:
%load_ext autoreload
%autoreload 2

1  def LassoCVModel(filename):

3  def RidgeCVModel(filename):

4  def ElasticNetCVModel(filename):

In [3]:
def wrapper(functionList = [], filenames = [ 'datasetIPPD.pickle' ]):
    if __name__ == '__main__':
        global model_selection
        
                
        model_selection = {}
        
        for f in functionList:
            print()
            for filename in filenames:
                out = f(filename)
                newScore = out[filename]['train_rmse_cv_picking']

                if f in model_selection:
                    #compare scores and select more accurate model
                    oldScore = model_selection[f]['train_rmse_cv_picking']
                    if(newScore < oldScore):
                        print("【【【】】】switching models for %s..." % filename)
                        print("【【【】】】newScore: %f < oldScore: %f" % (newScore, oldScore))
                        print("【【【】】】newModel: %s \n" % f)
                        print(100*'_')
                        model_selection[f] = out[filename]
                else:
                    #no score to compare
                    print("【【】】adding new model for %s \n" % filename)
                    print("【【【】】】newScore: %f " % (newScore))
                    print(100*'_')
                    model_selection[f] = out[filename]
    return model_selection

<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:><:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>
<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:><:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>
<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:><:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>
<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:><:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:


# 1

# LassoCVModel

In [4]:
########################### Test Lasso with Scaling ###########################
# the L1 and L2 regularizers of linear models) assume that all features are 
# centered around 0 and have variance in the same order

In [5]:
t_lasso = wrapper([LassoCVModel])



{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}

Dataset size read: train 258 and test 63 

# Tuning hyper-parameters 
[{'precompute': [True, False], 'alpha': array([  1.00000000e-04,   1.93069773e-04,   3.72759372e-04,
         7.19685673e-04,   1.38949549e-03,   2.68269580e-03,
         5.17947468e-03,   1.00000000e-02,   1.93069773e-02,
         3.72759372e-02,   7.19685673e-02,   1.38949549e-01,
         2.68269580e-01,   5.17947468e-01,   1.00000000e+00,
         1.93069773e+00,   3.72759372e+00,   7.19685673e+00,
         1.38949549e+01,   2.68269580e+01,   5.17947468e+01,
         1.00000000e+02,   1.93069773e+02,   3.72759372e+02,
         7.19685673e+02,   1.38949549e+03,   2.68269580e+03,
         5.17947468e+03,   1.00000000e+04,   1.93069773e+04,
         3.72759372e+04,   7.19685673e+04,   1.38949549e+05,
         2.68269580e+05,   5.17947468e+05,   1.00000000e+06,
         1.93069773e+06,   3.72759372e+06,   7.19685673e+06,
    

array([  173.64,    45.97,   141.66,   164.88,    67.96,    98.47,
        3309.8 ,  2896.76,  3359.25,  1861.97,  3344.01,  3371.75,
        2855.36,  1423.13,  1721.38,  1323.62,  2396.68,  2472.15,
        3028.27,  2877.71,  2024.25,  2314.1 ,  1174.9 ,  1723.63,
        3348.91,  2683.3 ,  1873.73,  2684.27,  2083.07,   998.65,
         976.5 ,  1868.49,  1076.1 ,  1073.56,  3326.93,  2265.29,
         644.52,   298.64,  3059.32,  1083.5 ,  1001.19,   322.13,
        2543.24,   692.62,  2478.78,   198.71,  1031.47,  2457.56,
        1801.74,   216.12,  1925.99,  2125.54,  2239.73,   747.33,
         810.75,   462.77,  2106.02,   218.82,  1634.05,  1802.26,
        1332.56,  2142.12,   462.06])

array([  738.54056959,  -487.41455819,   522.83282927,   715.44811953,
        -216.66019193,    45.23244851,  2315.03920863,  2337.69440249,
        2338.13165869,  2313.90234249,  2384.31655881,  2338.13165869,
        2383.87930261,  2336.52263556,  2359.8540393 ,  2313.4301855 ,
        2314.36874912,  2383.64609929,  2314.80600532,  2383.87930261,
        2383.17969267,  2337.22799586,  2361.22410875,  2382.94648936,
        2361.22410875,  2576.94277196,  1853.78462708,  2623.12767208,
        2264.92738651,  1100.7764584 ,  1054.59155828,  1876.87707714,
        1031.49910822,  1031.49910822,  2988.08553139,  2195.65003633,
         695.60370374,   333.63084681,  2964.99308133,  1054.59155828,
        1031.49910822,   333.63084681,  2195.65003633,   718.6961538 ,
        2108.41940197,   385.03628972,  1176.31109051,  2108.41940197,
        1584.63412109,   431.22118984,  1892.71166165,  1823.43431147,
        2085.32695191,   937.51090013,   937.51090013,   666.17352559,
      

A: 6

{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}



array([ 173.64,   45.97,  141.66,  164.88,   67.96,   98.47])

array([ 738.54056959, -487.41455819,  522.83282927,  715.44811953,
       -216.66019193,   45.23244851])

B: 19

{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}



array([ 3309.8 ,  2896.76,  3359.25,  1861.97,  3344.01,  3371.75,
        2855.36,  1423.13,  1721.38,  1323.62,  2396.68,  2472.15,
        3028.27,  2877.71,  2024.25,  2314.1 ,  1174.9 ,  1723.63,  3348.91])

array([ 2315.03920863,  2337.69440249,  2338.13165869,  2313.90234249,
        2384.31655881,  2338.13165869,  2383.87930261,  2336.52263556,
        2359.8540393 ,  2313.4301855 ,  2314.36874912,  2383.64609929,
        2314.80600532,  2383.87930261,  2383.17969267,  2337.22799586,
        2361.22410875,  2382.94648936,  2361.22410875])

C: 19

{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}



array([ 2683.3 ,  1873.73,  2684.27,  2083.07,   998.65,   976.5 ,
        1868.49,  1076.1 ,  1073.56,  3326.93,  2265.29,   644.52,
         298.64,  3059.32,  1083.5 ,  1001.19,   322.13,  2543.24,   692.62])

array([ 2576.94277196,  1853.78462708,  2623.12767208,  2264.92738651,
        1100.7764584 ,  1054.59155828,  1876.87707714,  1031.49910822,
        1031.49910822,  2988.08553139,  2195.65003633,   695.60370374,
         333.63084681,  2964.99308133,  1054.59155828,  1031.49910822,
         333.63084681,  2195.65003633,   718.6961538 ])

D: 19

{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}



array([ 2478.78,   198.71,  1031.47,  2457.56,  1801.74,   216.12,
        1925.99,  2125.54,  2239.73,   747.33,   810.75,   462.77,
        2106.02,   218.82,  1634.05,  1802.26,  1332.56,  2142.12,   462.06])

array([ 2108.41940197,   385.03628972,  1176.31109051,  2108.41940197,
        1584.63412109,   431.22118984,  1892.71166165,  1823.43431147,
        2085.32695191,   937.51090013,   937.51090013,   666.17352559,
        1869.61921159,   454.3136399 ,  1584.63412109,  1653.91147127,
        1392.01883083,  1846.52676153,   619.98862547])

【【】】adding new model for datasetIPPD.pickle 

【【【】】】newScore: 1716.241252 
____________________________________________________________________________________________________


In [6]:
t_print = t_lasso

for key in t_print.keys():
    print(80*'_')
    
    print('Model: %s' % (str(t_print[key]['model'])[:20]))
    print('Train RMSE: %f \n' % (t_print[key]['train_rmse_cv_picking']))
    
    #print('Test RMSE   : %f' % (t_print[key]['test_rmse_reporting']))
    #print('Overall Test Mean: %f \n' % (t_print[key]['test_mean_y_comparing']))
    
    print('A...TestA RMSE   : %f' % (t_print[key]['test_rmse_reportingA']))
    print('A...<<y_test_A Mean>>: %f \n' % (t_print[key]['test_mean_y_comparingA']))
    
    print('B...TestB RMSE   : %f' % (t_print[key]['test_rmse_reportingB']))
    print('B...<<y_test_B Mean>>: %f \n' % (t_print[key]['test_mean_y_comparingB']))
    
    print('C...TestC RMSE   : %f' % (t_print[key]['test_rmse_reportingC']))
    print('C...<<y_test_C Mean>>: %f \n' % (t_print[key]['test_mean_y_comparingC']))
    
    print('D...TestD RMSE   : %f' % (t_print[key]['test_rmse_reportingD']))
    print('D...<<y_test_D Mean>>: %f' % (t_print[key]['test_mean_y_comparingD']))
    
    print(80*'_')

________________________________________________________________________________
Model: Lasso(alpha=0.019306
Train RMSE: 1716.241252 

A...TestA RMSE   : 435.100106
A...<<y_test_A Mean>>: 115.430000 

B...TestB RMSE   : 750.326960
B...<<y_test_B Mean>>: 2464.612105 

C...TestC RMSE   : 130.718481
C...<<y_test_C Mean>>: 1608.160526 

D...TestD RMSE   : 213.939945
D...<<y_test_D Mean>>: 1378.651579
________________________________________________________________________________


In [7]:
def write_model_4c4(model_name, model_string):
    # write the model
    import pickle

    #||||||||||||||||||| 
    t_ = model_name
    prefix = '4C4_' + model_string
    #||||||||||||||||||| 

    for k in t_.keys():
        mo   = t_[k]['model']
        fname = prefix + '_tuned_ABCD' + '.pickle'
           
        print(fname)
        # write the model to a file
        with open(fname, 'wb') as handle:
            pickle.dump(mo, handle)

In [8]:
write_model_4c4(t_lasso, 'lasso')

4C4_lasso_tuned_ABCD.pickle


<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:><:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>
<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:><:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>
<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:><:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>
<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:><:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>


# RidgeModel

In [9]:
########################### Test Ridge with Scaling ###########################
# the L1 and L2 regularizers of linear models) assume that all features are 
# centered around 0 and have variance in the same order

In [10]:
# Note: Scaling improves Ridge

In [11]:
t_ridge = wrapper([RidgeCVModel])



{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}

Dataset size read: train 258 and test 63 

# Tuning hyper-parameters 
[{'alpha': array([  1.00000000e-35,   4.03701726e-35,   1.62975083e-34,
         6.57933225e-34,   2.65608778e-33,   1.07226722e-32,
         4.32876128e-32,   1.74752840e-31,   7.05480231e-31,
         2.84803587e-30,   1.14975700e-29,   4.64158883e-29,
         1.87381742e-28,   7.56463328e-28,   3.05385551e-27,
         1.23284674e-26,   4.97702356e-26,   2.00923300e-25,
         8.11130831e-25,   3.27454916e-24,   1.32194115e-23,
         5.33669923e-23,   2.15443469e-22,   8.69749003e-22,
         3.51119173e-21,   1.41747416e-20,   5.72236766e-20,
         2.31012970e-19,   9.32603347e-19,   3.76493581e-18,
         1.51991108e-17,   6.13590727e-17,   2.47707636e-16,
         1.00000000e-15,   4.03701726e-15,   1.62975083e-14,
         6.57933225e-14,   2.65608778e-13,   1.07226722e-12,
         4.32876128e-12,   1.7475

array([  173.64,    45.97,   141.66,   164.88,    67.96,    98.47,
        3309.8 ,  2896.76,  3359.25,  1861.97,  3344.01,  3371.75,
        2855.36,  1423.13,  1721.38,  1323.62,  2396.68,  2472.15,
        3028.27,  2877.71,  2024.25,  2314.1 ,  1174.9 ,  1723.63,
        3348.91,  2683.3 ,  1873.73,  2684.27,  2083.07,   998.65,
         976.5 ,  1868.49,  1076.1 ,  1073.56,  3326.93,  2265.29,
         644.52,   298.64,  3059.32,  1083.5 ,  1001.19,   322.13,
        2543.24,   692.62,  2478.78,   198.71,  1031.47,  2457.56,
        1801.74,   216.12,  1925.99,  2125.54,  2239.73,   747.33,
         810.75,   462.77,  2106.02,   218.82,  1634.05,  1802.26,
        1332.56,  2142.12,   462.06])

array([  953.3429758,  -390.6570242,   761.3429758,   889.3429758,
         -70.6570242,   249.3429758,  2369.3429758,  2401.3429758,
        2401.3429758,  2369.3429758,  2497.3429758,  2401.3429758,
        2497.3429758,  2401.3429758,  2433.3429758,  2369.3429758,
        2369.3429758,  2465.3429758,  2369.3429758,  2497.3429758,
        2465.3429758,  2401.3429758,  2433.3429758,  2465.3429758,
        2433.3429758,  2345.3429758,  1577.3429758,  2473.3429758,
        2089.3429758,   809.3429758,   681.3429758,  1577.3429758,
         681.3429758,   681.3429758,  2729.3429758,  1961.3429758,
         297.3429758,    41.3429758,  2729.3429758,   681.3429758,
         681.3429758,    41.3429758,  1961.3429758,   425.3429758,
        2361.3429758,   505.3429758,  1337.3429758,  2361.3429758,
        1721.3429758,   569.3429758,  2105.3429758,  1977.3429758,
        2297.3429758,  1081.3429758,  1081.3429758,   825.3429758,
        2105.3429758,   569.3429758,  1721.3429758,  1849.3429

A: 6

{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}



array([ 173.64,   45.97,  141.66,  164.88,   67.96,   98.47])

array([ 953.3429758, -390.6570242,  761.3429758,  889.3429758,
        -70.6570242,  249.3429758])

B: 19

{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}



array([ 3309.8 ,  2896.76,  3359.25,  1861.97,  3344.01,  3371.75,
        2855.36,  1423.13,  1721.38,  1323.62,  2396.68,  2472.15,
        3028.27,  2877.71,  2024.25,  2314.1 ,  1174.9 ,  1723.63,  3348.91])

array([ 2369.3429758,  2401.3429758,  2401.3429758,  2369.3429758,
        2497.3429758,  2401.3429758,  2497.3429758,  2401.3429758,
        2433.3429758,  2369.3429758,  2369.3429758,  2465.3429758,
        2369.3429758,  2497.3429758,  2465.3429758,  2401.3429758,
        2433.3429758,  2465.3429758,  2433.3429758])

C: 19

{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}



array([ 2683.3 ,  1873.73,  2684.27,  2083.07,   998.65,   976.5 ,
        1868.49,  1076.1 ,  1073.56,  3326.93,  2265.29,   644.52,
         298.64,  3059.32,  1083.5 ,  1001.19,   322.13,  2543.24,   692.62])

array([ 2345.3429758,  1577.3429758,  2473.3429758,  2089.3429758,
         809.3429758,   681.3429758,  1577.3429758,   681.3429758,
         681.3429758,  2729.3429758,  1961.3429758,   297.3429758,
          41.3429758,  2729.3429758,   681.3429758,   681.3429758,
          41.3429758,  1961.3429758,   425.3429758])

D: 19

{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}



array([ 2478.78,   198.71,  1031.47,  2457.56,  1801.74,   216.12,
        1925.99,  2125.54,  2239.73,   747.33,   810.75,   462.77,
        2106.02,   218.82,  1634.05,  1802.26,  1332.56,  2142.12,   462.06])

array([ 2361.3429758,   505.3429758,  1337.3429758,  2361.3429758,
        1721.3429758,   569.3429758,  2105.3429758,  1977.3429758,
        2297.3429758,  1081.3429758,  1081.3429758,   825.3429758,
        2105.3429758,   569.3429758,  1721.3429758,  1849.3429758,
        1593.3429758,  2041.3429758,   761.3429758])

【【】】adding new model for datasetIPPD.pickle 

【【【】】】newScore: 82975140439308480.000000 
____________________________________________________________________________________________________


In [12]:
t_print = t_ridge

for key in t_print.keys():
    print(80*'_')
    
    print('Model: %s' % (str(t_print[key]['model'])[:200]))
    print('Train RMSE: %f \n' % (t_print[key]['train_rmse_cv_picking']))
    
    #print('Test RMSE   : %f' % (t_print[key]['test_rmse_reporting']))
    #print('Overall Test Mean: %f \n' % (t_print[key]['test_mean_y_comparing']))
    
    print('A...TestA RMSE   : %f' % (t_print[key]['test_rmse_reportingA']))
    print('A...<<y_test_A Mean>>: %f \n' % (t_print[key]['test_mean_y_comparingA']))
    
    print('B...TestB RMSE   : %f' % (t_print[key]['test_rmse_reportingB']))
    print('B...<<y_test_B Mean>>: %f \n' % (t_print[key]['test_mean_y_comparingB']))
    
    print('C...TestC RMSE   : %f' % (t_print[key]['test_rmse_reportingC']))
    print('C...<<y_test_C Mean>>: %f \n' % (t_print[key]['test_mean_y_comparingC']))
    
    print('D...TestD RMSE   : %f' % (t_print[key]['test_rmse_reportingD']))
    print('D...<<y_test_D Mean>>: %f' % (t_print[key]['test_mean_y_comparingD']))
    
    print(80*'_')

________________________________________________________________________________
Model: Ridge(alpha=1e-35, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=1e-06)
Train RMSE: 82975140439308480.000000 

A...TestA RMSE   : 539.970804
A...<<y_test_A Mean>>: 115.430000 

B...TestB RMSE   : 739.945299
B...<<y_test_B Mean>>: 2464.612105 

C...TestC RMSE   : 345.040494
C...<<y_test_C Mean>>: 1608.160526 

D...TestD RMSE   : 231.242938
D...<<y_test_D Mean>>: 1378.651579
________________________________________________________________________________


In [13]:
write_model_4c4(t_ridge, 'ridge')

4C4_ridge_tuned_ABCD.pickle


# Elastic Net

In [14]:
########################### Test ElasticNet with Scaling ###########################
#
# the L1 and L2 regularizers of linear models) assume that all features are 
# centered around 0 and have variance in the same order

In [15]:
t_elasticNet = wrapper([ElasticNetCVModel])



{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}

Dataset size read: train 258 and test 63 

# Tuning hyper-parameters 
[{'l1_ratio': [0.9, 0.75, 0.5, 0.25, 0.1], 'alpha': array([  1.00000000e-25,   1.91448198e-24,   3.66524124e-23,
         7.01703829e-22,   1.34339933e-20,   2.57191381e-19,
         4.92388263e-18,   9.42668455e-17,   1.80472177e-15,
         3.45510729e-14,   6.61474064e-13,   1.26638017e-11,
         2.42446202e-10,   4.64158883e-09,   8.88623816e-08,
         1.70125428e-06,   3.25702066e-05,   6.23550734e-04,
         1.19377664e-02,   2.28546386e-01,   4.37547938e+00,
         8.37677640e+01,   1.60371874e+03,   3.07029063e+04,
         5.87801607e+05,   1.12533558e+07,   2.15443469e+08,
         4.12462638e+09,   7.89652287e+10,   1.51177507e+12,
         2.89426612e+13,   5.54102033e+14,   1.06081836e+16,
         2.03091762e+17,   3.88815518e+18,   7.44380301e+19,
         1.42510267e+21,   2.72833338e+22,   5.223345

/usr/local/lib/python3.4/dist-packages/sklearn/linear_model/coordinate_descent.py:484: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
/usr/local/lib/python3.4/dist-packages/sklearn/linear_model/coordinate_descent.py:484: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
/usr/local/lib/python3.4/dist-packages/sklearn/linear_model/coordinate_descent.py:484: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
/usr/local/lib/python3.4/dist-packages/sklearn/linear_model/coordinate_descent.py:484: ConvergenceWarning: Objective did not converge. You might want to increase the number of


Best parameters set found on development set:

{'l1_ratio': 0.5, 'alpha': 8.8862381627434068e-08}
ElasticNet(alpha=8.8862381627434068e-08, copy_X=True, fit_intercept=True,
      l1_ratio=0.5, max_iter=10000000.0, normalize=False, positive=False,
      precompute=False, random_state=None, selection='cyclic', tol=1e-20,
      warm_start=False)

Full Test Set: 63


/usr/local/lib/python3.4/dist-packages/sklearn/linear_model/coordinate_descent.py:484: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)


array([  173.64,    45.97,   141.66,   164.88,    67.96,    98.47,
        3309.8 ,  2896.76,  3359.25,  1861.97,  3344.01,  3371.75,
        2855.36,  1423.13,  1721.38,  1323.62,  2396.68,  2472.15,
        3028.27,  2877.71,  2024.25,  2314.1 ,  1174.9 ,  1723.63,
        3348.91,  2683.3 ,  1873.73,  2684.27,  2083.07,   998.65,
         976.5 ,  1868.49,  1076.1 ,  1073.56,  3326.93,  2265.29,
         644.52,   298.64,  3059.32,  1083.5 ,  1001.19,   322.13,
        2543.24,   692.62,  2478.78,   198.71,  1031.47,  2457.56,
        1801.74,   216.12,  1925.99,  2125.54,  2239.73,   747.33,
         810.75,   462.77,  2106.02,   218.82,  1634.05,  1802.26,
        1332.56,  2142.12,   462.06])

array([  738.45857638,  -487.65147508,   522.7364739 ,   715.3524476 ,
        -216.85434865,    45.08001139,  2315.10030944,  2337.76913067,
        2338.20643822,  2313.96330981,  2384.41869578,  2338.20643822,
        2383.98138823,  2336.59722615,  2359.94233667,  2313.49109737,
        2314.42977119,  2383.74815753,  2314.86707875,  2383.98138823,
        2383.28169614,  2337.30266928,  2361.312567  ,  2383.04846545,
        2361.312567  ,  2577.04348321,  1853.81138931,  2623.25574077,
        2265.01339389,  1100.7257665 ,  1054.51350894,  1876.91751809,
        1031.40738016,  1031.40738016,  2988.24548779,  2195.69500755,
         695.49446771,   333.49007359,  2965.13935901,  1054.51350894,
        1031.40738016,   333.49007359,  2195.69500755,   718.60059649,
        2108.50091388,   384.89350084,  1176.29411762,  2108.50091388,
        1584.6321938 ,   431.1057584 ,  1892.7788114 ,  1823.46042506,
        2085.3947851 ,   937.46588637,   937.46588637,   666.0856832 ,
      

A: 6

{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}



array([ 173.64,   45.97,  141.66,  164.88,   67.96,   98.47])

array([ 738.45857638, -487.65147508,  522.7364739 ,  715.3524476 ,
       -216.85434865,   45.08001139])

B: 19

{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}



array([ 3309.8 ,  2896.76,  3359.25,  1861.97,  3344.01,  3371.75,
        2855.36,  1423.13,  1721.38,  1323.62,  2396.68,  2472.15,
        3028.27,  2877.71,  2024.25,  2314.1 ,  1174.9 ,  1723.63,  3348.91])

array([ 2315.10030944,  2337.76913067,  2338.20643822,  2313.96330981,
        2384.41869578,  2338.20643822,  2383.98138823,  2336.59722615,
        2359.94233667,  2313.49109737,  2314.42977119,  2383.74815753,
        2314.86707875,  2383.98138823,  2383.28169614,  2337.30266928,
        2361.312567  ,  2383.04846545,  2361.312567  ])

C: 19

{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}



array([ 2683.3 ,  1873.73,  2684.27,  2083.07,   998.65,   976.5 ,
        1868.49,  1076.1 ,  1073.56,  3326.93,  2265.29,   644.52,
         298.64,  3059.32,  1083.5 ,  1001.19,   322.13,  2543.24,   692.62])

array([ 2577.04348321,  1853.81138931,  2623.25574077,  2265.01339389,
        1100.7257665 ,  1054.51350894,  1876.91751809,  1031.40738016,
        1031.40738016,  2988.24548779,  2195.69500755,   695.49446771,
         333.49007359,  2965.13935901,  1054.51350894,  1031.40738016,
         333.49007359,  2195.69500755,   718.60059649])

D: 19

{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}



array([ 2478.78,   198.71,  1031.47,  2457.56,  1801.74,   216.12,
        1925.99,  2125.54,  2239.73,   747.33,   810.75,   462.77,
        2106.02,   218.82,  1634.05,  1802.26,  1332.56,  2142.12,   462.06])

array([ 2108.50091388,   384.89350084,  1176.29411762,  2108.50091388,
        1584.6321938 ,   431.1057584 ,  1892.7788114 ,  1823.46042506,
        2085.3947851 ,   937.46588637,   937.46588637,   666.0856832 ,
        1869.67268262,   454.21188718,  1584.6321938 ,  1653.95058014,
        1392.0162201 ,  1846.56655384,   619.87342564])

【【】】adding new model for datasetIPPD.pickle 

【【【】】】newScore: 1447.282493 
____________________________________________________________________________________________________


In [16]:
t_print = t_elasticNet

for key in t_print.keys():
    print(80*'_')
    
    
    print('Model: %s' % (str(t_print[key]['model'])[:200]))
    print('Train RMSE: %f \n' % (t_print[key]['train_rmse_cv_picking']))
    
    #print('Test RMSE   : %f' % (t_print[key]['test_rmse_reporting']))
    #print('Overall Test Mean: %f \n' % (t_print[key]['test_mean_y_comparing']))
    
    print('A...TestA RMSE   : %f' % (t_print[key]['test_rmse_reportingA']))
    print('A...<<y_test_A Mean>>: %f \n' % (t_print[key]['test_mean_y_comparingA']))
    
    print('B...TestB RMSE   : %f' % (t_print[key]['test_rmse_reportingB']))
    print('B...<<y_test_B Mean>>: %f \n' % (t_print[key]['test_mean_y_comparingB']))
    
    print('C...TestC RMSE   : %f' % (t_print[key]['test_rmse_reportingC']))
    print('C...<<y_test_C Mean>>: %f \n' % (t_print[key]['test_mean_y_comparingC']))
    
    print('D...TestD RMSE   : %f' % (t_print[key]['test_rmse_reportingD']))
    print('D...<<y_test_D Mean>>: %f' % (t_print[key]['test_mean_y_comparingD']))
    
    print(80*'_')

________________________________________________________________________________
Model: ElasticNet(alpha=8.8862381627434068e-08, copy_X=True, fit_intercept=True,
      l1_ratio=0.5, max_iter=10000000.0, normalize=False, positive=False,
      precompute=False, random_state=None, selection
Train RMSE: 1447.282493 

A...TestA RMSE   : 435.120826
A...<<y_test_A Mean>>: 115.430000 

B...TestB RMSE   : 750.314696
B...<<y_test_B Mean>>: 2464.612105 

C...TestC RMSE   : 130.674899
C...<<y_test_C Mean>>: 1608.160526 

D...TestD RMSE   : 213.881577
D...<<y_test_D Mean>>: 1378.651579
________________________________________________________________________________


In [17]:
write_model_4c4(t_elasticNet, 'elasticNet')

4C4_elasticNet_tuned_ABCD.pickle


<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:><:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>
<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:><:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>
<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:><:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>
<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:><:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>


# Which features were given most weights by each model ?

In [18]:
names = ['ppn', 'sizeGB', 'ft1', 'ft2', 'ft3', 'ft4', 'ft5', 'ft6', 'ft7', 'ft8',
        'ft9', 'ft10', 'ft11', 'ft12', 'ft13', 'ft14', 'ft15', 'ft16', 'ft17',
        'ft18', 'ft24', 'ft25', 'ft19', 'ft39', 'ft20', 'ft33', 'ft21', 'ft35',
        'ft22', 'ft23', 'ft34', 'ft36', 'ft37', 'ft38', 'ft40', 'ft41', 'ft42',
        'ft43', 'ft44', 'ft45', 'ft46', 'ft48', 'ft47', 'ft49', 'ft51', 'ft50',
        'ft52', 'ft53', 'ft54', 'ft55', 'ft26', 'ft27', 'ft28', 'ft29', 'ft30',
        'ft31', 'ft32']

In [19]:
for v in t_lasso.values():
    _model = v['model']
    print(sorted(zip(map(lambda x: x, _model.coef_), names), reverse=True))

[(1439.7134843626532, 'ft51'), (897.73452067572532, 'sizeGB'), (448.85522170722203, 'ft39'), (25.485851158238937, 'ppn'), (-0.0, 'ft9'), (-0.0, 'ft8'), (-0.0, 'ft7'), (-0.0, 'ft6'), (-0.0, 'ft55'), (0.0, 'ft54'), (0.0, 'ft53'), (0.0, 'ft52'), (0.0, 'ft50'), (-0.0, 'ft5'), (-0.0, 'ft49'), (-0.0, 'ft48'), (0.0, 'ft47'), (-0.0, 'ft46'), (-0.0, 'ft45'), (-0.0, 'ft44'), (-0.0, 'ft43'), (-0.0, 'ft42'), (0.0, 'ft41'), (0.0, 'ft4'), (0.0, 'ft38'), (0.0, 'ft37'), (0.0, 'ft36'), (0.0, 'ft35'), (0.0, 'ft34'), (-0.0, 'ft33'), (-0.0, 'ft32'), (-0.0, 'ft30'), (-0.0, 'ft3'), (0.0, 'ft29'), (-0.0, 'ft28'), (-0.0, 'ft27'), (0.0, 'ft26'), (-0.0, 'ft25'), (0.0, 'ft24'), (0.0, 'ft23'), (0.0, 'ft22'), (0.0, 'ft21'), (-0.0, 'ft20'), (-0.0, 'ft2'), (-0.0, 'ft19'), (0.0, 'ft18'), (-0.0, 'ft17'), (-0.0, 'ft16'), (0.0, 'ft15'), (0.0, 'ft14'), (-0.0, 'ft13'), (0.0, 'ft12'), (-0.0, 'ft11'), (-0.0, 'ft10'), (-0.0, 'ft1'), (-720.79375672984895, 'ft31'), (-1043.2569532783223, 'ft40')]


In [20]:
for v in t_ridge.values():
    _model = v['model']
    print(sorted(zip(map(lambda x: x, _model.coef_), names), reverse=True))

[(1.0557433476106722e+17, 'ft32'), (93447260301598848.0, 'ft50'), (87222081211474464.0, 'ft49'), (80468313560991280.0, 'ft8'), (77988289550408176.0, 'ft46'), (57468659176805720.0, 'ft3'), (55659134518764712.0, 'ft30'), (55573274485594832.0, 'ft20'), (49273518355102192.0, 'ft33'), (43407163303467824.0, 'ft40'), (39779289180837960.0, 'ft53'), (37272524540724600.0, 'ft39'), (31533646835232356.0, 'ft23'), (31412328328051912.0, 'ft48'), (26949112077402332.0, 'ft24'), (26582628295690988.0, 'ft34'), (24441803099304340.0, 'ft26'), (21697899349518380.0, 'ft6'), (20094353398267796.0, 'ft29'), (16429947949994218.0, 'ft7'), (12158286314749768.0, 'ft25'), (227177044045035.12, 'ft42'), (948.11024970241749, 'sizeGB'), (42.092097700175557, 'ppn'), (-261060168566267.56, 'ft35'), (-1694858536561839.5, 'ft47'), (-1907051792187175.5, 'ft36'), (-2303801175694840.0, 'ft17'), (-2830350179750439.0, 'ft45'), (-7654576285663127.0, 'ft51'), (-7986859244370676.0, 'ft9'), (-8081312815078147.0, 'ft52'), (-855797680

In [21]:
for v in t_elasticNet.values():
    _model = v['model']
    print(sorted(zip(map(lambda x: x, _model.coef_), names), reverse=True))

[(897.83993626942356, 'sizeGB'), (490.31550739590563, 'ft4'), (468.52329005442976, 'ft39'), (427.55774922354539, 'ft41'), (388.01629270970864, 'ft29'), (350.54473750081428, 'ft51'), (342.75814717472929, 'ft47'), (274.67218562264685, 'ft35'), (209.02418357089815, 'ft14'), (166.89245779818884, 'ft32'), (157.41324049934749, 'ft24'), (149.75220401265059, 'ft26'), (124.25449038510841, 'ft11'), (120.40246478347743, 'ft21'), (95.05905649333819, 'ft33'), (93.422229101502097, 'ft20'), (83.088020752328575, 'ft34'), (60.177770775412064, 'ft12'), (56.428886552508828, 'ft8'), (27.526391072306858, 'ft19'), (25.500947599466343, 'ppn'), (18.634404369351888, 'ft48'), (16.055185798254694, 'ft45'), (15.046278184623638, 'ft43'), (0.030346675318476277, 'ft53'), (0.0, 'ft38'), (0.0, 'ft18'), (0.0, 'ft15'), (-14.81378880327167, 'ft23'), (-15.563631256724772, 'ft44'), (-20.390456320207576, 'ft7'), (-32.184768375742848, 'ft10'), (-38.954979281117396, 'ft55'), (-56.249375742429592, 'ft54'), (-63.941741494136146