In [1]:
# import all the filenames
from allfunctions import *

In [2]:
%load_ext autoreload
%autoreload 2

7  def SVRSigmoidCVModel(filename):

8 def SVRRbfCVModel(filename):

In [3]:
def wrapper(functionList = [], filenames = [ 'datasetIPPD.pickle' ]):
    if __name__ == '__main__':
        global model_selection
        
        global c
        initialize_c()
                
        model_selection = {}
        
        for f in functionList:
            print()
            for filename in filenames:
                out = f(filename)
                newScore = out[filename]['train_rmse_cv_picking']

                if f in model_selection:
                    #compare scores and select more accurate model
                    oldScore = model_selection[f]['train_rmse_cv_picking']
                    if(newScore < oldScore):
                        print("【【【】】】switching models for %s..." % filename)
                        print("【【【】】】newScore: %f < oldScore: %f" % (newScore, oldScore))
                        print("【【【】】】newModel: %s \n" % f)
                        print(100*'_')
                        model_selection[f] = out[filename]
                else:
                    #no score to compare
                    print("【【】】adding new model for %s \n" % filename)
                    print("【【【】】】newScore: %f " % (newScore))
                    print(100*'_')
                    model_selection[f] = out[filename]
    return model_selection

<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:><:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>
<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:><:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>
<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:><:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>
<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:><:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>


# Sigmoid Kernel

In [4]:
t_SVRSigmoidCVModel = wrapper([ SVRSigmoidCVModel ])



{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}

Dataset size read: train 258 and test 63 

# Tuning hyper-parameters 

Starting grdsurch.fit(X_train, y_train)

Best parameters set found on development set:

{'epsilon': 1.0, 'C': 1.0, 'gamma': 0.10000000000000001, 'coef0': 5.0, 'degree': 3}
SVR(C=1.0, cache_size=204800, coef0=5.0, degree=3, epsilon=1.0,
  gamma=0.10000000000000001, kernel='sigmoid', max_iter=-1,
  shrinking=False, tol=1e-07, verbose=False)

Full Test Set: 63


array([  173.64,    45.97,   141.66,   164.88,    67.96,    98.47,
        3309.8 ,  2896.76,  3359.25,  1861.97,  3344.01,  3371.75,
        2855.36,  1423.13,  1721.38,  1323.62,  2396.68,  2472.15,
        3028.27,  2877.71,  2024.25,  2314.1 ,  1174.9 ,  1723.63,
        3348.91,  2683.3 ,  1873.73,  2684.27,  2083.07,   998.65,
         976.5 ,  1868.49,  1076.1 ,  1073.56,  3326.93,  2265.29,
         644.52,   298.64,  3059.32,  1083.5 ,  1001.19,   322.13,
        2543.24,   692.62,  2478.78,   198.71,  1031.47,  2457.56,
        1801.74,   216.12,  1925.99,  2125.54,  2239.73,   747.33,
         810.75,   462.77,  2106.02,   218.82,  1634.05,  1802.26,
        1332.56,  2142.12,   462.06])

array([ 1629.319977  ,  1621.19008929,  1627.93350934,  1629.17795618,
        1623.09048568,  1624.84747658,  1615.79393129,  1615.84221345,
        1615.84548667,  1615.78556317,  1616.29548144,  1615.84548667,
        1616.29224286,  1615.83344236,  1616.00362715,  1615.78208798,
        1615.78899616,  1616.29051565,  1615.79221469,  1616.29224286,
        1616.28706133,  1615.83872213,  1616.0139047 ,  1616.28533421,
        1616.0139047 ,  1617.10690235,  1619.81739128,  1619.28854649,
        1620.09729052,  1622.85008978,  1620.64011586,  1620.99703512,
        1619.76509461,  1619.76509461,  1617.27524961,  1617.06538702,
        1622.61166085,  1624.71674622,  1616.27926117,  1620.64011586,
        1619.76509461,  1624.71674622,  1617.06538702,  1623.77811103,
        1630.68322972,  1617.56474823,  1623.56809798,  1630.68322972,
        1626.68490459,  1617.81835357,  1628.97125084,  1628.47884669,
        1630.52301041,  1621.74560644,  1621.74560644,  1619.62393623,
      

A: 6

{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}



array([ 173.64,   45.97,  141.66,  164.88,   67.96,   98.47])

array([ 1629.319977  ,  1621.19008929,  1627.93350934,  1629.17795618,
        1623.09048568,  1624.84747658])

B: 19

{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}



array([ 3309.8 ,  2896.76,  3359.25,  1861.97,  3344.01,  3371.75,
        2855.36,  1423.13,  1721.38,  1323.62,  2396.68,  2472.15,
        3028.27,  2877.71,  2024.25,  2314.1 ,  1174.9 ,  1723.63,  3348.91])

array([ 1615.79393129,  1615.84221345,  1615.84548667,  1615.78556317,
        1616.29548144,  1615.84548667,  1616.29224286,  1615.83344236,
        1616.00362715,  1615.78208798,  1615.78899616,  1616.29051565,
        1615.79221469,  1616.29224286,  1616.28706133,  1615.83872213,
        1616.0139047 ,  1616.28533421,  1616.0139047 ])

C: 19

{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}



array([ 2683.3 ,  1873.73,  2684.27,  2083.07,   998.65,   976.5 ,
        1868.49,  1076.1 ,  1073.56,  3326.93,  2265.29,   644.52,
         298.64,  3059.32,  1083.5 ,  1001.19,   322.13,  2543.24,   692.62])

array([ 1617.10690235,  1619.81739128,  1619.28854649,  1620.09729052,
        1622.85008978,  1620.64011586,  1620.99703512,  1619.76509461,
        1619.76509461,  1617.27524961,  1617.06538702,  1622.61166085,
        1624.71674622,  1616.27926117,  1620.64011586,  1619.76509461,
        1624.71674622,  1617.06538702,  1623.77811103])

D: 19

{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}



array([ 2478.78,   198.71,  1031.47,  2457.56,  1801.74,   216.12,
        1925.99,  2125.54,  2239.73,   747.33,   810.75,   462.77,
        2106.02,   218.82,  1634.05,  1802.26,  1332.56,  2142.12,   462.06])

array([ 1630.68322972,  1617.56474823,  1623.56809798,  1630.68322972,
        1626.68490459,  1617.81835357,  1628.97125084,  1628.47884669,
        1630.52301041,  1621.74560644,  1621.74560644,  1619.62393623,
        1628.89892404,  1618.0757043 ,  1626.68490459,  1627.18896677,
        1625.24880856,  1628.7336418 ,  1619.33765658])

【【】】adding new model for datasetIPPD.pickle 

【【【】】】newScore: 1093968.987519 
____________________________________________________________________________________________________


In [5]:
t_print = t_SVRSigmoidCVModel

for key in t_print.keys():
    print(80*'_')
    
    print('Model: %s' % (str(t_print[key]['model'])[:200]))
    print('Train RMSE: %f \n' % (t_print[key]['train_rmse_cv_picking']))
    
    #print('Test RMSE   : %f' % (t_print[key]['test_rmse_reporting']))
    #print('Overall Mean: %f \n' % (t_print[key]['test_mean_y_comparing']))
    
    print('A...TestA RMSE   : %f' % (t_print[key]['test_rmse_reportingA']))
    print('A...y_test_A Mean: %f \n' % (t_print[key]['test_mean_y_comparingA']))
    
    print('B...TestB RMSE   : %f' % (t_print[key]['test_rmse_reportingB']))
    print('B...y_test_B Mean: %f \n' % (t_print[key]['test_mean_y_comparingB']))
    
    print('C...TestC RMSE   : %f' % (t_print[key]['test_rmse_reportingC']))
    print('C...y_test_C Mean: %f \n' % (t_print[key]['test_mean_y_comparingC']))
    
    print('D...TestD RMSE   : %f' % (t_print[key]['test_rmse_reportingD']))
    print('D...y_test_D Mean: %f' % (t_print[key]['test_mean_y_comparingD']))
    
    print(80*'_')

________________________________________________________________________________
Model: SVR(C=1.0, cache_size=204800, coef0=5.0, degree=3, epsilon=1.0,
  gamma=0.10000000000000001, kernel='sigmoid', max_iter=-1,
  shrinking=False, tol=1e-07, verbose=False)
Train RMSE: 1093968.987519 

A...TestA RMSE   : 1511.167264
A...y_test_A Mean: 115.430000 

B...TestB RMSE   : 1127.156361
B...y_test_B Mean: 2464.612105 

C...TestC RMSE   : 924.600652
C...y_test_C Mean: 1608.160526 

D...TestD RMSE   : 831.421247
D...y_test_D Mean: 1378.651579
________________________________________________________________________________


In [6]:
# write the model
import pickle

#||||||||||||||||||| 
t_ = t_SVRSigmoidCVModel
prefix = '4C4_' + 'SVRSigmoidCVModel'
#||||||||||||||||||| 

for k in t_.keys():
    mo   = t_[k]['model']
    fname = prefix + '_tuned_ABCD' + '.pickle'
       
    print(fname)
    # write the model to a file
    with open(fname, 'wb') as handle:
        pickle.dump(mo, handle)

4C4_SVRSigmoidCVModel_tuned_ABCD.pickle


# Linear Kernel

In [7]:
t_SVRLinearCVModel = wrapper([ SVRLinearCVModel ])



{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}

Dataset size read: train 258 and test 63 

# Tuning hyper-parameters 

Starting grdsurch.fit(X_train, y_train)

 Best parameters set found on development set:

{'epsilon': 50.0, 'C': 1.0, 'gamma': 1e-08, 'coef0': 0.0, 'degree': 3}
SVR(C=1.0, cache_size=204800, coef0=0.0, degree=3, epsilon=50.0, gamma=1e-08,
  kernel='linear', max_iter=-1, shrinking=False, tol=1e-07, verbose=False)

Full Test Set: 63


array([  173.64,    45.97,   141.66,   164.88,    67.96,    98.47,
        3309.8 ,  2896.76,  3359.25,  1861.97,  3344.01,  3371.75,
        2855.36,  1423.13,  1721.38,  1323.62,  2396.68,  2472.15,
        3028.27,  2877.71,  2024.25,  2314.1 ,  1174.9 ,  1723.63,
        3348.91,  2683.3 ,  1873.73,  2684.27,  2083.07,   998.65,
         976.5 ,  1868.49,  1076.1 ,  1073.56,  3326.93,  2265.29,
         644.52,   298.64,  3059.32,  1083.5 ,  1001.19,   322.13,
        2543.24,   692.62,  2478.78,   198.71,  1031.47,  2457.56,
        1801.74,   216.12,  1925.99,  2125.54,  2239.73,   747.33,
         810.75,   462.77,  2106.02,   218.82,  1634.05,  1802.26,
        1332.56,  2142.12,   462.06])

array([ 1549.10184513,  1466.94637396,  1542.55980223,  1540.95183782,
        1490.33364428,  1513.1757018 ,  1658.27426093,  1666.39736629,
        1666.42426823,  1658.20431586,  1682.72428285,  1666.42426823,
        1682.6973809 ,  1666.32527397,  1674.48998277,  1658.17526666,
        1658.23301127,  1682.6830332 ,  1658.25991322,  1682.6973809 ,
        1682.65433779,  1666.36867088,  1674.57427554,  1682.63999008,
        1674.57427554,  1715.9326531 ,  1678.17000349,  1732.23266772,
        1710.1945924 ,  1638.57084761,  1622.27083299,  1686.3200108 ,
        1614.12082569,  1614.12082569,  1747.95724201,  1685.74457048,
        1606.91355996,  1591.3726363 ,  1739.8072347 ,  1622.27083299,
        1614.12082569,  1591.3726363 ,  1685.74457048,  1615.06356727,
        1529.81876529,  1410.33005425,  1479.20057174,  1529.81876529,
        1484.13465024,  1426.63006887,  1523.27672238,  1498.82670046,
        1521.66875798,  1464.50852153,  1464.50852153,  1441.08538194,
      

A: 6

{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}



array([ 173.64,   45.97,  141.66,  164.88,   67.96,   98.47])

array([ 1549.10184513,  1466.94637396,  1542.55980223,  1540.95183782,
        1490.33364428,  1513.1757018 ])

B: 19

{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}



array([ 3309.8 ,  2896.76,  3359.25,  1861.97,  3344.01,  3371.75,
        2855.36,  1423.13,  1721.38,  1323.62,  2396.68,  2472.15,
        3028.27,  2877.71,  2024.25,  2314.1 ,  1174.9 ,  1723.63,  3348.91])

array([ 1658.27426093,  1666.39736629,  1666.42426823,  1658.20431586,
        1682.72428285,  1666.42426823,  1682.6973809 ,  1666.32527397,
        1674.48998277,  1658.17526666,  1658.23301127,  1682.6830332 ,
        1658.25991322,  1682.6973809 ,  1682.65433779,  1666.36867088,
        1674.57427554,  1682.63999008,  1674.57427554])

C: 19

{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}



array([ 2683.3 ,  1873.73,  2684.27,  2083.07,   998.65,   976.5 ,
        1868.49,  1076.1 ,  1073.56,  3326.93,  2265.29,   644.52,
         298.64,  3059.32,  1083.5 ,  1001.19,   322.13,  2543.24,   692.62])

array([ 1715.9326531 ,  1678.17000349,  1732.23266772,  1710.1945924 ,
        1638.57084761,  1622.27083299,  1686.3200108 ,  1614.12082569,
        1614.12082569,  1747.95724201,  1685.74457048,  1606.91355996,
        1591.3726363 ,  1739.8072347 ,  1622.27083299,  1614.12082569,
        1591.3726363 ,  1685.74457048,  1615.06356727])

D: 19

{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}



array([ 2478.78,   198.71,  1031.47,  2457.56,  1801.74,   216.12,
        1925.99,  2125.54,  2239.73,   747.33,   810.75,   462.77,
        2106.02,   218.82,  1634.05,  1802.26,  1332.56,  2142.12,   462.06])

array([ 1529.81876529,  1410.33005425,  1479.20057174,  1529.81876529,
        1484.13465024,  1426.63006887,  1523.27672238,  1498.82670046,
        1521.66875798,  1464.50852153,  1464.50852153,  1441.08538194,
        1515.12671507,  1434.78007617,  1484.13465024,  1508.58467217,
        1485.74261465,  1506.97670777,  1424.78536733])

【【】】adding new model for datasetIPPD.pickle 

【【【】】】newScore: 1102318.365660 
____________________________________________________________________________________________________


In [8]:
t_print = t_SVRLinearCVModel

for key in t_print.keys():
    print(80*'_')
    
    print('Model: %s' % (str(t_print[key]['model'])[:200]))
    print('Train RMSE: %f \n' % (t_print[key]['train_rmse_cv_picking']))
    
    #print('Test RMSE   : %f' % (t_print[key]['test_rmse_reporting']))
    #print('Overall Mean: %f \n' % (t_print[key]['test_mean_y_comparing']))
    
    print('A...TestA RMSE   : %f' % (t_print[key]['test_rmse_reportingA']))
    print('A...y_test_A Mean: %f \n' % (t_print[key]['test_mean_y_comparingA']))
    
    print('B...TestB RMSE   : %f' % (t_print[key]['test_rmse_reportingB']))
    print('B...y_test_B Mean: %f \n' % (t_print[key]['test_mean_y_comparingB']))
    
    print('C...TestC RMSE   : %f' % (t_print[key]['test_rmse_reportingC']))
    print('C...y_test_C Mean: %f \n' % (t_print[key]['test_mean_y_comparingC']))
    
    print('D...TestD RMSE   : %f' % (t_print[key]['test_rmse_reportingD']))
    print('D...y_test_D Mean: %f' % (t_print[key]['test_mean_y_comparingD']))
    
    print(80*'_')

________________________________________________________________________________
Model: SVR(C=1.0, cache_size=204800, coef0=0.0, degree=3, epsilon=50.0, gamma=1e-08,
  kernel='linear', max_iter=-1, shrinking=False, tol=1e-07, verbose=False)
Train RMSE: 1102318.365660 

A...TestA RMSE   : 1401.885760
A...y_test_A Mean: 115.430000 

B...TestB RMSE   : 1086.507331
B...y_test_B Mean: 2464.612105 

C...TestC RMSE   : 873.332031
C...y_test_C Mean: 1608.160526 

D...TestD RMSE   : 769.671023
D...y_test_D Mean: 1378.651579
________________________________________________________________________________


In [9]:
# write the model
import pickle

#||||||||||||||||||| 
t_ = t_SVRLinearCVModel
prefix = '4C4_' + 'SVRLinearCVModel'
#||||||||||||||||||| 

for k in t_.keys():
    mo   = t_[k]['model']
    fname = prefix + '_tuned_ABCD' + '.pickle'
       
    print(fname)
    # write the model to a file
    with open(fname, 'wb') as handle:
        pickle.dump(mo, handle)

4C4_SVRLinearCVModel_tuned_ABCD.pickle


# Poly Kernel

In [10]:
t_SVRPolyCVModel = wrapper([ SVRPolyCVModel ])



{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}

Dataset size read: train 258 and test 63 

# Tuning hyper-parameters... 

Starting grdsurch.fit(X_train, y_train)

Best parameters set found on development set:

{'epsilon': 50.0, 'C': 1.0, 'gamma': 0.10000000000000001, 'coef0': 10.0, 'degree': 3}
SVR(C=1.0, cache_size=204800, coef0=10.0, degree=3, epsilon=50.0,
  gamma=0.10000000000000001, kernel='poly', max_iter=1000000000.0,
  shrinking=False, tol=0.01, verbose=False)

Full Test Set: 63


array([  173.64,    45.97,   141.66,   164.88,    67.96,    98.47,
        3309.8 ,  2896.76,  3359.25,  1861.97,  3344.01,  3371.75,
        2855.36,  1423.13,  1721.38,  1323.62,  2396.68,  2472.15,
        3028.27,  2877.71,  2024.25,  2314.1 ,  1174.9 ,  1723.63,
        3348.91,  2683.3 ,  1873.73,  2684.27,  2083.07,   998.65,
         976.5 ,  1868.49,  1076.1 ,  1073.56,  3326.93,  2265.29,
         644.52,   298.64,  3059.32,  1083.5 ,  1001.19,   322.13,
        2543.24,   692.62,  2478.78,   198.71,  1031.47,  2457.56,
        1801.74,   216.12,  1925.99,  2125.54,  2239.73,   747.33,
         810.75,   462.77,  2106.02,   218.82,  1634.05,  1802.26,
        1332.56,  2142.12,   462.06])

array([  641.37289317,  -110.49580795,   524.37329616,   609.78732901,
          63.1410698 ,   233.23526695,  2163.73834497,  2191.45539749,
        2191.73408735,  2163.01765535,  2244.19962467,  2191.73408735,
        2243.91783269,  2190.70857748,  2217.67658327,  2162.71834965,
        2163.31331994,  2243.76754517,  2163.59050922,  2243.91783269,
        2243.46697334,  2191.15813233,  2218.55460437,  2243.31668903,
        2218.55460437,  2535.68642761,  1815.56029568,  2587.7828875 ,
        2220.36340529,  1050.23365566,  1049.83620667,  1826.25428893,
        1041.73454123,  1041.73454123,  2959.58260472,  2152.87372283,
         682.97592391,   299.0507519 ,  2924.28542141,  1049.83620667,
        1041.73454123,   299.0507519 ,  2152.87372283,   674.13715368,
        2049.36005446,   412.76110136,  1145.45896774,  2049.36005446,
        1545.71013041,   444.625231  ,  1837.23932139,  1774.56657671,
        2027.48966356,   917.16677372,   917.16677372,   666.06508889,
      

A: 6

{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}



array([ 173.64,   45.97,  141.66,  164.88,   67.96,   98.47])

array([ 641.37289317, -110.49580795,  524.37329616,  609.78732901,
         63.1410698 ,  233.23526695])

B: 19

{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}



array([ 3309.8 ,  2896.76,  3359.25,  1861.97,  3344.01,  3371.75,
        2855.36,  1423.13,  1721.38,  1323.62,  2396.68,  2472.15,
        3028.27,  2877.71,  2024.25,  2314.1 ,  1174.9 ,  1723.63,  3348.91])

array([ 2163.73834497,  2191.45539749,  2191.73408735,  2163.01765535,
        2244.19962467,  2191.73408735,  2243.91783269,  2190.70857748,
        2217.67658327,  2162.71834965,  2163.31331994,  2243.76754517,
        2163.59050922,  2243.91783269,  2243.46697334,  2191.15813233,
        2218.55460437,  2243.31668903,  2218.55460437])

C: 19

{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}



array([ 2683.3 ,  1873.73,  2684.27,  2083.07,   998.65,   976.5 ,
        1868.49,  1076.1 ,  1073.56,  3326.93,  2265.29,   644.52,
         298.64,  3059.32,  1083.5 ,  1001.19,   322.13,  2543.24,   692.62])

array([ 2535.68642761,  1815.56029568,  2587.7828875 ,  2220.36340529,
        1050.23365566,  1049.83620667,  1826.25428893,  1041.73454123,
        1041.73454123,  2959.58260472,  2152.87372283,   682.97592391,
         299.0507519 ,  2924.28542141,  1049.83620667,  1041.73454123,
         299.0507519 ,  2152.87372283,   674.13715368])

D: 19

{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}



array([ 2478.78,   198.71,  1031.47,  2457.56,  1801.74,   216.12,
        1925.99,  2125.54,  2239.73,   747.33,   810.75,   462.77,
        2106.02,   218.82,  1634.05,  1802.26,  1332.56,  2142.12,   462.06])

array([ 2049.36005446,   412.76110136,  1145.45896774,  2049.36005446,
        1545.71013041,   444.625231  ,  1837.23932139,  1774.56657671,
        2027.48966356,   917.16677372,   917.16677372,   666.06508889,
        1817.45196637,   458.72958902,  1545.71013041,  1605.49168879,
        1357.0620223 ,  1796.56096102,   632.47834467])

【【】】adding new model for datasetIPPD.pickle 

【【【】】】newScore: 1173546.824938 
____________________________________________________________________________________________________


In [11]:
t_print = t_SVRPolyCVModel

for key in t_print.keys():
    print(80*'_')
    
    print('Model: %s' % (str(t_print[key]['model'])[:20]))
    print('Train RMSE: %f \n' % (t_print[key]['train_rmse_cv_picking']))
    
    #print('Test RMSE   : %f' % (t_print[key]['test_rmse_reporting']))
    #print('Overall Mean: %f \n' % (t_print[key]['test_mean_y_comparing']))
    
    print('A...TestA RMSE   : %f' % (t_print[key]['test_rmse_reportingA']))
    print('A...y_test_A Mean: %f \n' % (t_print[key]['test_mean_y_comparingA']))
    
    print('B...TestB RMSE   : %f' % (t_print[key]['test_rmse_reportingB']))
    print('B...y_test_B Mean: %f \n' % (t_print[key]['test_mean_y_comparingB']))
    
    print('C...TestC RMSE   : %f' % (t_print[key]['test_rmse_reportingC']))
    print('C...y_test_C Mean: %f \n' % (t_print[key]['test_mean_y_comparingC']))
    
    print('D...TestD RMSE   : %f' % (t_print[key]['test_rmse_reportingD']))
    print('D...y_test_D Mean: %f' % (t_print[key]['test_mean_y_comparingD']))
    
    print(80*'_')

________________________________________________________________________________
Model: SVR(C=1.0, cache_siz
Train RMSE: 1173546.824938 

A...TestA RMSE   : 317.766294
A...y_test_A Mean: 115.430000 

B...TestB RMSE   : 785.936757
B...y_test_B Mean: 2464.612105 

C...TestC RMSE   : 143.027711
C...y_test_C Mean: 1608.160526 

D...TestD RMSE   : 242.965511
D...y_test_D Mean: 1378.651579
________________________________________________________________________________


In [12]:
# write the model
import pickle

#||||||||||||||||||| 
t_ = t_SVRPolyCVModel
prefix = '4C4_' + 'SVRPolyCVModel'
#||||||||||||||||||| 

for k in t_.keys():
    mo   = t_[k]['model']
    fname = prefix + '_tuned_ABCD' + '.pickle'
       
    print(fname)
    # write the model to a file
    with open(fname, 'wb') as handle:
        pickle.dump(mo, handle)

4C4_SVRPolyCVModel_tuned_ABCD.pickle


# rbf Kernel

In [13]:
t_SVRRbfCVModel = wrapper([ SVRRbfCVModel ])



{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}

Dataset size read: train 258 and test 63 

# Tuning hyper-parameters 

Starting grdsurch.fit(X_train, y_train)

Best parameters set found on development set:

{'epsilon': 10.0, 'C': 1.0, 'gamma': 0.01, 'coef0': 0.0, 'degree': 3}
SVR(C=1.0, cache_size=204800, coef0=0.0, degree=3, epsilon=10.0, gamma=0.01,
  kernel='rbf', max_iter=-1, shrinking=False, tol=1e-07, verbose=False)

Full Test Set: 63


array([  173.64,    45.97,   141.66,   164.88,    67.96,    98.47,
        3309.8 ,  2896.76,  3359.25,  1861.97,  3344.01,  3371.75,
        2855.36,  1423.13,  1721.38,  1323.62,  2396.68,  2472.15,
        3028.27,  2877.71,  2024.25,  2314.1 ,  1174.9 ,  1723.63,
        3348.91,  2683.3 ,  1873.73,  2684.27,  2083.07,   998.65,
         976.5 ,  1868.49,  1076.1 ,  1073.56,  3326.93,  2265.29,
         644.52,   298.64,  3059.32,  1083.5 ,  1001.19,   322.13,
        2543.24,   692.62,  2478.78,   198.71,  1031.47,  2457.56,
        1801.74,   216.12,  1925.99,  2125.54,  2239.73,   747.33,
         810.75,   462.77,  2106.02,   218.82,  1634.05,  1802.26,
        1332.56,  2142.12,   462.06])

array([ 1612.08221731,  1612.19480083,  1612.37618388,  1611.89264395,
        1612.30882118,  1612.48857637,  1616.59668132,  1616.80019217,
        1616.80004721,  1616.59705674,  1617.16540815,  1616.80004721,
        1617.16554728,  1616.80058062,  1616.99317373,  1616.59721265,
        1616.59690272,  1617.16562148,  1616.59675833,  1617.16554728,
        1617.16576988,  1616.80034679,  1616.99272512,  1617.16584408,
        1616.99272512,  1620.59951829,  1619.63588349,  1620.62166013,
        1620.15383103,  1618.53552664,  1618.4751023 ,  1619.62725805,
        1618.38635366,  1618.38635366,  1621.13847186,  1620.00899449,
        1617.97210569,  1617.44525422,  1621.0911248 ,  1618.4751023 ,
        1618.38635366,  1617.44525422,  1620.00899449,  1617.99095591,
        1610.44257969,  1610.28686866,  1610.75249189,  1610.44257969,
        1610.13626373,  1610.58953465,  1610.71707991,  1610.13574767,
        1610.24666077,  1610.78227494,  1610.78227494,  1610.54140576,
      

A: 6

{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}



array([ 173.64,   45.97,  141.66,  164.88,   67.96,   98.47])

array([ 1612.08221731,  1612.19480083,  1612.37618388,  1611.89264395,
        1612.30882118,  1612.48857637])

B: 19

{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}



array([ 3309.8 ,  2896.76,  3359.25,  1861.97,  3344.01,  3371.75,
        2855.36,  1423.13,  1721.38,  1323.62,  2396.68,  2472.15,
        3028.27,  2877.71,  2024.25,  2314.1 ,  1174.9 ,  1723.63,  3348.91])

array([ 1616.59668132,  1616.80019217,  1616.80004721,  1616.59705674,
        1617.16540815,  1616.80004721,  1617.16554728,  1616.80058062,
        1616.99317373,  1616.59721265,  1616.59690272,  1617.16562148,
        1616.59675833,  1617.16554728,  1617.16576988,  1616.80034679,
        1616.99272512,  1617.16584408,  1616.99272512])

C: 19

{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}



array([ 2683.3 ,  1873.73,  2684.27,  2083.07,   998.65,   976.5 ,
        1868.49,  1076.1 ,  1073.56,  3326.93,  2265.29,   644.52,
         298.64,  3059.32,  1083.5 ,  1001.19,   322.13,  2543.24,   692.62])

array([ 1620.59951829,  1619.63588349,  1620.62166013,  1620.15383103,
        1618.53552664,  1618.4751023 ,  1619.62725805,  1618.38635366,
        1618.38635366,  1621.13847186,  1620.00899449,  1617.97210569,
        1617.44525422,  1621.0911248 ,  1618.4751023 ,  1618.38635366,
        1617.44525422,  1620.00899449,  1617.99095591])

D: 19

{{ scale_this: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling X_train and X_test... }}



array([ 2478.78,   198.71,  1031.47,  2457.56,  1801.74,   216.12,
        1925.99,  2125.54,  2239.73,   747.33,   810.75,   462.77,
        2106.02,   218.82,  1634.05,  1802.26,  1332.56,  2142.12,   462.06])

array([ 1610.44257969,  1610.28686866,  1610.75249189,  1610.44257969,
        1610.13626373,  1610.58953465,  1610.71707991,  1610.13574767,
        1610.24666077,  1610.78227494,  1610.78227494,  1610.54140576,
        1610.43515414,  1610.86931546,  1610.13626373,  1610.71983258,
        1610.44874217,  1610.23820546,  1610.23828345])

【【】】adding new model for datasetIPPD.pickle 

【【【】】】newScore: 1083775.362152 
____________________________________________________________________________________________________


In [14]:
t_print = t_SVRRbfCVModel

for key in t_print.keys():
    print(80*'_')
    
    print('Model: %s' % (str(t_print[key]['model'])[:20]))
    print('Train RMSE: %f \n' % (t_print[key]['train_rmse_cv_picking']))
    
    #print('Test RMSE   : %f' % (t_print[key]['test_rmse_reporting']))
    #print('Overall Mean: %f \n' % (t_print[key]['test_mean_y_comparing']))
    
    print('A...TestA RMSE   : %f' % (t_print[key]['test_rmse_reportingA']))
    print('A...y_test_A Mean: %f \n' % (t_print[key]['test_mean_y_comparingA']))
    
    print('B...TestB RMSE   : %f' % (t_print[key]['test_rmse_reportingB']))
    print('B...y_test_B Mean: %f \n' % (t_print[key]['test_mean_y_comparingB']))
    
    print('C...TestC RMSE   : %f' % (t_print[key]['test_rmse_reportingC']))
    print('C...y_test_C Mean: %f \n' % (t_print[key]['test_mean_y_comparingC']))
    
    print('D...TestD RMSE   : %f' % (t_print[key]['test_rmse_reportingD']))
    print('D...y_test_D Mean: %f' % (t_print[key]['test_mean_y_comparingD']))
    
    print(80*'_')

________________________________________________________________________________
Model: SVR(C=1.0, cache_siz
Train RMSE: 1083775.362152 

A...TestA RMSE   : 1497.569885
A...y_test_A Mean: 115.430000 

B...TestB RMSE   : 1126.484189
B...y_test_B Mean: 2464.612105 

C...TestC RMSE   : 921.208515
C...y_test_C Mean: 1608.160526 

D...TestD RMSE   : 831.750214
D...y_test_D Mean: 1378.651579
________________________________________________________________________________


In [15]:
# write the model
import pickle

#||||||||||||||||||| 
t_ = t_SVRRbfCVModel
prefix = '4C4_' + 'SVRRbfCVModel'
#||||||||||||||||||| 

for k in t_.keys():
    mo   = t_[k]['model']
    fname = prefix + '_tuned_ABCD' + '.pickle'
       
    print(fname)
    # write the model to a file
    with open(fname, 'wb') as handle:
        pickle.dump(mo, handle)

4C4_SVRRbfCVModel_tuned_ABCD.pickle


# Which features were given most weights by each model ?